### ISSUE TITLE
Key does not work

### ISSUE THREAD

**Issue by sinuso** [aandrew-me/tgpt#101]
The new key is no longer valid.

```
Some error has occurred.
Trying to get new app key
No new app key found. Try again later.
```

**Comment by Brunno-Linux** [comment]
I have this problem to./У меня та же проблема. Arch linux.

**Comment by levysoft** [comment]
I have the same problem since this morning, too

**Comment by aindriu80** [comment]
Some error has occurred.
Trying to get new app key
No new app key found. Try again later.

**Comment by datxuantran** [comment]
I also have the same problem

**Comment by gns23** [comment]
Same problem here! Worked like a charm before the recent change..

**Comment by aandrew-me** [comment]
No api keys for now ¯\_(ツ)_/¯

**Comment by davidesottosanti** [comment]
me too 🥲

**Comment by onurcangnc** [comment]
Same issue :(

**Comment by jancordeiro** [comment]
Same here.

**Comment by kagerou-hikari** [comment]
```
Some error has occurred.
Trying to get new app key
No new app key found. Try again later. 
```

**Comment by gns23** [comment]
Solved! Thank you so much!

**Comment by levysoft** [comment]
Yes, it's solved for me too. Thanks

**Comment by onurcangnc** [comment]
Hi I got new errors.

<img width="568" alt="Screen Shot 2023-09-25 at 14 49 44" src="https://github.com/aandrew-me/tgpt/assets/55115769/154ed775-37c8-4264-84e2-eeb9bbc52da3">
