### ISSUE TITLE
Key auto change to default api key on running

### ISSUE THREAD

**Issue by kagerou-hikari** [aandrew-me/tgpt#102]
If you edit the key in the file located at ~/.config/tgpt/key.txt, and then run tgpt, it will revert back to the default key. run tgpt, it will revert back to the default key.

**Comment by sinuso** [comment]
![image](https://github.com/aandrew-me/tgpt/assets/11968484/11c3bd83-268e-4c4a-bc31-59fdfa2d47c5)

**Comment by aandrew-me** [comment]
> If you edit the key in the file located at ~/.config/tgpt/key.txt, and then run tgpt, it will revert back to the default key. run tgpt, it will revert back to the default key.

I tried it myself and it worked fine. Key should be like this: `KEY:api_key_in_base_64`

**Comment by aandrew-me** [comment]
Api will be changed in next update and keys will become irrelevant again
