### ISSUE TITLE
Again the key does not work.

### ISSUE THREAD

**Issue by sinuso** [aandrew-me/tgpt#104]
The new key is no longer valid.

```
Some error has occurred.
Trying to get new app key
No new app key found. Try again later.
```

**Comment by aandrew-me** [comment]
I changed the backend, I will push update tomorrow

**Comment by gns23** [comment]
thx for info and your great work!

**Comment by sinuso** [comment]
> I changed the backend, I will push update tomorrow

Thank you and good night
