### ISSUE TITLE
Access my paid Chat GPT PLUS  subscription as API?

### ISSUE THREAD

**Issue by Free-Radical** [aandrew-me/tgpt#106]
I pay for my gpt 4 access (GPT PLUS) thru browser, app, etc. OpenAI doesn't allow us to use this subscription for API (unless I've missed something pls correct me if im wrong) and wants to charge separately for API access! which is bullshit!

What would it take to "re-route" tgpt etc to seem like calls are originating from the GPT app or Browser window?

Any leads would be appreciated!!!

**Comment by aandrew-me** [comment]
You can't do that with tgpt. And it's complex, it would likely require cookies (which would require to be changed frequently). And certainly openai doesn't want you to do this. So better not go that way.

You can search, you may find something.

**Comment by Free-Radical** [comment]
Ok cool. Thx. 
I know it could be done in a kludgy way using selenium but was hoping someone had solved the problem.

**Comment by aandrew-me** [comment]
You may check the repo gpt4free
