### ISSUE TITLE
No new app key found

### ISSUE THREAD

**Issue by 0x4hm3d0x** [aandrew-me/tgpt#108]
~ $ tgpt hi
Some error has occurred.
Trying to get new app key
No new app key found. Try again later.

**Comment by aandrew-me** [comment]
Update to latest version

**Comment by Free-Radical** [comment]
Little off topic: Is the key now kept as a Github secret?

**Comment by Free-Radical** [comment]
You are the man!

**Comment by aandrew-me** [comment]
> You are the man! PS is the access GPT3.5 or 4? it seems to claims its 3.5

GPT 3.5
