### ISSUE TITLE
Can't install  the new update of tgpt :  Unsupported architecture: armv8l

### ISSUE THREAD

**Issue by 0x4hm3d0x** [aandrew-me/tgpt#110]
~ $ curl -sSL https://raw.githubusercontent.com/aandrew-me/tgpt/main/install | bash -s /usr/local/bin
Download location: /usr/local/bin
Unsupported architecture: armv8l
 I also try install it usign go but it now work..

**Comment by aandrew-me** [comment]
Is it android?

**Comment by 0x4hm3d0x** [comment]
> Is it android?

Yes termux

**Comment by 0x4hm3d0x** [comment]
I already run it before on temrux and it was work very well

**Comment by aandrew-me** [comment]
Yes install script won't work for termux. You need to use go install. So update won't work
