### ISSUE TITLE
Hey I got new errors after an update.

### ISSUE THREAD

**Issue by onurcangnc** [aandrew-me/tgpt#113]
<img width="568" alt="Screen Shot 2023-09-28 at 08 47 22" src="https://github.com/aandrew-me/tgpt/assets/55115769/21d3fcfe-4af2-440d-8677-14a1be0c33d3">

**Comment by aandrew-me** [comment]
Are you using latest version? 1.9.0

**Comment by onurcangnc** [comment]
I have not been sudo. That's why, I could not update and not recognized. Thanks :)
