### ISSUE TITLE
"--quiet", "-q", "-w" and "-whole" not working?

### ISSUE THREAD

**Issue by sinuso** [aandrew-me/tgpt#115]
For a while now there is no response when using `tgpt -q` or `tgpt --quiet` `tgpt -w` and `tgpt -whole`

![image](https://github.com/aandrew-me/tgpt/assets/11968484/5f0fb100-bbed-4c17-9977-5969259d912e)

**Comment by aandrew-me** [comment]
The website has implemented verification :(

**Comment by sinuso** [comment]
> The website has implemented verification :(

 There is no way to avoid Loading?
From terminal there is no problem, but for example if you use a web page that queries tgpt the responses are like `⣾ Loading⣽ Loading⣻ Loading⢿ Loading⡿ Loading⣟ Loading⣯ Loading⣷ Loading⣾ Loading⣽ Loading hello`

**Comment by aandrew-me** [comment]
There is, with -q and -w. When you created the issue, nothing was working, not even just `tgpt 'some message'`. I pushed update with a temporary fix, once I get time I will push update fixing other options too

**Comment by sinuso** [comment]
Is `Loading⣻` 100% necessary when --quiet is not used?

The result using graphical interfaces is terrible and difficult to filter.

![image](https://github.com/aandrew-me/tgpt/assets/11968484/22495ba0-1f41-4405-8623-15b42b0f0e50)

**Comment by aandrew-me** [comment]
I am pushing an update
