### ISSUE TITLE
Unauthorized - Access token is missing "401 Unauthorized"

### ISSUE THREAD

**Issue by sleeping-miyagi** [aandrew-me/tgpt#118]
When running tgpt, the following error occurs:

```
user@archlinux:~$ tgpt "What is internet?"
What is internet?


{"error":{"code":"error","message":{"message":"Unauthorized - Access token is missing"},"param":null,"type":"401 Unauthorized"}}
```

This is using the latest version from the AUR

```
user@archlinux:~$ tgpt -u
You are already using the latest version. v1.10.0
```

It was working fine when I updated to v1.10.0 but it now produces the mentioned error after a few hours.

**Comment by pitsi** [comment]
Same thing here, although I only get the empty lines and not the error one
```
$ tgpt-linux-amd64 "what is 10 times 6"
what is 10 times 6




```
Debian unstable x64, using tgpt 1.10.0 from the provided binary here. The same happens with the latest 1.9.x, so it is not the app's fault.
