### ISSUE TITLE
It has stopped working again.

### ISSUE THREAD

**Issue by sinuso** [aandrew-me/tgpt#119]
It does not return a response either with or without a flag.

**Comment by gns23** [comment]
#118 

Same here, seems someone got an error before it went silent..

**Comment by aandrew-me** [comment]
Well looks like the website has stopped working (

**Comment by aindriu80** [comment]
same here, just get a print out of the question but no answer.... 

also the update doesn't work - tgpt -u does nothing, you have to run 
`curl -sSL https://raw.githubusercontent.com/aandrew-me/tgpt/main/install | bash -s /usr/local/bin`

**Comment by aandrew-me** [comment]
Update coming

**Comment by chw90** [comment]
It's still not working for me with version 2.0.2 (installed from AUR):

````
~> tgpt 'Why is tgpt not giving answers?'
Why is tgpt not giving answers?
```
