### ISSUE TITLE
Didn't work?

### ISSUE THREAD

**Issue by kokizzu** [aandrew-me/tgpt#120]
tried from latest:
```
[21:52:55] kyz :: pop2204  ➜  ~ » go install github.com/aandrew-me/tgpt@latest
go: downloading github.com/aandrew-me/tgpt v1.10.0
go: downloading github.com/bogdanfinn/fhttp v0.5.22
go: downloading github.com/bogdanfinn/tls-client v1.3.11
go: downloading github.com/charmbracelet/bubbles v0.15.0
go: downloading github.com/charmbracelet/bubbletea v0.24.0
go: downloading github.com/olekukonko/ts v0.0.0-20171002115256-78ecb04241c0
go: downloading github.com/mattn/go-localereader v0.0.1
go: downloading github.com/containerd/console v1.0.4-0.20230313162750-1ae8d489ac81
go: downloading github.com/muesli/ansi v0.0.0-20211018074035-2e021307bc4b
go: downloading github.com/muesli/cancelreader v0.2.2
go: downloading github.com/muesli/termenv v0.15.1
go: downloading github.com/tam7t/hpkp v0.0.0-20160821193359-2b70b4024ed5
go: downloading github.com/charmbracelet/lipgloss v0.6.0
go: downloading github.com/atotto/clipboard v0.1.4
go: downloading github.com/bogdanfinn/utls v1.5.16
go: downloading github.com/aymanbagabas/go-osc52/v2 v2.0.1
[23:44:03] kyz :: pop2204  ➜  ~ » tgpt 'write me quicksort using golang'
write me quicksort using golang



[23:44:15] kyz :: pop2204  ➜  ~ » tgpt 'write me mergesort using golang'
write me mergesort using golang



```

^ empty XD

**Comment by kokizzu** [comment]
after `tgpt -u` now it works '__') so the latest branch is broken?

**Comment by aandrew-me** [comment]
Interesting, let me check

**Comment by kokizzu** [comment]
also another issuq, `tgpt -q -i` is broken
```
tgpt -q -i                                                                                                                                                                                                                                             Hello! How can I assist you today?% 
```
does not show prompt and still show animation

**Comment by aandrew-me** [comment]
> also another issue, `tgpt -q -i` is broken
> 
> ```
> tgpt -q -i                                                                                                                                                                                                                                             Hello! How can I assist you today?% 
> ```
> 
> does not show prompt and still show animation

There is no such option as `tgpt -q -i`, you have to use them separately

**Comment by aandrew-me** [comment]
> after `tgpt -u` now it works '__') so the latest branch is broken?

I don't know why go package manager thinks 1.10.0 is the latest version https://pkg.go.dev/github.com/aandrew-me/tgpt?tab=versions

**Comment by aandrew-me** [comment]
> after `tgpt -u` now it works '__') so the latest branch is broken?

I think I needed to update the version in go.mod file. So the installation command would look like
go install github.com/aandrew-me/tgpt/v2@latest

**Comment by kokizzu** [comment]
might be because no `v2/go.mod` file
https://go.dev/blog/v2-go-modules

**Comment by aandrew-me** [comment]
The new command to install with go is `go install github.com/aandrew-me/tgpt/v2@latest`
