### ISSUE TITLE
Not used for a day or two but got - reached our limit of messages per 24 hours

### ISSUE THREAD

**Issue by Pi-MONSTER** [aandrew-me/tgpt#123]
2.0.2 wasn't responding so updated to 2.0.3
And getting this now, tried using a vpn but same error.
Take it that refers to your limit reached, not mine.

Some error has occurred. Statuscode: 429
{"error":{"code":"error","message":"You've reached our limit of messages per 24 hours. Please try again later.","param":null,"type":"429 Too Many Requests"}}

**Comment by aandrew-me** [comment]
It depends on your IP. Wait some seconds and try again

**Comment by Pi-MONSTER** [comment]
No change still getting
Statuscode: 429

**Comment by Quinta0** [comment]
I have this error: 
Some error has occurred. Statuscode: 502

**Comment by aandrew-me** [comment]
Changed api
