### ISSUE TITLE
Error -> post : chatgptlogin.ai : /chat/chat_api_stream : x509 : certificate : invalid

### ISSUE THREAD

**Issue by kenny-kvibe** [aandrew-me/tgpt#126]
I just saw you've updated your repo, so I updated tgpt, but now I got a different error after trying to run it (There's "//" before "chat" in the URL, possible bug?):
```
Some error has occurred. Check your internet connection.

Error: Post "https://chatgptlogin.ai//chat/chat_api_stream": x509: certificate is not valid for any names, but wanted to match chatgptlogin.ai
```

![image](https://github.com/aandrew-me/tgpt/assets/16114808/5cc40285-362b-4bb2-b4b8-675e1bcd74fb)

*AND* after 5 minutes I tried again and now It works, I changed nothing.

![image](https://github.com/aandrew-me/tgpt/assets/16114808/cb0808d1-0cb9-493d-8592-9afaca76a332)

So now I'm just posting this, letting you know.

**Comment by aandrew-me** [comment]
The APIs keep getting overloaded and stop working

**Comment by kenny-kvibe** [comment]
Maybe this could help you make it more stable:
`https://github.com/xtekky/gpt4free/tree/main/g4f/Provider` (from [g4f](https://pypi.org/project/g4f/))
I'm thinking of integrating it with tgpt via the local proxy method.

**Comment by aandrew-me** [comment]
> Maybe this could help you make it more stable: [`github.com/xtekky/gpt4free/tree/main/g4f/Provider`](https://github.com/xtekky/gpt4free/tree/main/g4f/Provider) (from [g4f](https://pypi.org/project/g4f/)) I'm thinking of integrating it with tgpt via the local proxy 

Its possible. But for that g4f needs to always be running a python server which is already beyond the scope of this program. G4f already provides an API in python, so there may be some program utilizing it. However even with plenty of providers integrated, I face problems getting proper responses.

**Comment by kenny-kvibe** [comment]
Hmm, try changing your [`functions.go:454`](https://github.com/aandrew-me/tgpt/blob/dd28ac78aeefea0c93bb1a629ac941df25c5d399/functions.go#L454) to be like [`tls-client/example/main.go:68`](https://github.com/bogdanfinn/tls-client/blob/e3bf4c30d7a0f0fac6a2636871935e3aeedbeac3/example/main.go#L68)
 by using more headers from xtekky repos folder "Provider", I think that should help, other than that I don't know much about Golang.

**Comment by aandrew-me** [comment]
Its not about headers. I am also receiving this certificate error but only on MacOs and even in browser. So it has something to do with mac

**Comment by kenny-kvibe** [comment]
Have you tried installing the certificate in the browser and trying then just in the browser?
I never used an Apple device, but as far as I know Apple's Safari is like MS's Internet Explorer - a browser to download other browsers.

**Comment by aandrew-me** [comment]
> Have you tried installing the certificate in the browser and trying then just in the browser? I never used an Apple device, but as far as I know Apple's Safari is like MS's Internet Explorer - a browser to download other browsers.

Its working fine on Macos now

**Comment by kenny-kvibe** [comment]
Awesome!
