### ISSUE TITLE
tgpt 2.0.4 Some error has occurred. Statuscode: 403

### ISSUE THREAD

**Issue by victor03303** [aandrew-me/tgpt#129]
Dear

Thank you for sharing your work. I wanted to inform you of this error.

https://pastes.io/0aqgtizurd

**Comment by Paulo-2048** [comment]
Same here

**Comment by brucevoin** [comment]
same error.

**Comment by pablingas** [comment]
**Some error has occurred. Statuscode: 502**
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by victor03303** [comment]
> **Some error has occurred. Statuscode: 502**
> <title>502 Bad Gateway</title>
> # 502 Bad Gateway
> nginx


Do you have the same version installed?
It's a different error code

**Comment by Paulo-2048** [comment]
I think that erro (502), has already been resolved in last update version.

View the issue #124

**Comment by mistersenpai** [comment]
I noticed in the readme, the current API is: chatgptlogin.ai/chat.

When trying to access this site manually, it appears to be taken down, thus it's probably the fact the API key, tgpt is no longer working.

**Comment by sinuso** [comment]
> I noticed in the readme, the current API is: chatgptlogin.ai/chat.
> 
> When trying to access this site manually, it appears to be taken down, thus it's probably the fact the API key, tgpt is no longer working.

I think it's been many versions since that api has been used.

**Comment by alexaldearroyo** [comment]
I've got this error too:


**Some error has occurred. Statuscode: 502**
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by rickychii** [comment]
Same here
![image](https://github.com/aandrew-me/tgpt/assets/129695864/7925737c-dd23-4938-b67b-602bc01777cf)

I'm on Debian 13 Trixie

**Comment by aandrew-me** [comment]
Update coming with new api

**Comment by victor03303** [comment]
resolved in tgpt 2.0.5.
Thank you very much aandrew-me!
