### ISSUE TITLE
Line wrapping

### ISSUE THREAD

**Issue by Olejja** [aandrew-me/tgpt#13]
Hello.

Is there any trick or way to use line wrapping (shift + enter)? When you try to send a request with a script, it looks like this:

```
tgpt 'What does this code do? #!/bin/bash                                                                                                  ~

url=$(xclip -o) 

if [[ $url =~ ^(https?://) ]]; then 
  mpv "$url" --title='${media-title}'
fi
'
What does this code do? #!/bin/bash                                                                                                  ~

url=$(xclip -o) 

if [[ $url =~ ^(https?://) ]]; then 
  mpv \"$url\" --title=title
fi


Error. Your IP is being blocked by the server.
Status Code: 400
```

**Comment by aandrew-me** [comment]
It looks fine, its just the backend server has setup some protection that when it sees these special characters, it blocks the request. That's why you are getting an error.

**Comment by aandrew-me** [comment]
In these cases use the site instead.

You have these two sites which don't require any login
https://chatbot.theb.ai/
https://www.phind.com/
