### ISSUE TITLE
Give possibility to generate images

### ISSUE THREAD

**Issue by rickychii** [aandrew-me/tgpt#131]
I can suggest a simple command option, such as example: `tgpt -img [prompt]` and let the AI generate the image relative to input description and save it in your current pwd.

Example
------

**input**:
`tgpt -img "a blue Ferrari"` 

**output**
a jpeg or png file saved in local file system with the sport car

**Comment by aandrew-me** [comment]
Image generation is a whole different story. It needs different APIs. Give me an image generation api and I may consider

**Comment by rickychii** [comment]
Hi @aandrew-me

I think https://ai.fakeopen.com can work also with image generation, try to make POST curl to this endpoint:
`https://ai.fakeopen.com/v1/images/generations`


and in here there are specifications for make the API call:
`https://platform.openai.com/docs/api-reference/images/object`

Le me know if you can work with this input or if you need more specifications about.

-R

**Comment by aandrew-me** [comment]
Sadly its not working...

**Comment by rickychii** [comment]
It should be api key problem, if we discover how to use an api key compatible with image generations I think it's done.

You could consider to use 2 api keys, one for text, one for image.

-R

**Comment by rickychii** [comment]
### Ignore what I said before

I found this free AI tool:

`https://api.craiyon.com/v3` (Post request)

header:
"Content-Type": "application-json"

body:
`
{
  "prompt": "a blue ferrari",
  "token": null,
  "model": "photo",
  "negative_prompt": "",
  "version": "c4ue22fb7kb6wlac"
}
`
it's a bit slower (1 minute per request ~~) but it's completly free.

Notice response will be an array of 9 pictures, such as example:
`
"images": [
   "2023-10-21/dac24e913b744b48ad2b2d0d07ad4ee505578f16.webp"
]
`
you need to:
- cycle the array
- compose the complete image url, which will result something like: 'https://img.craiyon.com/' + images[i]
- save the image in local path

See by yourself if want to save all whole 9 images array or just one of them. I would say let's save all images.

Please tell me what do you think and if you are agree to implement this. I'm available for any necessity.

-R

**Comment by aandrew-me** [comment]
I am getting cloudflare errors

**Comment by sinuso** [comment]
@aandrew-me Not possible with your [textToImage](https://github.com/aandrew-me/textToImage) application?

**Comment by aandrew-me** [comment]
Ok its working now. textToImage uses API Keys. I don't want to bring API Keys back to this app

**Comment by sinuso** [comment]
> Ok its working now. textToImage uses API Keys. I don't want to bring API Keys back to this app

The app does not update to the new code:

```
:~$ tgpt -u
You are already using the latest version. v2.0.5
```

**Comment by aandrew-me** [comment]
> > Ok its working now. textToImage uses API Keys. I don't want to bring API Keys back to this app
> 
> The app does not update to the new code:
> 
> ```
> :~$ tgpt -u
> You are already using the latest version. v2.0.5
> ```

Well because I haven't pushed the update yet

**Comment by rickychii** [comment]
Downloaded latest version and it's working. Great implementation!
-R
