### ISSUE TITLE
Infinite "Loading..." than error code 524

### ISSUE THREAD

**Issue by snoopyonline78** [aandrew-me/tgpt#133]
I installed tgpt with apt and manually, but inserting a question, the app stays on "Loading..." for a long time, and then gives the Error 524.

What can i do?

thanks a lot

D.

**Comment by ConradoCps** [comment]
I am have same issue

**Comment by aandrew-me** [comment]
Looks like the api is down, I am changing it to a different api for now

**Comment by snoopyonline78** [comment]
Thanks a lot!
