### ISSUE TITLE
ChatGPT may not have enough time to print the result

### ISSUE THREAD

**Issue by Monsterovich** [aandrew-me/tgpt#136]
If the response to the request is received very slowly, tgpt will exit by timeout with this error.

```
Some error has occurred. Error: net/http: request canceled (Client.Timeout or context cancellation while reading body)
```

**Comment by aandrew-me** [comment]
How did you get that error

**Comment by Monsterovich** [comment]
> How did you get that error

ChatGPT can sometimes be very slow to produce a response and if it doesn't make it in time, tgpt will drop a timeout error.

**Comment by aandrew-me** [comment]
In that case just press Ctrl + C and do again
