### ISSUE TITLE
input and output in multi-line

### ISSUE THREAD

**Issue by fastfading** [aandrew-me/tgpt#139]
the terminal is too wide .
so it is difficult to read the answer.
enhance this with auto change line  for each sentence . 

both the input and output did not support multiline very well. 
find a way to resolve this

**Comment by fastfading** [comment]
terminal program is not good at  gui  
may be we need a gui or web version  for this

**Comment by aandrew-me** [comment]
There are many apps for android and websites. Like perplexity.ai. Use those

**Comment by aandrew-me** [comment]
> terminal program is not good at gui may be we need a gui or web version for this

Your statement is self contradictory.
