### ISSUE TITLE
Add an interactive mode

### ISSUE THREAD

**Issue by vanhyr** [aandrew-me/tgpt#14]
Hey , great project I'm personally enjoying it a lot!

I think it should have an **interactive mode** for entering `tgpt` with no arguments for just start talking with the IA instead of typing `tgpt "<the query>"` every time you want to use it. My **personal approach** would be something like this:

```sh
tgpt
> query here
> response here
```

Probably also consider adding a way to **visually differenciate** the questions and the answers. Also the program should just wait for an `exit` command to **terminate** the interactive session.

Thanks for your effort, I'll try to implement the feature if I have the time.

**Comment by aandrew-me** [comment]
Hey! I am glad it helped you.

I think it would be great to implement such a thing. By this time I would have already implemented it, but I am trying to solve this problem and I am failing to. Are you a Go dev, cause your help would be highly appreciated.

**Comment by pxsxs** [comment]
if anyone is interested, I made this little python script to use tgpt in interactive mode on linux, consider this as a temporary workaround until interactive mode is officially implemented :)

```
import subprocess

while True:
    prompt = input()
    subprocess.run(["tgpt", prompt])
    print(" ")
```

to terminate just press Ctrl + C

**Comment by aandrew-me** [comment]
Added

**Comment by omaru-ok** [comment]
if would be better if we have more feature like [AICHAT](https://github.com/sigoden/aichat#features) i was using it early ,but my api is finished
