### ISSUE TITLE
Multiline mode missing visible cursor and slow pasting

### ISSUE THREAD

**Issue by khlsvr** [aandrew-me/tgpt#140]
Hey, is this my terminal issue but in my urxvt I don't see the cursor marker where the input currently is when I launch tgpt with `tgpt -m`. I have to type something to see where the text is coming to get a hunch where I am at.

Then another nuisance is that when I paste a code snippet to the multiline field for analysis, it takes a very long time for it to paste as it may take multiple seconds per line to have it pasted to the input field. 

Other than that and the currently missing history problem which you are aware of already due to api changes etc, good job!

**Comment by aandrew-me** [comment]
Use Ctrl + Shift + V to paste

**Comment by khlsvr** [comment]
Thank you this works. The cursor in multiline mode is indeed a problem with my rxvt-unicode it seems. When I run `tgpt -m` inside tmux on urxvt, it does show up, but not stand-alone in urxvt. The cursor is also visible in the terminal called `st`. In xterm it doesn't work either though. I have some settings in ~/.Xresources for xterm and urxvt but I'm not sure if they cause it. I tried commenting out all color lines from 0 to 15 with an exclamation mark like `!URxvt.color0:  #3f3f3f` but that didn't help. Oh well, this is an issue suitable solved somewhere else.
