### ISSUE TITLE
Broken ? 

### ISSUE THREAD

**Issue by Welding-Torch** [aandrew-me/tgpt#141]
I'm on Ubuntu WSL. I first tried the curl install command, and it kept hanging. So then I decided to try the go install command and here's what happened: 
```
$ go install github.com/aandrew-me/tgpt/v2@latest
go: github.com/aandrew-me/tgpt/v2@latest: module github.com/aandrew-me/tgpt/v2: Get "https://proxy.golang.org/github.com/aandrew-me/tgpt/v2/@v/list": dial tcp 142.251.42.113:443: i/o timeout
```
So yeah, I can't seem to install it.

**Comment by aandrew-me** [comment]
Looks like you have connection issues in WSL, I can't help with that, could be DNS issues.

**Comment by Welding-Torch** [comment]
I checked, and you're right. Guess it was an Hyper-V issue since I've been experimenting with Virtual Machines more lately, and changing a setting else where might have cause WSL connectivity to stop. Thanks.
