### ISSUE TITLE
Quota exhausted

### ISSUE THREAD

**Issue by sinuso** [aandrew-me/tgpt#142]
More than 24 hours with this result, I have only made 2 requests
```
:~$ tgpt -q "hi"
当前地区当日额度已消耗完
```

当前地区当日额度已消耗完 > The quota for the current day in the current region has been exhausted.

**Comment by sinuso** [comment]
```
$ tgpt -q "hi"
Some error has occurred. Statuscode: 502
An internal error occurred with Vercel.

BAD_GATEWAY
```

**Comment by aandrew-me** [comment]
Whenever I check I see everything is okay. If you get errors, try again

**Comment by sinuso** [comment]
> Whenever I check I see everything is okay. If you get errors, try again

Since we used the new API I only have problems... I don't know if it is due to IP or region.
98% of queries are with "当前地区当日额度已消耗完" or "Some error has occurred. Statuscode: 502"

```
$ tgpt -q "hola"
当前地区当日额度已消耗完
```
Honestly, I liked the version with the Openai API better... if the key failed, I could replace it with a functional one.

**Comment by sinuso** [comment]
@aandrew-me  3 hours testing and with 3 IP (1 from Germany and 2 from Spain)

```
tgpt@test:~$ tgpt hola
hola

当前地区当日额度已消耗完

tgpt@test:~$ tgpt hi
hi

当前地区当日额度已消耗完

tgpt@test:~$ tgpt hello
hello

当前地区当日额度已消耗完

tgpt@test:~$ tgpt morning
morning

当前地区当日额度已消耗完

tgpt@test:~$ tgpt works?
works?

当前地区当日额度已消耗完

tgpt@test:~$ tgpt testing
Some error has occurred. Statuscode: 502
An internal error occurred with Vercel.

BAD_GATEWAY

tgpt@test:~$ tgpt hello
hello

当前地区当日额度已消耗完
```

**Comment by aandrew-me** [comment]
That's sad. I don't want to go back to the API Key based approach. However if you have an OpenAI API key, you can use [shell-gpt](https://github.com/TheR1D/shell_gpt)

**Comment by sinuso** [comment]
> That's sad. I don't want to go back to the API Key based approach. However if you have an OpenAI API key, you can use [shell-gpt](https://github.com/TheR1D/shell_gpt)

Does the option to use a proxy work?
If so, where should the proxy.txt be located? In `~/.config/tgpt`?

**Comment by aandrew-me** [comment]
Currently it needs to be located in the directory in which you're in

**Comment by sinuso** [comment]
> Currently it needs to be located in the directory in which you're in

All the proxies that I find available give me this result, even if I set up a proxy myself.

```
:~$ tgpt -q hi
Some error has occurred. Check your internet connection.

Error: Post "https://s.aifree.site/api/generate": Proxy responded with non 200 code: 308 Permanent Redirect
```

**Comment by sinuso** [comment]
I have already solved! 
Thank you :)
