### ISSUE TITLE
Is there a way to install tgpt on Mac OS?

### ISSUE THREAD

**Issue by snoopyonline78** [aandrew-me/tgpt#148]
Good day,

Is there a way to install tgpt on Mac OS?

I see the tgpt-mac-arm64 file, but have no idea how to install/use it.

Is there a guide?

Kindly regards

Snoop

**Comment by aandrew-me** [comment]
There is install script in README
https://github.com/aandrew-me/tgpt#installation-

**Comment by snoopyonline78** [comment]
Thanks a lot! Will try immediately!
