### ISSUE TITLE
Statuscode: 500

### ISSUE THREAD

**Issue by tjtcdqm** [aandrew-me/tgpt#149]
Some error has occurred. Statuscode: 500
{"error":{"message":"internal server error","type":"requests","param":"fk-GUt9nBOoIGIbDDHS-NTpE0U********************","code":null}}

**Comment by kenny-kvibe** [comment]
Some error has occurred. Statuscode: 502
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"82367d34b8805ac5","b":1,"version":"2023.10.0","token":"74e2929b3b9a41338725b197dcdf931f"}' crossorigin="anonymous"></script>
</body>
</html>

**Comment by jnu2019058164** [comment]
something happen in server, maybe🤔

**Comment by MohitDabas** [comment]
Having same kind of issue! 502 bad gateway

**Comment by stanfieldr** [comment]
I was having this issue yesterday, but it seems to have resolved itself

**Comment by aandrew-me** [comment]
Yeah sometimes there maybe a problem in the server, I cant do anything about that. If problem persists for too long, I will change the backend
