### ISSUE TITLE
Interactive mode: arrow keys don't work

### ISSUE THREAD

**Issue by oren64** [aandrew-me/tgpt#153]
Hi,

First, I really like this ChatGPT terminal interface, great work.

1) As the title says, the arrows keys don't work in Interactive mode, I can't move the cursor to edit the text.

2) Will there session in Interactive mode in the future, that remember the previous questions like in ChatGPT.

Thanks

**Comment by aandrew-me** [comment]
1. That's why multiline interactive mode has been added
2. Yes I will add that logic when I get time

**Comment by oren64** [comment]
ok tanks
