### ISSUE TITLE
Write errors to stderr, exit with error codes

### ISSUE THREAD

**Issue by niutech** [aandrew-me/tgpt#160]
In many places in [functions.go](https://github.com/aandrew-me/tgpt/blob/main/functions.go) there are error handling methods like:
```go
fmt.Println("\nSome error has occurred.")
fmt.Println("Error:", err)
os.Exit(0)
```
Instead of writing to stdout, output them to stderr, like `fmt.Fprintln(os.Stderr, "\nSome error has occurred.")` or just `println("\nSome error has occurred.")`.
Finally, exit with code bigger than 0, because 0 is reserved for success.

**Comment by aandrew-me** [comment]
You're right
