### ISSUE TITLE
401 error with text, images work fine.

### ISSUE THREAD

**Issue by sinuso** [aandrew-me/tgpt#161]
It hasn't worked for more than 12 hours, it always responds with a 401 error message with random keys.
The image generation works perfectly.

I also notice that the API page has ceased to exist or has been modified.

![image](https://github.com/aandrew-me/tgpt/assets/11968484/b32a73e9-548b-4b68-a373-bc0b6a568709)

**freegpts1.aifree.site**

![image](https://github.com/aandrew-me/tgpt/assets/11968484/d386ad16-c158-417e-add6-c842b5ded380)

**chatf.aifree.site**

![image](https://github.com/aandrew-me/tgpt/assets/11968484/4ae9c47a-8e4c-42c2-a740-73a230ff4725)

**Comment by sinuso** [comment]
> Check if you still have this problem

Now the error is:
Some error has occurred. Statuscode: 429
{"detail":"rate limited."}

![image](https://github.com/aandrew-me/tgpt/assets/11968484/3b2a785f-6012-4edb-9369-00dbb4062a94)

**Comment by abaynp** [comment]
the endpoint seems stop working. we need to host pandoranext ourself or use shared pandoranext if there is any.

**Comment by sinuso** [comment]
@aandrew-me It's broken again.


![image](https://github.com/aandrew-me/tgpt/assets/11968484/3afc287d-a939-4824-9007-f21d07242fe5)

**Comment by abaynp** [comment]
@sinuso no it's not. it's just a lot of api key got banned. it uses a lot of free api key, then rotate it. however a lot of api key got banned, or out of free trial, and it's still in the pool. if u keep trying i may got response from api key that still alive.

**Comment by sinuso** [comment]
> @sinuso no it's not. it's just a lot of api key got banned. it uses a lot of free api key, then rotate it. however a lot of api key got banned, or out of free trial, and it's still in the pool. if u keep trying i may got response from api key that still alive.

It is always an error 401[1], 429, a blank response or it is waiting for a response and you have to force it to close.

[1]
{"error":{"message":"Unauthorized - Access token is missing",....
{"error":{"message":"Your OpenAI account has been deactivated, please check your email for more information. If you feel this is an error, contact us through our help center at help.openai.com."

**Comment by abaynp** [comment]
@sinuso "message":"Unauthorized - Access token is missing" "message":"Your OpenAI account has been deactivated..
means it is working just fine. Those message is comming from openai, it means this program is working as intended, which is connecting you from your local terminal to openai/fakeopen server.
It just a lot of account that used in this free method got banned.

you can always build it your self with your api key with openai endpoint, and it would be working.
simply edit with the functions.go file, then build

gen-img working fine, it use different endpoint.

**Comment by aandrew-me** [comment]
I cannot do anything about those errors. The only thing I can do is change the API, so if you have good APIs, suggest and I will change

**Comment by aandrew-me** [comment]
> > I cannot do anything about those errors. The only thing I can do is change the API, so if you have good APIs, suggest and I will change
> 
> Maybe gpt4free? It would be great to be able to use gpt4.

That repo has many APIs, I took this one from it. Many dont work. And whenever I tried using gpt4free locally I got errors

**Comment by aandrew-me** [comment]
Brave Leo is good, but it has rate limits

**Comment by sinuso** [comment]
> > > I cannot do anything about those errors. The only thing I can do is change the API, so if you have good APIs, suggest and I will change
> > 
> > 
> > Maybe gpt4free? It would be great to be able to use gpt4.
> 
> That repo has many APIs, I took this one from it. Many dont work. And whenever I tried using gpt4free locally I got errors


I'm trying this (it's bad I know) and for now it always gives me an answer.


```
import g4f
import sys

g4f.debug.logging = True  # Enable debug logging
g4f.debug.check_version = False  # Disable automatic version checking
print(g4f.Provider.Bing.params)  # Print supported args for Bing

while True:
    pregunta = input("What do you want to ask?")

    response = g4f.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": pregunta}],
        stream=True,
    )
    for message in response:
        print(message, flush=True, end='')

    respuesta_usuario = input("Do you want to ask another question?")

    if respuesta_usuario == "no":
        break
```

![image](https://github.com/aandrew-me/tgpt/assets/11968484/81d547a1-6b7b-4fbb-9f9a-63c0b6ef19cf)

**Comment by aandrew-me** [comment]
I cannot use it like this because its in Python

**Comment by sinuso** [comment]
> I cannot use it like this because its in Python

I found this API de Free-GPT4-WEB-API.
https://api.freegpt4.ddns.net/?text=hello

**Comment by aandrew-me** [comment]
Hm let me see

**Comment by aandrew-me** [comment]
This is not convenient
