### ISSUE TITLE
To long command or path

### ISSUE THREAD

**Issue by DevLenn** [aandrew-me/tgpt#162]
Hey, i'm using tgpt with windows 11 and i'm giving it a pretty long command (content of a 60kb .txt file), and because of this pretty long command, i'm facing the error, i belive it was error 207, "the command you submitted was too long" or "path to long" or sth like that.  Is there any way to bypass that? I double checked if the path or filename is to long but this doesn't seem to be the issue, and i deactivated file path length limitations as well.

**Comment by DevLenn** [comment]
i'll add steps on how to reproduce and more accurate info later :)

**Comment by aandrew-me** [comment]
I dont think there is a way to bypass this
