### ISSUE TITLE
Statuscode: 429 "error" upgrade latest PAndoraNext

### ISSUE THREAD

**Issue by gdimatis** [aandrew-me/tgpt#163]
Some error has occurred. Statuscode: 429
{
    "error": {
        "message": "It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by waikoo** [comment]
> Some error has occurred. Statuscode: 429 { "error": { "message": "It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy", "type": "invalid_request_error", "param": null, "code": null } }

same for me. reinstalling didn't help. (with `yay`)

**Comment by victor03303** [comment]
same for me
this is a general issue
not related to clients

**Comment by aandrew-me** [comment]
Looks like I need to change the api

**Comment by aandrew-me** [comment]
Update is already available

**Comment by victor03303** [comment]
thank you again aandrew!
