### ISSUE TITLE
Could you make changing the API more flexible?

### ISSUE THREAD

**Issue by xplshn** [aandrew-me/tgpt#167]
That's it, a feature request, the APIs are public and scraped, thus, unstable, I've tried to use other services but none match your project, not because of the APIs I mean, but because of how it works, the -m and -i feature are great, and its a BIG PLUS(+) that it is made in go, the only con I find is that I cannot use other APIs with tgpt. For example, OpenChat would be great to have, or KoboldAI through Horde. Not for free I mean, just add support for CHANGING the API, it could also be useful in the near future for when the API dies, for example, it would be great to have that right now:
```
Some error has occurred. Statuscode: 401
{"error":{"message":"Your OpenAI account has been deactivated, please check your email for more information. If you feel this is an error, contact us through our help center at help.openai.com.","type":"requests","param":"fk-CB6ddGnFYkVhxMbfG1w7g0o********************","code":null}}
[anto@beef ~]$ 

```

**Comment by abaynp** [comment]
I think it's not that hard to support changing endpoint and headers that come with additional file.
you can do it yourself if you understand golang.
or simply edit the function.go file and build tgpt yourself

**Comment by aandrew-me** [comment]
Definitely would be great, though it would need a lot of work, I will try once I get the time
