### ISSUE TITLE
Cyrillic encoding in Powershell (Win11) seems broken

### ISSUE THREAD

**Issue by artasolovev** [aandrew-me/tgpt#168]
Hello! Thanks for support Win users :) 

**Environment:** 

Win11 Terminal - PowerShell - Scoop Instalation

**Terminal Font:**

Comic Sans Nerd Font Mono

In multi-line interactive mode there is problem with support for encoding Cyrillic characters. The terminal has a font that supports Cyrillic. 
However, there is no problem in the bash environment on Linux. 
Something strange. 

![Снимок экрана 2023-12-10 111019](https://github.com/aandrew-me/tgpt/assets/23165372/13755f59-4e20-4cb8-bc46-0edb5f393919)

**Comment by abaynp** [comment]
I think ps only support ascii, I'm not sure what I'm talking about tho

**Comment by aandrew-me** [comment]
Interesting, could be related to your font

**Comment by artasolovev** [comment]
> Interesting, could be related to your font

I checked various fonts, including system ones, where Cyrillic is present. The encoding is still not correct :) The problem seems to be how the powershell works with multiline input.

**Comment by aandrew-me** [comment]
Hmmm I don't really know what to do here, I used a library to implement multiline input mode

**Comment by aandrew-me** [comment]
I checked in Windows powershell with Cyrilic being the default system language, no problems. So I don't think i can do anything from my side
