### ISSUE TITLE
Keeps asking for token

### ISSUE THREAD

**Issue by nikinbaidar** [aandrew-me/tgpt#169]
Some error has occurred. Statuscode: 401
{"error":{"message":"Unauthorized - Access token is missing","type":"requests","param":"fk-71CIhpldDHg9N3rOZBMxVYt********************","code":null}}

Why does it keep asking for tokens? After a few minutes it answers one question then this happens again.

**Comment by abaynp** [comment]
@nikinbaidar a lot of account got banned, u will see a lot variation of fk-xxxxxxxx, means it use different account to answer your request. Unfortunately these accounts got banned. 

get your api key instead, and edit the function.go file, then build with it
