### ISSUE TITLE
New Error: 429

### ISSUE THREAD

**Issue by snoopyonline78** [aandrew-me/tgpt#170]
tgpt "hallo"
Some error has occurred. Statuscode: 429
{
    "error": {
        "message": "It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by aandrew-me** [comment]
Which version is this?

**Comment by dev0null** [comment]
Hi I'm having a similar issue but before the 429 I get the unauthorized status code 401 and this happened after 3 questions.

tgpt "question"

**Some error has occurred. Statuscode: 401**
{"error":
{"message":"Your OpenAI account has been deactivated, please check your email for more information. If you feel this is an error, contact us through our help center at help.openai.com.",
"type":"requests",
"param":"fk-sUc3ubGsOQ3rRxyQ8duzfV4********************",
"code":null
}}

After this it gives this error:
**Some error has occurred. Statuscode: 429**
{"detail":"rate limited."}

Then I tried changing IP with a VPN and it worked for other 3  requests until I got the same error again.
The requests were made within a five-minute time span.

**Comment by niutech** [comment]
tgpt version 2.2.1:
```
Some error has occurred. Statuscode: 429
{"error":{"message":"You've reached our limit of messages per hour. Please try again later.","type":"requests","param":"fk-b8Ms7TxubmIbaMCiuBLzUud********************","code":null}}
```

**Comment by greboide** [comment]
+1 to niutech error

**Comment by JorySeverijnse** [comment]
I just installed tgpt from aur, cause i wanted to check it out. but i get the same error as @niutech. Didnt even get the chance to commincate with it. Is anyone experiencing the same issue:
```
Some error has occurred. Statuscode: 429
{"error":{"message":"You've reached our limit of messages per hour. Please try again later.","type":"requests","param":"fk-b8Ms7TxubmIbaMCiuBLzUud********************","code":null}}
```

**Comment by bortao1337zika** [comment]
Yes, same issue here. Installed from the AUR.

**Comment by aandrew-me** [comment]
Sometimes errors may occur, I tried now, its working fine

**Comment by m5kro** [comment]
the free api started rate limiting, you need to space out your requests by a few seconds now :(

**Comment by niutech** [comment]
@aandrew-me It's still not working, I get errors 429 all the time despite waiting ~30 sec. between requests. Maybe you could use another free proxy?

**Comment by snoopyonline78** [comment]
> Which version is this?

2.0.5

**Comment by snoopyonline78** [comment]
Now i updated to 2.2.1

Now this error occurs:

xxxx@Lat7400:~/libimobiledevice-glue$ tgpt -v
tgpt 2.2.1
xxxx@Lat7400:~/libimobiledevice-glue$ tgpt "Merry xmas"
Some error has occurred. Statuscode: 429
{"error":{"message":"You've reached our limit of messages per hour. Please try again later.","type":"requests","param":"fk-AfA4TsUHCxZGqnLi8gdO5dl********************","code":null}}

**Comment by aandrew-me** [comment]
Yes I think its time to change api

**Comment by sinuso** [comment]
> Yes I think its time to change api

@aandrew-me The new API already gives an error. Is there any way we can put the Liaobots authCode?

```
:~$ tgpt "hello"
Some error has occurred. Statuscode: 402
Error
```

**Comment by sameedzahoor** [comment]
It would be good to add support for the new mixtral model or other models as well.

**Comment by aandrew-me** [comment]
I am looking for an API, so if anyone has a good api, feel free to share

**Comment by aandrew-me** [comment]
I switched to brave's chat ai, it works well, but it has rate limits

**Comment by sinuso** [comment]
> I switched to brave's chat ai, it works well, but it has rate limits

I think the problem is that there are more and more people using TGPT (that's good) but the APIs limit our consumption.
I have modified the authCode of version 2.2.2 and after 60 requests I still have 0.08 points of the initial 0.10.

**Comment by niutech** [comment]
How about https://github.com/ayaka14732/ChatGPTAPIFree?

**Comment by aandrew-me** [comment]
> How about https://github.com/ayaka14732/ChatGPTAPIFree?

Check the readme, its not working anymore

**Comment by maik3531** [comment]
Since the new version, responses are only given in English, even if I ask the question in German. 

tgpt "guten tag"

 "Guten Tag" is German for "Good day".

I was answered earlier " Guten Tag, wie kann ich ihnen helfen ?" Is there a way to save the language in a config file?

**Comment by aandrew-me** [comment]
> Since the new version, responses are only given in English, even if I ask the question in German.
> 
> tgpt "guten tag"
> 
> "Guten Tag" is German for "Good day".
> 
> I was answered earlier " Guten Tag, wie kann ich ihnen helfen ?" Is there a way to save the language in a config file?

Earlier it was a different language model

**Comment by maik3531** [comment]
But when I write 'please give me the answer in German,' then it will also be given in German. However, I don't want to have to specify that the answer should be given in German every time I make a request. That's why I asked if there's a way to specify the language for answers, for example, in the '~/.config/tgpt' directory.

**Comment by aandrew-me** [comment]
> But when I write 'please give me the answer in German,' then it will also be given in German. However, I don't want to have to specify that the answer should be given in German every time I make a request. That's why I asked if there's a way to specify the language for answers, for example, in the '~/.config/tgpt' directory.

There is no way. If you have to write each time, you can create an alias in your shell

**Comment by niutech** [comment]
There are some more free LLM APIs:
- https://github.com/PawanOsman/ChatGPT and https://chat.pawan.krd
- https://github.com/waylaidwanderer/node-chatgpt-api
- https://github.com/songquanpeng/one-api and https://openai.justsong.cn
- https://github.com/find-xposed-magisk/pandora-next and https://chat.oaifree.com
- https://chat-shared3.zhile.io/
- https://github.com/xing61/xiaoyi-robot
- https://github.com/petals-infra/chat.petals.dev and https://chat.petals.dev
- https://github.com/KohnoseLami/Brave-Leo

**Comment by sameedzahoor** [comment]
There needs to be a way to ask the GPT to continue generating from where it left off (apparently because of a world limit).

**Comment by maik3531** [comment]
> > But when I write 'please give me the answer in German,' then it will also be given in German. However, I don't want to have to specify that the answer should be given in German every time I make a request. That's why I asked if there's a way to specify the language for answers, for example, in the '~/.config/tgpt' directory.
> 
> There is no way. If you have to write each time, you can create an alias in your shell

I already had voice input and voice output set up through aliases, but I can't manage to get any more functionalities working.

` alias bot='sed -i "s/duration=[0-9]\+/duration=5/g" ~/.local/bin/stt.py; output=$(tgpt -w "$(python3 ~/.local/bin/stt.py </dev/null 2>/dev/null)"); echo "$output" >> output.txt; if grep -q "Some error has occurred" output.txt; then spd-say "Entschuldigung, ich habe Sie leider nicht verstanden."; else spd-say "$(cat output.txt)"; fi; rm -f output.txt'

alias bott='sed -i "s/duration=[0-9]\+/duration=10/g" ~/.local/bin/stt.py; output=$(tgpt -w "$(python3 ~/.local/bin/stt.py </dev/null 2>/dev/null)"); echo "$output" >> output.txt; if grep -q "Some error has occurred" output.txt; then spd-say "Entschuldigung, ich habe Sie leider nicht verstanden."; fi'

alias botts='sed -i "s/duration=[0-9]\+/duration=10/g" ~/.local/bin/stt.py; output=$(tgpt -w "$(python3 ~/.local/bin/stt.py </dev/null 2>/dev/null)"); echo "$output" >> output.txt; if grep -q "Some error has occurred" output.txt; then spd-say "Entschuldigung, ich habe Sie leider nicht verstanden."; rm -f output.txt; else spd-say "$(cat output.txt)"; fi'

alias botc='sed -i "s/duration=[0-9]\+/duration=15/g" ~/.local/bin/stt.py; output=$(tgpt -c "$(python3 ~/.local/bin/stt.py </dev/null 2>/dev/null)"); echo "$output" >> output.txt; if grep -q "Some error has occurred" output.txt; then spd-say "Entschuldigung, ich habe Sie leider nicht verstanden."; rm -f output.txt; else sed -i "s/\`\`\`//g" output.txt; spd-say "code wurde generiert."; fi'

alias botb='sed -i "s/duration=[0-9]\+/duration=5/g" ~/.local/bin/stt.py; tgpt -img "$(python3 ~/.local/bin/stt.py 2>/dev/null)"; spd-say "Bilder wurden generiert."' `

**Comment by eyeberic** [comment]
> I am looking for an API, so if anyone has a good api, feel free to share

@aandrew-me - Does the candidate have to meet certain requirements? Was thinking about Claude or Pi.AI if we can hook into those?

**Comment by aandrew-me** [comment]
> > I am looking for an API, so if anyone has a good api, feel free to share
> 
> @aandrew-me - Does the candidate have to meet certain requirements? Was thinking about Claude or Pi.AI if we can hook into those?

Those 2 look good, I will check them. Just make sure the api should be free to use. I will check the rest

**Comment by eyeberic** [comment]
Aside from the above two mentioned (Claude and Pi.ai), I came across [Perplexity.ai](https://www.perplexity.ai/) which seems like a good candidate as well. 

[Huggingface.co](https://huggingface.co/chat/) might be possible though it seems like there is a free message limit without account, and have not encountered any limits using a free account.

**Comment by aandrew-me** [comment]
I checked Claude, it doesn't work in many countries, pi.ai uses different system of sending requests and Perplexity too was complex to implement the last time I checked. Huggingface is slow

**Comment by eyeberic** [comment]
Was about to mention Bing Chat as well, though I suspect it will be the same situation as Claude. 🙅🏾

**Comment by xplshn** [comment]
> > > But when I write 'please give me the answer in German,' then it will also be given in German. However, I don't want to have to specify that the answer should be given in German every time I make a request. That's why I asked if there's a way to specify the language for answers, for example, in the '~/.config/tgpt' directory.
> > 
> > 
> > There is no way. If you have to write each time, you can create an alias in your shell
> 
> I already had voice input and voice output set up through aliases, but I can't manage to get any more functionalities working.
> 
> ` alias bot='sed -i "s/duration=[0-9]+/duration=5/g" ~/.local/bin/stt.py; output=$(tgpt -w "$(python3 ~/.local/bin/stt.py </dev/null 2>/dev/null)"); echo "$output" >> output.txt; if grep -q "Some error has occurred" output.txt; then spd-say "Entschuldigung, ich habe Sie leider nicht verstanden."; else spd-say "$(cat output.txt)"; fi; rm -f output.txt'
> 
> alias bott='sed -i "s/duration=[0-9]+/duration=10/g" ~/.local/bin/stt.py; output=$(tgpt -w "$(python3 ~/.local/bin/stt.py </dev/null 2>/dev/null)"); echo "$output" >> output.txt; if grep -q "Some error has occurred" output.txt; then spd-say "Entschuldigung, ich habe Sie leider nicht verstanden."; fi'
> 
> alias botts='sed -i "s/duration=[0-9]+/duration=10/g" ~/.local/bin/stt.py; output=$(tgpt -w "$(python3 ~/.local/bin/stt.py </dev/null 2>/dev/null)"); echo "$output" >> output.txt; if grep -q "Some error has occurred" output.txt; then spd-say "Entschuldigung, ich habe Sie leider nicht verstanden."; rm -f output.txt; else spd-say "$(cat output.txt)"; fi'
> 
> alias botc='sed -i "s/duration=[0-9]+/duration=15/g" ~/.local/bin/stt.py; output=$(tgpt -c "$(python3 ~/.local/bin/stt.py </dev/null 2>/dev/null)"); echo "$output" >> output.txt; if grep -q "Some error has occurred" output.txt; then spd-say "Entschuldigung, ich habe Sie leider nicht verstanden."; rm -f output.txt; else sed -i "s/```//g" output.txt; spd-say "code wurde generiert."; fi'
> 
> alias botb='sed -i "s/duration=[0-9]+/duration=5/g" ~/.local/bin/stt.py; tgpt -img "$(python3 ~/.local/bin/stt.py 2>/dev/null)"; spd-say "Bilder wurden generiert."' `

I have made scripts in POSIX sh for the such in the past. One such that might be helpful is TTTS(uses Tiktok's API as TTS), its on my Handyscripts repo, no API keys, or configs needed, speaks all languages supported by the API. It might be useful for this, I've used it in the past in conjunction with tgpt -w, and whisper.cpp to make a little AI assistant
