### ISSUE TITLE
Some error has occurred. Statuscode: 401

### ISSUE THREAD

**Issue by viqplx7q** [aandrew-me/tgpt#171]
{"error":{"message":"Your OpenAI account has been deactivated, please check your email for more information. If you feel this is an error, contact us through our help center at help.openai.com.","type":"requests","param":"fk-zgvjbgxrZZudp1XFjScrlpr********************","code":null}}

**Comment by aandrew-me** [comment]
Sometimes errors may occur, you have to wait and try again
