### ISSUE TITLE
tgpt - Lack of context / context cross-contamination

### ISSUE THREAD

**Issue by eyeberic** [aandrew-me/tgpt#177]
Using tgpt version 2.2.3 on Linux AMD64, in multiline mode, the response provided seems to: 

1. Lack previous context even though the results are still as above (Apologies, there is no previous context provided. This is the first message you have sent. Is these anything else I can assist you with.)
2. Initial topic was about "Generative AI", and it suddenly responded back on the topic of "karma".

**Comment by aandrew-me** [comment]
Yes I switched to a new api, so there is no context, I have to reimplement this feature

**Comment by eyeberic** [comment]
Thank you for taking a look into this. 

WIll this regression be prioritized first prior to sourcing of new APIs in #170 since this feature will be backend-agnostic?

**Comment by aandrew-me** [comment]
It is not backend agnostic

**Comment by aandrew-me** [comment]
Models fakeopen and openai have context support

**Comment by sameedzahoor** [comment]
There needs to be a way to rejoin conversations in case of some error cropping up.

**Comment by aandrew-me** [comment]
> There needs to be a way to rejoin conversations in case of some error cropping up.

Next update
