### ISSUE TITLE
Clarify that tgpt use llama

### ISSUE THREAD

**Issue by ignassew** [aandrew-me/tgpt#178]
From looking at the code, tgpt is using [LLama 2 13b chat model](https://github.com/aandrew-me/tgpt/blob/992b576a02757c7f4807a7dde40971eb49990d7e/functions.go#L482).

The repository description says:
> ChatGPT in terminal without needing API keys 

Which is, in my opinion misleading.

**Comment by aandrew-me** [comment]
Forgot about changing that. It was always using got 3.5 until recently

**Comment by prathyk** [comment]
How does this exactly work? Who hosts the model? Where?

**Comment by aandrew-me** [comment]
Using freely available APIs. Currently Brave Leo is being used
