### ISSUE TITLE
Text Appears to be generated by LLaMA

### ISSUE THREAD

**Issue by chboishabba** [aandrew-me/tgpt#179]
With a name like tgpt, it seems maybe a little deceptive to name the project as if it were aligned with OpenAI's. There is no mention of the fact that LLaMA is used anywhere on the page.

**Comment by chboishabba** [comment]
Hi Andrew, seems you have updated the readme, thank you kindly. I did find it useful. Good luck working on the context.

**Comment by aandrew-me** [comment]
Yeah it was got 3.5 for a long time until recently. I couldn't find a good working got 3.5 api, so I had to switch to this one
