### ISSUE TITLE
Explain what Bai Chatbot is, chinese is something you want to see on ur PC, code, websites.

### ISSUE THREAD

**Issue by xplshn** [aandrew-me/tgpt#18]
That's it, what is Bai Chatbot, why, and how do you get their API? Does TGPT violate any terms of service? If so, how can you adapt this so it respects private property?

**Comment by aandrew-me** [comment]
Its an [an open source project](https://github.com/Chanzhaoyu/chatgpt-web)  that provides 2 unofficial apis for chatgpt. They have a website which you can use and its free of charge and doesn't require any login. They also provide a telegram bot. And the code here is open source, you can see how it comminicates with their api. So nothing is violated here.

**Comment by xplshn** [comment]
I asked about a violation of ChatGPTs TOS. Net about security, but thanks for the info,  I'll those projects out.

**Comment by aandrew-me** [comment]
This program doesn't communicate directly with Chatgpt, so chatgpt is not even in the equation here.

**Comment by aandrew-me** [comment]
There is no reverse engineering or anything like that going on

**Comment by xplshn** [comment]
Okay, then that it. Great thing to know :) . Also, will you release a Termux version? It needs to compile with the Android NDK in order to work. And for aarm64

**Comment by aandrew-me** [comment]
Yeah I had tried compiling for android but it failed. I will try again
