### ISSUE TITLE
Python clone of tgpt

### ISSUE THREAD

**Issue by Simatwa** [aandrew-me/tgpt#180]
This is **NOT** really an issue but an information to  pass across.

I recreated tgpt in Python, added some enhancements and named it [tgpt2](https://github.com/Simatwa/tgpt2).

It also features a ready to use commandline interface and a package to intergrate it in your own python code.

This repo served as a reference.

**Comment by sameedzahoor** [comment]
I think you should call it python-tgpt rather that tgpt2 which might be used for future versions of the code here.

**Comment by Simatwa** [comment]
Nice idea folk. It's now a done deal.
https://github.com/Simatwa/python-tgpt

**Comment by aandrew-me** [comment]
Well done, I don't think its necessary to call it 'a clone' of tgpt. Its your project, you coded it in a completely different language.

**Comment by aandrew-me** [comment]
Well done, I don't think its necessary to call it 'a clone' of tgpt. Its your project, you coded it in a completely different language.
