### ISSUE TITLE
Allow to set own x-brave-key

### ISSUE THREAD

**Issue by niutech** [aandrew-me/tgpt#181]
Now the Brave key is hardcoded in the source code, so it can be easily blocked by Brave. Please allow us to optionally provide our own `x-brave-key` as a command parameter.

**Comment by sameedzahoor** [comment]
Also, can we have temperature as a parameter too. It would be good to call something like 'tgpt --temp 0.1  Hello' .

**Comment by Simatwa** [comment]
All this is addressed in [python clone of tgpt](https://github.com/Simatwa/python-tgpt). Something like this is possible

`$ tgpt -t <Temperature> -bk <Brave-Key> "<Your prompt>"`

**Comment by niutech** [comment]
Tha't nice, but I'd prefer a tiny single static binary rather than a
whole Python environment.

**Comment by Simatwa** [comment]
That's quite easy. Submit as an issue over there and then we gonna work on that.

**Comment by aandrew-me** [comment]
The key used by brave for free tier is same for everyone

**Comment by niutech** [comment]
Yes, but if I buy a premium access, I can easily swap the key for a larger LLM.
