### ISSUE TITLE
Support Mixtral-8x7b when it's available

### ISSUE THREAD

**Issue by niutech** [aandrew-me/tgpt#182]
[Brave is working](https://github.com/brave/brave-core/pull/21398) on the new freemium AI model in Leo: `mixtral-8x7b-instruct`. Explore the possibility of adding a (limited) support of it with `tgpt` when it's generally available.

**Comment by Simatwa** [comment]
The model is yet to support API. But your concern is fully addressed by this [python clone of tgpt](https://github.com/Simatwa/python-tgpt) using `-m` flag e.g `tgpt "<Your prompt>" -m mixtral-8x7b-instruct`
