### ISSUE TITLE
Incomplete answers (only show the first word)

### ISSUE THREAD

**Issue by sinuso** [aandrew-me/tgpt#186]
The answers only show the first word.

```
:~$ tgpt -i
Interactive mode started. Press Ctrl + C or type exit to quit.

╭─ You
╰─> hi

╭─ Bot
Here

╭─ You
╰─> 1+1?

╭─ Bot
That

╭─ You
╰─> hello

╭─ Bot
Here

╭─ You
╰─> write the alphabet

╭─ Bot
I'm

╭─ You
╰─>

```

**Comment by aandrew-me** [comment]
Adding one header fixed it, looks like they are making backend changes

**Comment by sinuso** [comment]
> Adding one header fixed it, looks like they are making backend changes

Now it works perfect.

An observation/request. 
Can you add a line break at the end of the answers to avoid this? 

```
test@localhost:~$ tgpt -q "hi"

Hello! I'm here to help answer any questions you have. What's on your mind? 🤔test@localhost:~$
```

It should show like this:

```
test@localhost:~$ tgpt -q "hi"

Hello! I'm here to help answer any questions you have. What's on your mind? 🤔
test@localhost:~$
```

**Comment by aandrew-me** [comment]
Ah right, my terminal automatically added the line break, so I missed it. Will surely add
