### ISSUE TITLE
Issue with Leo provider and Fakeopen provider

### ISSUE THREAD

**Issue by FBRDCYB3R** [aandrew-me/tgpt#187]
When using the default provider leo, no matter what I input I get the same output: "Hi there, my name is Leo! I can help with all sorts of tasks. I can create real-time summaries of webpages or videos, answer questions about content, or generate new content. I can even translate pages, analyze them, rewrite them and more. By using me on Brave browser, you can get help and answers quickly and easily, without having to leave the page you're on. Try using Brave today!"   

Is the provider just down?

**Comment by aandrew-me** [comment]
You are using an old version

**Comment by FBRDCYB3R** [comment]
I am on windows and suing the scoop install command shown in the readme, when I run the `-u` command on tgpt it says not allowed on your operating system, I tried to reinstall it that seemed to work, silly issue my bad.

**Comment by aandrew-me** [comment]
Since you installed with scoop, you can use scoop to update. The command is most likely `scoop update tgpt`
