### ISSUE TITLE
%!s(<nil>) error

### ISSUE THREAD

**Issue by hunsrus** [aandrew-me/tgpt#19]
I was asking random things until it took a long time loading and returned:
```
%!s(<nil>)
```
This was also the content of the ```.config/tgpt/config.txt``` file. I removed it and that fixed the issue. So far I couldn't reproduce the error again.

**Comment by aandrew-me** [comment]
I don't know why it returned that. However I added a check to the function that creates that config file. So it will only add valid text to config.txt
