### ISSUE TITLE
too much Hallucinations while using tgpt

### ISSUE THREAD

**Issue by HakaishinShwet** [aandrew-me/tgpt#190]
thanks dev for this terminal gpt it is working but facing too much conversation breakups, i tried multi line mode and interactive one and faced this. i dont think it is your code fault but is there any way to improve it or any tips you might wanna give for this issue :-)

**Comment by aandrew-me** [comment]
> thanks dev for this terminal gpt it is working but facing too much conversation breakups, i tried multi line mode and interactive one and faced this. i dont think it is your code fault but is there any way to improve it or any tips you might wanna give for this issue :-)

Elaborate your issue

**Comment by HakaishinShwet** [comment]
@aandrew-me  
![20240108_12h30m14s_grim](https://github.com/aandrew-me/tgpt/assets/55040435/1f7488f1-8295-4658-ae23-d4d0ada68a61)
![20240108_12h25m23s_grim](https://github.com/aandrew-me/tgpt/assets/55040435/ad57003e-326f-470f-aaf2-60573e502c65)

**Comment by aandrew-me** [comment]
What version are you using

**Comment by aandrew-me** [comment]
You're using an older version, update the program

**Comment by HakaishinShwet** [comment]
you are right sir i was on 2.2.3-1 version and i did upgrade to latest and test it out right now and it did give me 3-4 times one complete result but in interactive mode when i tried to further conversate with it ,i was getting - error has occurred. Statuscode: 400 and i am attaching one sample of that error which i faced just now.
![20240108_12h52m22s_grim](https://github.com/aandrew-me/tgpt/assets/55040435/89a09d22-d4bc-4796-8a2a-28a09e62870c)

**Comment by aandrew-me** [comment]
Yes this provider sometimes gets errors, you can try other ones, like `opengpts`

**Comment by HakaishinShwet** [comment]
yea opengpts is working better but i am getting Some error has occurred. Statuscode: 422
{"detail":[{"type":"json_invalid","loc":["body",1440],"msg":"JSON decode error","input":{},"ctx":{"error":"Invalid control character at"}}]}    this error sometime and it is ending conversation with it

**Comment by aandrew-me** [comment]
What did you type when you got the error

**Comment by HakaishinShwet** [comment]
normal text only i tried 3 times and i am attaching the last one ss to so that you can see. it is breaking every time at second message from ai for me in my 3 trials with the mentioned error code while i am using opengpts
![20240109_09h40m39s_grim](https://github.com/aandrew-me/tgpt/assets/55040435/d5f503d4-851f-44d9-8335-f3afb4b8b750)

**Comment by HakaishinShwet** [comment]
@aandrew-me while using fakeopen i am getting these errors:
1. type 1  error - Some error has occurred. Statuscode: 401
{"error":{"message":"Your OpenAI account has been deactivated, please check your email for more information. If you feel this is an error, contact us through our help center at help.openai.com.","type":"requests","param":"fk-lMGEKjXz_KDLl3cjr04qNMr********************","code":null}}
2. type 2 error- Some error has occurred. Statuscode: 400
{"error":{"message":"invalid paramters","type":"invalid_request_error","param":null,"code":null}}

This is not your code fault still just wanted to tell about this and maybe if possible could find some more working apis or external methods later which could make this program much better for future :-) thanks for the hardwork
![20240109_09h47m46s_grim](https://github.com/aandrew-me/tgpt/assets/55040435/1d75c47d-3f76-4182-ab59-4dcb7bf124f6)
![20240109_09h47m00s_grim](https://github.com/aandrew-me/tgpt/assets/55040435/3ad6ad14-bcbe-42bf-b0f6-1b2d80523979)

**Comment by aandrew-me** [comment]
> normal text only i tried 3 times and i am attaching the last one ss to so that you can see. it is breaking every time at second message from ai for me in my 3 trials with the mentioned error code while i am using opengpts ![20240109_09h40m39s_grim](https://private-user-images.githubusercontent.com/55040435/295098430-d5f503d4-851f-44d9-8335-f3afb4b8b750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjgxMjAsIm5iZiI6MTcwNDgyNzgyMCwicGF0aCI6Ii81NTA0MDQzNS8yOTUwOTg0MzAtZDVmNTAzZDQtODUxZi00NGQ5LTgzMzUtZjNhZmI0YjhiNzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE5MTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZWJmNzVjMDhjMTI4YjJiMGJlODI1YjdhODA5MmJkMDI1NzZlMGQ1ZTYyMjlhNjI3ZWVhYmVkNDZlNjY2MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Ud-eGBaLj_8BrSydOFc6MVmzp4-GkgqVnN5CZQdz74)

Ok I identified the problem, will be fixed

**Comment by aandrew-me** [comment]
> @aandrew-me while using fakeopen i am getting these errors:
> 
> 1. type 1  error - Some error has occurred. Statuscode: 401
>    {"error":{"message":"Your OpenAI account has been deactivated, please check your email for more information. If you feel this is an error, contact us through our help center at help.openai.com.","type":"requests","param":"fk-lMGEKjXz_KDLl3cjr04qNMr********************","code":null}}
> 2. type 2 error- Some error has occurred. Statuscode: 400
>    {"error":{"message":"invalid paramters","type":"invalid_request_error","param":null,"code":null}}
> 
> This is not your code fault still just wanted to tell about this and maybe if possible could find some more working apis or external methods later which could make this program much better for future :-) thanks for the hardwork ![20240109_09h47m46s_grim](https://private-user-images.githubusercontent.com/55040435/295099852-1d75c47d-3f76-4182-ab59-4dcb7bf124f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjgxMjAsIm5iZiI6MTcwNDgyNzgyMCwicGF0aCI6Ii81NTA0MDQzNS8yOTUwOTk4NTItMWQ3NWM0N2QtM2Y3Ni00MTgyLWFiNTktNGRjYjdiZjEyNGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE5MTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjg2NzAyNjJjOWYyYjUzZTFlMTdmODQzM2ZhMjk1NDBlZTM1ZWNjMWI2NWQ2MDY1YTFhYTczNzAxMWY0OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BzCPUuTr0N8wBifCTDzxqqbaJh8bjp0GtaOYlL9_L4k) ![20240109_09h47m00s_grim](https://private-user-images.githubusercontent.com/55040435/295099865-3ad6ad14-bcbe-42bf-b0f6-1b2d80523979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjgxMjAsIm5iZiI6MTcwNDgyNzgyMCwicGF0aCI6Ii81NTA0MDQzNS8yOTUwOTk4NjUtM2FkNmFkMTQtYmNiZS00MmJmLWIwZjYtMWIyZDgwNTIzOTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE5MTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZGYzYzU0YzcyYTJkN2JiYzk1NDA2NGMyNjg3OWFkZDc2NTNmYjk2NGI2ZGQwNTdkZmY0Zjg3OWFjNGU3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sqKOiDY7gSPm3B6lqob0TWg0d5XQB0dv-ZXdr0AQekk)

There are 2 other apis available to use. I keep adding more when I find/can

**Comment by HakaishinShwet** [comment]
@aandrew-me i have updated to new version so sometimes i able to do continuous conversation but still i am facing one new issue for which i create new issue and closing this one.so do check my new issue sir :-)
