### ISSUE TITLE
2.4.2 update issue - getting html code error in between conversations while using opengpts

### ISSUE THREAD

**Issue by HakaishinShwet** [aandrew-me/tgpt#191]
This the error i am getting in between conversations which is breaking chat in between.

ERROR -

Some error has occurred. Statuscode: 403
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/runs/stream</code> from this server.  <ins>That’s all we know.</ins>

I am attaching one sample conversation with two images in which there is normal conversation and above mentioned error, Hope it helps you to fix this error.

![20240110_08h42m21s_grim](https://github.com/aandrew-me/tgpt/assets/55040435/76007464-5cd8-499c-9f68-c7e5abc51ae4)
![20240110_08h42m17s_grim](https://github.com/aandrew-me/tgpt/assets/55040435/de0a1d56-0ef6-453b-9920-926156cb3ba2)

**Comment by aandrew-me** [comment]
I couldn't reproduce the error

**Comment by HakaishinShwet** [comment]
@aandrew-me now i get it why i was facing that issue. my system was tunnel with proxy so because of that i was getting that issue, without proxy server tunneling over system it was working fine.plus i tested with wireguard vpn too and didnt faced issue with that just sometime connection gets dropped thats all. So i am closing this issue from my side :-)
