### ISSUE TITLE
After update not working more..

### ISSUE THREAD

**Issue by grugnoymeme** [aandrew-me/tgpt#193]
Hi, after the last update i always get this problem:

╭─meme@quarantasette 🪫54% at 09:20:32 in ~ took 25ms 
╰─λ tgpt "What is internet?"                                             
Some error has occurred. Statuscode: 401 {"error":{"message":"Unauthorized - Access token is missing","type":"requests","param":null,"code":null}}

how to fix this?

**Comment by aandrew-me** [comment]
Not related to update, the api is having problems, use a different provider

**Comment by grugnoymeme** [comment]
for example which one?

**Comment by grugnoymeme** [comment]
fakeopen?

**Comment by som3bd** [comment]
There are other providers, see the help menu - https://github.com/aandrew-me/tgpt?tab=readme-ov-file#usage-

**Comment by grugnoymeme** [comment]
thank u!!
