### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by sameedzahoor** [aandrew-me/tgpt#195]
I wrote a tiny user interface using fzf for tgpt (I used python-tgpt just because it supports conversation, but with minor edits it can be used for tgpt too). It supports reading chats, conversation management, autosuggestions and has an improved shell mode. Try it out and give your feedback.
https://github.com/sameedzahoor/szl

**Comment by sameedzahoor** [comment]
You can try replicating what python-tgpt has done. You will be able to support conversations (albeit very basic) with leo and other models. You can try out conversations with leo on szl and try to implement the same.

**Comment by sinuso** [comment]
Interesting to be able to use the 41+ gpt4free models with python-tgpt.

I like

**Comment by aandrew-me** [comment]
> Interesting to be able to use the 41+ gpt4free models with python-tgpt.
> 
> I like

Last time I tried most of them didn't work. Identify which ones work and I can add them

**Comment by sameedzahoor** [comment]
I have focused on local chat storage in szl, so I have chosen only fakeopen, leo and opengpt. You could in theory use the same interface for other chats by slightly modifying the script. 
The gpt4free on the other hand needs chrome installed (if I remember correctly) and uses cookies.

**Comment by sinuso** [comment]
> > Interesting to be able to use the 41+ gpt4free models with python-tgpt.
> > I like
> 
> Last time I tried most of them didn't work. Identify which ones work and I can add them

With this script you can check which ones work.
https://github.com/ayoub-fork/g4f-check

This has been my result.

```
====== WORKING PROVIDERS ======
FakeGpt              3.20s
DeepInfra            5.57s
ChatgptAi            9.32s
Liaobots             2.89s
Koala                3.77s
GeekGpt              5.38s
ChatBase             15.68s
You                  2.89s
VoiGpt               20.12s
Pi                   51.84s
PerplexityAi         67.82s
GptChatly            87.70s
MyShell              118.89s
====== FASTEST PROVIDER ======
Liaobots             2.89s
====== 13/82 WORKING ======
```

And this is the result from a Linux terminal without Chrome.

```
====== WORKING PROVIDERS ======
MyShell              0.73s
FakeGpt              2.36s
GeekGpt              2.78s
Koala                2.91s
You                  3.22s
ChatgptX             6.26s
Liaobots             43.57s
====== FASTEST PROVIDER ======
MyShell              0.73s
====== 7/68 WORKING ======
```

**Comment by Simatwa** [comment]
> > > Interesting to be able to use the 41+ gpt4free models with python-tgpt.
> > > I like
> > 
> > 
> > Last time I tried most of them didn't work. Identify which ones work and I can add them
> 
> With this script you can check which ones work. https://github.com/ayoub-fork/g4f-check
> 
> This is my result in Windows with Chrome and cookies:
> 
> ```
> ====== WORKING PROVIDERS ======
> FakeGpt              3.20s
> DeepInfra            5.57s
> ChatgptAi            9.32s
> Liaobots             2.89s
> Koala                3.77s
> GeekGpt              5.38s
> ChatBase             15.68s
> You                  2.89s
> VoiGpt               20.12s
> Pi                   51.84s
> PerplexityAi         67.82s
> GptChatly            87.70s
> MyShell              118.89s
> ====== FASTEST PROVIDER ======
> Liaobots             2.89s
> ====== 13/82 WORKING ======
> ```
> 
> And this is the result from a Linux terminal without Chrome and cookies:
> 
> ```
> ====== WORKING PROVIDERS ======
> MyShell              0.73s
> FakeGpt              2.36s
> GeekGpt              2.78s
> Koala                2.91s
> You                  3.22s
> ChatgptX             6.26s
> Liaobots             43.57s
> ====== FASTEST PROVIDER ======
> MyShell              0.73s
> ====== 7/68 WORKING ======
> ```

Another hassle-free workaround here :

`$ pytgpt gpt4free update && pytgpt gpt4free list providers --working --json `

<details>
<summary>
Output :
</summary>

```json
{
    "providers": [
        "Bard",
        "Aura",
        "ChatForAi",
        "GptChatly",
        "AiChatOnline",
        "GptForLove",
        "Liaobots",
        "Poe",
        "Pi",
        "DeepInfra",
        "ChatgptNext",
        "FakeGpt",
        "FreeChatgpt",
        "GptTalkRu",
        "ThebApi",
        "Chatxyz",
        "Yqcloud",
        "OpenaiChat",
        "ChatgptDemo",
        "Theb",
        "Raycast",
        "GeekGpt",
        "TalkAi",
        "Chatgpt4Online",
        "ChatgptAi",
        "ChatBase",
        "AItianhuSpace",
        "GptGo",
        "Hashnode",
        "You",
        "HuggingChat",
        "Koala",
        "Gpt6",
        "MyShell",
        "Phind",
        "Bing",
        "OnlineGpt",
        "GPTalk",
        "Llama2",
        "GeminiProChat",
        "PerplexityAi"
    ]
}
```

</details>

**Comment by aandrew-me** [comment]
@Simatwa Thanks for the info, really appreciate that

**Comment by sameedzahoor** [comment]
Have added eleven providers that worked on my system to the szl script.

**Comment by johnd0e** [comment]
[szl.zip](https://github.com/user-attachments/files/25271451/szl.zip)
