### ISSUE TITLE
🚀 PYTHON-TGPT Has Just Got Better

### ISSUE THREAD

**Issue by Simatwa** [aandrew-me/tgpt#197]
> **Disclaimer:** This is **NOT** an issue but information to pass across.

🌟 Greetings, folks! The [PYTHON-TGPT](https://github.com/Simatwa/python-tgpt) project has made some incredible updates, and I'm thrilled to share them with you!

🤖 **Over 60 Functional Providers** are now available, thanks to the amazing [gpt4free](https://github.com/xtekky/gpt4free) project. These providers are backed by top-notch models like **Palm, text-davinci-003, gpt-3.5-turbo-16k, gpt-4-0613, llama13b-v2-chat, claude-v1 & v2, gpt-neox-20b, santacoder, command-nightly** and more!

🔑 **Over 80% of these providers** don't require an API key or cookies, just installation, and you're good to go! Plus, you can enjoy the state-of-the-art [awesome-chatgpt-prompts](https://github.com/f/awesome-chatgpt-prompts) and other [curated prompts](https://github.com/Simatwa/gpt-cli/blob/main/assets/all-acts.json) like **DAN, AIM, EvilBot, NeoGPT, AmoralAI, BetterDAN, FunnyGPT** and more!

Don't forget to give it a ⭐️.

> Credits : [tgpt](https://github.com/aandrew-me/tgpt)

**Comment by aandrew-me** [comment]
Great job! Well its your project and way different than mine, so I don't think you need to credit tgpt
