### ISSUE TITLE
[FEATURE REQUEST] Use charmbracelet/glow to display the markdown output on the terminal

### ISSUE THREAD

**Issue by aryan-212** [aandrew-me/tgpt#198]
So basically, A line where "echo "the_chatgpt_output" | glow -" is executed internally would be great!

**Comment by aandrew-me** [comment]
Firstly I don't see any library provided, secondly tgpt prints streamed texts, and I can't parse markdown in realtime in the terminal. However `glow` is a great tool and you can utilize it. You can use -q or -w with it and it works well. You just won't get streamed texts
<img width="756" alt="image" src="https://github.com/aandrew-me/tgpt/assets/66430340/518505c7-78d1-47d0-b342-5d0bfd717fd8">

**Comment by aandrew-me** [comment]
And you can use some alias. For example for `fish` shell you can setup a function
```
function getMd
    tgpt -w $argv | glow -
end
```

And then use it

<img width="523" alt="image" src="https://github.com/aandrew-me/tgpt/assets/66430340/d17a4706-3f79-468c-a482-a071b6dd0a26">

**Comment by muniss950** [comment]
What if i want this output but for the multiline interactive mode? What alias should I make
