### ISSUE TITLE
Fakeopen is shutting down after 30.01

### ISSUE THREAD

**Issue by johnd0e** [aandrew-me/tgpt#199]
Ref: https://linux.do/t/topic/1051

**Comment by sameedzahoor** [comment]
Leo seems to not be working today. Why was leo removed from providers? I quite liked it.

**Comment by aandrew-me** [comment]
> Leo seems to not be working today. Why was leo removed from providers? I quite liked it.

I quote Brave -
> We are hoping you would remove Leo as an available API provider on your project since it is not intended for use by third parties such as yourself and costs us to support the load from your project.

**Comment by sameedzahoor** [comment]
Well, that seems fair. Do we really have so many users?

**Comment by aandrew-me** [comment]
> Well, that seems fair. Do we really have so many users?

Enough to make an impact
