### ISSUE TITLE
[enhancement] Self Update

### ISSUE THREAD

**Issue by Bellisario** [aandrew-me/tgpt#20]
Would be great to update tgpt directly from its interface instead of manually installing each time the new release.

An example command for this:

```bash
tgpt --update
# or
tgpt -U
```

**Comment by aandrew-me** [comment]
This is already available. Just not on Windows

**Comment by Bellisario** [comment]
I don't find any flag for this here:

```
Usage: tgpt "Explain quantum computing in simple terms"
Options:
-f, --forget                                       Forget chat history
-v, --version                                      Print version
-h, --help                                         Print help message

Example:
tgpt -f
```

Do I need to run the [original installer](https://github.com/aandrew-me/tgpt#download-for-linux-or-mac-with-this-one-line)?

**Comment by aandrew-me** [comment]
Inbuilt updater was added just yesterday

**Comment by Bellisario** [comment]
Just done:

```
Usage: tgpt "Explain quantum computing in simple terms"
Options:
-f, --forget                                       Forget chat history
-v, --version                                      Print version
-h, --help                                         Print help message
-i, --interactive                                  Start interactive mode
-u, --update                                       Update program

Example:
tgpt -f
```

Now the update command is shown!

Thanks for the quick answers, I'll close the issue...

**Comment by aandrew-me** [comment]
Wish you a great day/night!

**Comment by omaru-ok** [comment]
@aandrew-me  why not [scoop](https://scoop.sh/) pacakge still ?

**Comment by aandrew-me** [comment]
> @aandrew-me why not [scoop](https://scoop.sh/) pacakge still ?

Already added. Check Readme
