### ISSUE TITLE
Create commit message

### ISSUE THREAD

**Issue by sahashirshendu** [aandrew-me/tgpt#200]
Is it possiible to generate a git commit message by piping the diff? The following gives nothing
```bash
$ git diff | tgpt "given the above, Generate git commit message, for my changes" -w

given the above, Generate git commit message, for my changes

Sure, I can help with that. What changes did you make that you would like to include in the git commit message?
```

**Comment by aandrew-me** [comment]
Hmm right now it only checks stdinput if there is no prompt. I will add the feature

**Comment by Gogotron** [comment]
I like to use the following little hack:
```sh
$ git diff | tgpt -w "$(cat -) given the above, Generate git commit message, for my changes"
```
Or if you want some newlines:
```sh
$ git diff | tgpt -w "$(printf "$(cat -)\n\ngiven the above, Generate git commit message, for my changes")"
```
Also, you should not that options such as `-w` only work if they're before the prompt.

**Comment by aandrew-me** [comment]
The feature will be available in next update. The prompt should be after all the flags, so that command will look like
`git diff | tgpt -w "given the above, Generate git commit message, for my changes" `
