### ISSUE TITLE
Web server is down?

### ISSUE THREAD

**Issue by ghobadkhan** [aandrew-me/tgpt#204]
```tgpt``` command is not working anymore!

First, it shows a _loading_ message for 20s and then apparently times out with 522 code.

What's wrong?
![Screenshot from 2024-01-30 20-30-39](https://github.com/aandrew-me/tgpt/assets/19890208/79f590f8-eb1a-4350-b020-16fd321c6fe3)
![Screenshot from 2024-01-30 20-30-56](https://github.com/aandrew-me/tgpt/assets/19890208/c8f84648-ee8e-420e-a97a-a4c0fb20c89b)

**Comment by privet2pizza** [comment]
I had the same issue when I installed it with command

> yay -S tgpt

So, I found 2 solution:

1. Update it with `tgpt -u`;
2. install **tgpt-bin**, not **tgpt**

**Comment by aandrew-me** [comment]
There actually has been an issue #203 
And I don't maintain `tgpt` in AUR, only `tgpt-bin`
