### ISSUE TITLE
Not Remembering Conversation Context Since Last Update

### ISSUE THREAD

**Issue by protwan** [aandrew-me/tgpt#206]
I've noticed that tgpt is not remembering the context of the conversation. This means that I can't follow up on previous questions and responses, which is a key feature that I rely on. I haven't been updating regularly, so I'm not exactly sure since which version this behavior started.

**Comment by protwan** [comment]
It seems to work now in interactive mode, but not in multiline mode.

**Comment by aandrew-me** [comment]
> It seems to work now in interactive mode, but not in multiline mode.

My bad, missed it, will be in next update
