### ISSUE TITLE
Error: bufio.Scanner: token too long

### ISSUE THREAD

**Issue by giovannilupi** [aandrew-me/tgpt#207]
Hello, 

I'm encountering the  following error when using the default provider (opengpts):
`Some error has occurred. Error: bufio.Scanner: token too long`

Other providers seem to work correctly.

![Screenshot 2024-02-03 at 23 33 07](https://github.com/aandrew-me/tgpt/assets/37253784/0d6d0397-a7dd-4270-9d31-ccf357cfd387)

**Comment by aandrew-me** [comment]
Yes I found the problem, fix incoming, use other provider for now
