### ISSUE TITLE
[Issue] Invalid provider: 'koboldai'

### ISSUE THREAD

**Issue by NextStep-IM** [aandrew-me/tgpt#209]
### Issue
- `tgpt --provider koboldai _"query"_' returns an error: `Invalid provider`.
- Other providers work.

### Extra info
- Using the AUR package `tgpt-bin` on Arco Linux.

**Comment by aandrew-me** [comment]
I made a typo, thanks for mentioning

**Comment by NextStep-IM** [comment]
Fixed. Thanks a lot, @aandrew-me!
