### ISSUE TITLE
introduce word - wrapping

### ISSUE THREAD

**Issue by omaru-ok** [aandrew-me/tgpt#21]
![image](https://github.com/aandrew-me/tgpt/assets/108952834/d4eb2391-121f-44a9-a237-526dfb59641f)
see inner words like `additionally ` are breaked up 

### please introduce  ->
- word wrapping ,  based on terminal size
- line break , 
- very colofull output  , being plain text is very plain

**Comment by aandrew-me** [comment]
I cannor introduce word wrapping because characters are printed character by character. 

And what do you mean by very 'colofull' output? Colorful text is being printed in many cases, except dor normal text

**Comment by aandrew-me** [comment]
OK Word wrapping issue has been addressed and fixed. So it should be fine from next update

**Comment by omaru-ok** [comment]
https://github.com/aandrew-me/tgpt/commit/b8bdb37b583aa9c81be932fb8b2dc0c2c8a87bb0
im waiting for next release

**Comment by omaru-ok** [comment]
![image](https://github.com/aandrew-me/tgpt/assets/108952834/5db6c695-608f-46a5-a15e-85f7d904f6e8)
reopen the issue, 
![image](https://github.com/aandrew-me/tgpt/assets/108952834/77919dd7-8a98-473b-9cff-f5033328177d)

terminal = window terminal , alacrity 
os = window 11

**Comment by aandrew-me** [comment]
Hmm, I changed some code, wait for next update

**Comment by omaru-ok** [comment]
# wrap break's randomly on `-i` intractive mode 
@aandrew-me 
![image](https://github.com/aandrew-me/tgpt/assets/108952834/b6829d19-554b-4d56-a809-e6e163b9c2fa)

**Comment by NormTurtle** [comment]
![image](https://github.com/aandrew-me/tgpt/assets/108952834/bda57e6e-9f15-4e80-abf6-f59f21ece2cb)
some werid Wrapping issue AGAIN ,
 making it hard to read 
why there is unneeded  LINE-break for just one CHARACTER? `an`

**Comment by aandrew-me** [comment]
Year

> ![image](https://user-images.githubusercontent.com/108952834/240998939-bda57e6e-9f15-4e80-abf6-f59f21ece2cb.png) some werid Wrapping issue AGAIN , making it hard to read why there is unneeded LINE-break for just one CHARACTER? `an`

Yeah I realized why its happening. It will be fine in next update

**Comment by NormTurtle** [comment]
@aandrew-me just interest is there any other ELSE like free-GPT AI projects like this one?
not for devloping for consumer

**Comment by aandrew-me** [comment]
> @aandrew-me just interest is there any other ELSE like free-GPT AI projects like this one? not for devloping for consumer

Yeah
https://you.com/
https://www.phind.com/
Bing chat, Bard AI

**Comment by NormTurtle** [comment]
i use all them already
