### ISSUE TITLE
The generated images are not perfect enough and the resolution is so poor. 

### ISSUE THREAD

**Issue by mahfuzswaron** [aandrew-me/tgpt#211]

**Comment by aandrew-me** [comment]
I agree, but what can I do?

**Comment by mahfuzswaron** [comment]
Actually I am making content about tgpt. that's why thought to inform you about the issue. that's it. If you have something to make it better, I'll suggest to do.

**Comment by aandrew-me** [comment]
Oh I see. Well I am just using the API of [Craiyon](https://www.craiyon.com/)
So I can't do anything about it, only if there is a better api, I can add it

**Comment by mahfuzswaron** [comment]
Got it.
