### ISSUE TITLE
possible feature request lists

### ISSUE THREAD

**Issue by DarkReaperBoy** [aandrew-me/tgpt#212]
1) add support for custom openai api, like
https://github.com/TheR1D/shell_gpt?tab=readme-ov-file#localai
for example, when used for local/hosted models that use custom openai server

2) add support for system prompt/roles
to make it behave in certain way.

**Comment by aandrew-me** [comment]
Preprompts will be available in next update

And I will look into the first point

**Comment by aandrew-me** [comment]
Support for Ollama will be available in next update

**Comment by guillermodelrio** [comment]
can we add glow support? would be neat to output markdown

**Comment by johnd0e** [comment]
@guillermodelrio 
What kind of support do you mean?

Normally this should be enough:
```
tgpt ... | glow
```
