### ISSUE TITLE
go install does not make tgpt accessible

### ISSUE THREAD

**Issue by alamar** [aandrew-me/tgpt#215]
```
% go install github.com/aandrew-me/tgpt/v2@latest
... stuff happens ...
% tgpt
zsh: command not found: tgpt
% cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.10
DISTRIB_CODENAME=mantic
DISTRIB_DESCRIPTION="Ubuntu 23.10"
```

Yup.

I don't believe README should assume that user understands how `go install` works, how it can be configured and what happens afterwards. I have `go` installed but have no clue.

**Comment by som3bd** [comment]
`~/go/bin` needs to be in PATH

**Comment by alamar** [comment]
Can you please put that to `README`? Thanks.

**Comment by aandrew-me** [comment]
Sure. go install is used by people who work with go. So for them its common knowledge, that's why I didn't put it
