### ISSUE TITLE
Phind Provider doesn't provide a speed resoponse   - 504 error code

### ISSUE THREAD

**Issue by EslamElkhair** [aandrew-me/tgpt#216]
Some error has occurred. Statuscode: 504 error code: 504

![Screenshot from 2024-02-14 18-30-16](https://github.com/aandrew-me/tgpt/assets/63516927/a53e84a8-86ec-4920-b0e6-2d94e10f4e01)

**Comment by som3bd** [comment]
Checked their site, its having problems too
