### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by trace1729** [aandrew-me/tgpt#218]
add support for google gemini, since gemini api is free.

**Comment by aandrew-me** [comment]
Well it still requires project id and api key, and apparently isn't supported in my country. But I will add if I can

**Comment by mountaineerbr** [comment]
While Gemini support is not implemented here, you may want to check out my [shell warper](https://github.com/mountaineerbr/shellChatGPT) which has just got support for Gemini. Cheers!

> add support for google gemini, since gemini api is free.

**Comment by johnd0e** [comment]
https://github.com/PublicAffairs/openai-gemini
