### ISSUE TITLE
Option for giving only code

### ISSUE THREAD

**Issue by jyash8** [aandrew-me/tgpt#22]
Please add an option to extract only code from result.
Could please also syntax highlighting with bat or some other tool?

**Comment by aandrew-me** [comment]
I can add an option to output only code. Then you can pipe it to bat and or whatever you want

**Comment by jyash8** [comment]
Just add a line with name of language that code is in earlier like it was as bat requires the name of programming language to enable syntax highlighting

**Comment by aandrew-me** [comment]
Bat doesn't handle languages that way, you know what language that is, so just specify it with `-l` in bat.

So it will be something like
```
tgpt --code "Write hello world program in python" | bat -l py
```

**Comment by jyash8** [comment]
I want it to autodetect.

**Comment by aandrew-me** [comment]
I don't think bat has autodetect support. If you want, tell its developers, not me.

**Comment by SAXN-SYNX** [comment]
if we can copy just the code ?
simple copy button in every generated code might help if it is implemented, i guess we can implement using tview ?

**Comment by aandrew-me** [comment]
Well as it is on a website to make a button, in cli the program constantly needs to be running to make that  button functional

**Comment by SAXN-SYNX** [comment]
so for interactive mode only , it is possible ?

**Comment by aandrew-me** [comment]
Interactive mode doesn't just print code. Lots of work needs to be done which I think is just too much for this. If you need all these, the website is already there and it does a much better job. 

So, no
