### ISSUE TITLE
Apperantly doesn't reply with anything

### ISSUE THREAD

**Issue by 0xQueen** [aandrew-me/tgpt#223]
Is there a limit? It worked before, now it doesnt reply with anything, other models work, 
![image](https://github.com/aandrew-me/tgpt/assets/156551265/c2ad7228-c411-4d71-8488-be399f5b0207)

**Comment by FBRDCYB3R** [comment]
getting same error here, updated to 2.7.0 on windows via scoop

**Comment by 0axmx-cx** [comment]
There might just be an issue with the opengpts provider, try your prompts with other providers for the time being if you can;
For example:
```
tgpt --provider llama2 "Hello World"
tgpt --provider phind "Hello World"
tgpt --provider koboldai "Hello World"
```

**Comment by shello101** [comment]
Hi, other providers are up, the one that is down is opengpts provider.

**Comment by maxonlinux** [comment]
Opengpts server responds with status 500. That's why.

**Comment by aryan-212** [comment]
Is there any way to make the other providers a default???

**Comment by aandrew-me** [comment]
Yeah looks like the provider is having problems, use other providers

**Comment by gamma19** [comment]
how can I change default provider to phind? so I can still use "tgpt -i" ?

**Comment by maxonlinux** [comment]
It's fixed.

**Comment by poslat-pismo** [comment]
> > Yeah looks like the provider is having problems, use other providers
> 
> I think this issue can be closed. Please create a new assistant and update the assistant id it the source code to make it work again because all the assistants were removed from their servers.

Please help me, I know this is not right place, but how can i get the "assistant_id"?
