### ISSUE TITLE
Assistant not found

### ISSUE THREAD

**Issue by juren53** [aandrew-me/tgpt#226]
$ tgpt -s "How to update my system?"
Some error has occurred. Statuscode: 404
{"detail":"Assistant not found"}
$ tgpt -v
tgpt 2.7.0
$

**Comment by tatore02** [comment]
same for me

**Comment by mgomezbuceta** [comment]
For me too

**Comment by aandrew-me** [comment]
I will fix it in next update, use different providers for now

**Comment by juren53** [comment]
Thanks, Andrew.  Will do.
