### ISSUE TITLE
add pollinations for image generation

### ISSUE THREAD

**Issue by nazdridoy** [aandrew-me/tgpt#227]
https://pollinations.ai

image generation endpoint "https://image.pollinations.ai/prompt/" prompt

its seems better than craiyon.com, Plese look into this.

thank you for this awesome tool

**Comment by sinuso** [comment]
It's already suggested [here ](https://github.com/aandrew-me/tgpt/issues/188#issuecomment-1948683244)

**Comment by nazdridoy** [comment]
oh, great! Then i'll close this issue and follow that one. thanks
