### ISSUE TITLE
Provider "Opengpts" doesn't work in v2.7.1

### ISSUE THREAD

**Issue by caliarch** [aandrew-me/tgpt#229]
The command ` tgpt --provider opengpts "prompt"` with any sort of prompt outputs:
```
Some error has occurred. Statuscode: 404

 <html><head>
 <meta http-equiv="content-type" content="text/html;charset=utf-8">
 <title>404 Page not found</title>
 </head>
<body text=#000000 bgcolor=#ffffff>
 <h1>Error: Page not found</h1>
<h2>The requested URL was not found on this server.</h2>
 <h2></h2>
 </body></html>

**Comment by aandrew-me** [comment]
Yes the provider has stopped working, I will wait for a couple of days, and if it doesn't change, I will remove it

**Comment by caliarch** [comment]
I see, thank you. Should I close the issue or leave it open?

**Comment by aandrew-me** [comment]
Keep it open

**Comment by sinuso** [comment]
> Yes the provider has stopped working, I will wait for a couple of days, and if it doesn't change, I will remove it

I doubt it will work again, the demo example API was receiving too many requests.
It's a shame, I think she was the fastest of all.
