### ISSUE TITLE
Error: Post "https://https.extension.phind.com/agent/": EOF

### ISSUE THREAD

**Issue by EnriColombo** [aandrew-me/tgpt#233]
How to replicate the issue:
```sh
~# tgpt "What is Alpine Linux?"
Some error has occurred. Check your internet connection.

Error: Post "https://https.extension.phind.com/agent/": EOF
```
The internet connection works fine.
My system specs are:
```sh
~# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.3
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
Go lang version:
```sh
~# go version
go version go1.16.15 linux/386
```
tgpt version:
```sh
~# tgpt -v
tgpt 2.7.1
```
Any help would be appreciated, tks!

**Comment by aandrew-me** [comment]
Interesting. Can you access phind.com?

**Comment by EnriColombo** [comment]
Actually I get a 403 forbidden status code.
```sh
~# curl -Is https://https.extension.phind.com/agent/ | head -1
HTTP/2 403
```

**Comment by aandrew-me** [comment]
Its normal, check if you can access https://www.phind.com

**Comment by aandrew-me** [comment]
Just try opening in browser

**Comment by EnriColombo** [comment]
It opens in browser

**Comment by aandrew-me** [comment]
Strange, I don't even know. The error message isn't clear either. If you can somehow proxy the request to something like MITMProxy, that could help me understand better

**Comment by agvxov** [comment]
Not sure if this helps anything, but I can confirm tgpt works normally under my Alpine v3.18.

**Comment by aandrew-me** [comment]
> Not sure if this helps anything, but I can confirm tgpt works normally under my Alpine v3.18.

Thanks for letting us know. I think that indicates to it being a network related problem
