### ISSUE TITLE
Return answer in stdout

### ISSUE THREAD

**Issue by tfuchs1987** [aandrew-me/tgpt#234]
Hi,

in former versions I could further process the answer provided by tgpt. Is it possible to have an attribute similar to -q (quiet) to send the return value to stdout? Currently I would need to save the output to a file and read it again.

Thanks in advance!

**Comment by aandrew-me** [comment]
-q still works, what's the problem?

**Comment by tfuchs1987** [comment]
yes -q was working in former versions for me but I use node-red to communicate with tgpt, which is listening for an stdout and is not recieving any information anymore. 

Just a suggestion - I have a workaround with saving the return value to a file to read it.
Thanks for all your effort on this project anyway!

**Comment by aandrew-me** [comment]
Interestingly strange, there hasn't been any change in output, it always printed to standard output. Only the errors are now printed to standard error. Also I never used node-red, so I don't know how to check.
