### ISSUE TITLE
Groq is recently released and is currently providing public chat access and api access for free but there is signup step so is there any possibility for its integration?

### ISSUE THREAD

**Issue by HakaishinShwet** [aandrew-me/tgpt#235]
They have signup process in which we have to either provide any email or with google. With temp mail we can create and verify and get free access to api and cloud console chat/playground and to there public chat too so just wanted to let you know this and wanted to ask if there is any possibility to use that in this project :-))
https://groq.com/ this is url for groq

**Comment by aandrew-me** [comment]
Well its similar to openai so surely I can add. Users can use their own api keys

**Comment by aandrew-me** [comment]
Will be available in next update

**Comment by HakaishinShwet** [comment]
@aandrew-me thanks plus without api key too is there any possibility like they public chat option too without console but for that we have to login tho so was just curious about this :-)).

**Comment by aandrew-me** [comment]
It requires to use cookie and some additional headers

**Comment by HakaishinShwet** [comment]
was thinking same just wanted to confirm :-)
