### ISSUE TITLE
Request for adding Google Gemini(formerly known as Bard)

### ISSUE THREAD

**Issue by golam71** [aandrew-me/tgpt#236]
So you get api key from [here](https://aistudio.google.com/app/apikey)

here is a small bash code i have written but i dont know C

```
#!/bin/bash

# Check if an argument is provided
if [ -z "$1" ]; then
	echo "Usage: $0 <prompt>"
	exit 1
fi

# URL encode the prompt
prompt=$(echo -n "$1" | jq -s -R -r @uri)

# Make the API request with the provided prompt
curl -sS -H 'Content-Type: application/json' \
	-d "{\"contents\":[{\"parts\":[{\"text\":\"$prompt\"}]}]}" \
	-X POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=API_KEY_GOES_HERE |
	jq -r '.candidates[0].content.parts[0].text' | sed 's/\\n/\n/g'
```

It does not support C but the documentation is [here](https://ai.google.dev/tutorials) and I would have liked to help sadly I am only a frontend dev .

Regards,
Golam Moula

**Comment by johnd0e** [comment]
https://github.com/PublicAffairs/openai-gemini

**Comment by sinuso** [comment]
I think cookies or both options, cookies or api key, would be better.
There are too many countries, such as Spain, that cannot obtain an API key.

Only these areas can have access https://ai.google.dev/available_regions#available_regions

**Comment by johnd0e** [comment]
@sinuso
You can avoid geo restrictions using openai-gemini project.

**Comment by xpufx** [comment]
> @sinuso You can avoid geo restrictions using openai-gemini project.

As far as I can tell this is not only for escaping geo restrictions but also an openAI compatible API proxy. Where would the proxy URL (in place of openai base url) and gemini API key go in tgpt though?

**Comment by johnd0e** [comment]
@xpufx 
> Where would the proxy URL (in place of openai base url) and gemini API key go in tgpt though?

Seems that is not implemented in tgpt yet.

**Comment by xpufx** [comment]
Come to think  of it. openai-gemini is not very convenient with this requirement that the clients all have to pass the gemini key. If you were writing your own tool, sure.

**Comment by aandrew-me** [comment]
I cannot properly test it because my country isn't supported by Gemini...
