### ISSUE TITLE
Multiline inputs cannot be piped

### ISSUE THREAD

**Issue by agvxov** [aandrew-me/tgpt#239]
The input passed will always cut off at the first newline in non-interactive mode.

For example:
```sh
$ bat example1.txt example2.txt
───────┬──────────────────────────────────
       │ File: example1.txt
───────┼──────────────────────────────────
   1   │ continue to list:
   2   │ 1. dog
   3   │ 2. cat
───────┴──────────────────────────────────
───────┬──────────────────────────────────
       │ File: example2.txt
───────┼──────────────────────────────────
   1   │ continue to list: 1. dog 2. cat
───────┴──────────────────────────────────
$ cat example1.txt | \tgpt

It seems like you're asking for a continuation of a list, but you haven't provided the context or the list you're ferring to. Could you please provide more details about the list you want to
 continue?

$ cat example2.txt | \tgpt

3. bird
```

### tgpt version: `tgpt 2.7.1`

**Comment by aandrew-me** [comment]
I gotta fix that, but for now you can make a slight modification and it will work:
`cat example1.txt | tgpt "Complete the list"`

**Comment by agvxov** [comment]
I'm actually "speed reading" pdf text rips by asking for a summary at each context window sized chunk.
My current work-around is piping the input through sed to replace the barrage of newlines with spaces. This works ok, but is hardly ideal. Also, the root of the problem was rather confusing at first while scripting.

**Comment by VedantWankhade** [comment]
If you dont mind can I work on this issue? I have been learning go for a few weeks now and would like to take a shot at this.

**Comment by aandrew-me** [comment]
> @aandrew-me, if you dont mind can I work on this issue? I have been learning go for a few weeks now and would like to take a shot at this.

Why would I mind? :) Go on. The right code already exists, you probably just need to replace
