### ISSUE TITLE
FeatureRequest "Multiline input"

### ISSUE THREAD

**Issue by SAXN-SYNX** [aandrew-me/tgpt#24]
Sending code to test  or debug doesn't work in interactive mode. 

Adding multiline support would help.
https://github.com/pterm/pterm

there is interactive_textinput/multi-line in here. if that helps.
Also adding a clear command to clear the terminal would help a lot.

**Comment by aandrew-me** [comment]
I was actually looking for a way to implement this. So thanks for helping!

**Comment by aandrew-me** [comment]
pterm was a bit problematic. But I was able to do it with a different library
