### ISSUE TITLE
multiline mode in linux: copy - paste does not work

### ISSUE THREAD

**Issue by ardabro** [aandrew-me/tgpt#243]
Linux, Debian, Cinnamon.
Copy shortcuts "c" and "b" always result in "Could not write to clipboard"
When I put anything into the system clipboard (text from the terminal window or editor), 
attempt to paste it with "p" results in "Could not read from clipboard".
Not sure if it tries to communicate with the system clipboard, or use its own semi-clipboard. 
In other words: Is paste from the system clipboard expected to work or not?

**Comment by aandrew-me** [comment]
It uses sytem clipboard, so you need to install the required system dependency. If you are on X11, you can try installing `xclip`/`xsel`. On wayland use `wl-clipboard`

**Comment by ardabro** [comment]
Right! I did a fresh system recently and forgot about Xsel. 
Now it works like a harm.
