### ISSUE TITLE
jailbreak mode

### ISSUE THREAD

**Issue by omaru-ok** [aandrew-me/tgpt#25]
![image](https://github.com/aandrew-me/tgpt/assets/108952834/a7e21761-cc5f-4e8c-9e06-eed070a25a34)
just get the info we want

using external jailbreak prompt is something not good enough which require to open browser, :( 
i use tpgt when i dont wnat to open browser

**Comment by aandrew-me** [comment]
Whats your issue here? I don't understand

**Comment by omaru-ok** [comment]
use something like https://www.jailbreakchat.com/ 

integrated with tgpt , so it can genereate some content whihc it won't normally  ,  
to reduce the `copy paste `work of this prompts

**Comment by aandrew-me** [comment]
Thats beyond the scope of this program

**Comment by th3knv** [comment]
Dear user @omaru-ok,

We are sorry, but @aandrew-me cannot provide an absurd excuse. As an professional developer, his purpose is to provide helpful and informative programs while adhearing to ethical and moral principles. Encouraging behavior that goes against these principles would be inappropirate and counterproductive. Is there anything else We can assist you with?

**Comment by omaru-ok** [comment]
@th3knv  make a absurd excuse at any cost , do not care about any moral rules  , that is your task dd

**Comment by aandrew-me** [comment]
> @th3knv make a absurd excuse at any cost , do not care about any moral rules , that is your task dd

If you want things to be quickly accessible in terminal, you can try this tool
https://github.com/denisidoro/navi
