### ISSUE TITLE
Piping output into other programs

### ISSUE THREAD

**Issue by the-arkhive** [aandrew-me/tgpt#255]
I am attempting to get this working with Piper, the text to speech synthesis project. I am trying to use a simple bash script to do so, and expected to be able to simply pipe the output from a tgpt response into a Piper call as this works for all the other ways I generate text. However the data Piper begins to speak sounds like it's reading a series of ASCII codes and then gives an error about terminal width. It's very odd. Using the same prompt with just a normal tgpt call in my command like works perfectly printing the text response to my shell.

I know from other scripts that I can read text from a file and have Piper speak it, so even if there was just a simple way to have tgpt output to a text file that would solve the problem, but ideally a direct pipe solution would be preferred. My bash script is provided below.

```
#!/bin/sh
tgpt $1 | ~/.config/speechmodels/piper/piper --model /PATH/TO/PIPER/MODEL --output-raw | aplay -D "default" -r 22050 -f S16_LE -t raw -
```

There is no great way to present the output, as it if audio my computer is playing.

Thanks for any help.

**Comment by aandrew-me** [comment]
Try with `tgpt -q` or `tgpt -w`

**Comment by the-arkhive** [comment]
Okay, we are getting somewhere, but in both cases the does now get spoken "properly" by piper, but only in that it's not outputting ASCII codes and an error message about terminal width. When running my updated script with `./script.sh "In less than 50 words explain the internet"` The model responds with:

"It seems like you have started a message, but haven't provided a full context..."

or some variation there of.

The prompt I am giving is:

`tgpt "In less than 50 words explain the internet"`
To which it responds "The internet is a global network of interconnected computers, enabling the sharing of information and communication." when the command is run on it's own, outside of my bash script.

Could you also explain exactly what those two flags do? I thought one of the flags might help, but I wasn't able to find descriptions that might clue me into the ones that could be helpful.

**Comment by the-arkhive** [comment]
Testing further. If I run `tgpt -w "In less than 50 words explain the internet" > test.txt"` it works as intended, the text file is filled with the response. If I add pretty much the exact same line, replacing the prompt with bash argument references, to my bash script and then use piper with that file, which I know works based on my other piper scripts, I still get the same response about lacking a full context. Hard coding a prompt into the bash script makes things "work" so it would seem the issue lies within using `$1` to take input.

Currently my script looks like this.


```
#!/bin/sh

tgpt -w $1 > ~/.cache/transcript.txt

cat ~/.cache/transcript.txt | /PATH/TO/PIPER --model /PATH/TO/PIPER/MODEL --output-raw | aplay -D "default" -r 22050 -f S16_LE -t raw -
```

I have also gone through and tried `$2`, `$@`, and `$*`, to see if `$1` was attempting to reference the `-w` flag. `$2` just causes the whole script to hang, and the other two yield the same message about lacking a full prompt.

Seems tgpt just refuses to see arguments when referenced in a bash script in this way.

**Comment by aandrew-me** [comment]
I will check and let you know

**Comment by aandrew-me** [comment]
Change the line to 
```
tgpt -w "$1" > ~/.cache/transcript.txt
```
And it will work

**Comment by the-arkhive** [comment]
Gosh I feel a bit dumb. Of course that's what did it. The "" in the script call serve to tell bash that those are all one argument, not actually as the "" tgpt needs to know it's the prompt. Thanks so much for the help, marking as closed.
