### ISSUE TITLE
how to ask follow up questions as in the web interface 

### ISSUE THREAD

**Issue by KingJulianS** [aandrew-me/tgpt#257]
Hi team ,

I am trying out tgpt on cli using phind as the provider. 
Is there way or some advice on how to keep a conversation flowing with follow up questions based on the previous interaction(as is possible with the web interface ?

**Comment by aandrew-me** [comment]
There are interactive modes. Check help menu with -h or — help

**Comment by KingJulianS** [comment]
Thanks the interactive is perfect for my use case.
