### ISSUE TITLE
[Feature Request] input file contents

### ISSUE THREAD

**Issue by SAXN-SYNX** [aandrew-me/tgpt#26]
Currenlty we can't paste 20 lines of text or code to pass into tgpt. So adding -f for file input mode to pass the contents directly would give more advantage to it.

- If there is limit to what the server can handle, then we should consider adding limit to file size or lines of code ?

For example : there is a python file with a function
```
What does someFunction do ?
import os
import sys

def someFunction():
   # Doing something
```

Directly sending this file as -f and get the output as interactive mode would help developers alot.

**Comment by aandrew-me** [comment]
Pasting 20 lines should not be a problem. Looks like there is a character limit and I increased it, so  from next update you will be able to paste more

**Comment by aandrew-me** [comment]
Check it, should be fine now

**Comment by aandrew-me** [comment]
If its not working with Ctrl + V, try with Ctrl + Shift + V

**Comment by SAXN-SYNX** [comment]
It works, Great.
