### ISSUE TITLE
Regarding free chatgpt 3.5 api access

### ISSUE THREAD

**Issue by HakaishinShwet** [aandrew-me/tgpt#260]
https://github.com/PawanOsman/ChatGPT
This project providing ChatGPT gpt-3.5-turbo API for Free (as a Reverse Proxy).So can you study this product like what it is doing to achieve free chatgpt api access and can we implement something from this project to this tgpt project to have better free chatgpt cli chat

**Comment by aandrew-me** [comment]
It requires api key. And there is already gpt 3.5 in tgpt
