### ISSUE TITLE
feature request - raw text output

### ISSUE THREAD

**Issue by DarioDarko** [aandrew-me/tgpt#265]
hi,

ive been using tgpt a lot lately, cool project! :smile: 

i would really like to get an option for raw text output to enable further processing. for instance you could send the output to a [text2speech model](https://github.com/rhasspy/piper), create logs of your chats, etc.

**Comment by aandrew-me** [comment]
Hello, -w and -q are already available for that

**Comment by DarioDarko** [comment]
they dont work in interactive or multiline mode tho. i dont like using the regular mode because it doesn't support continuous conversation

**Comment by aandrew-me** [comment]
Ah okay so you want to be able to save logs of interactive modes. Did I get it right?

**Comment by DarioDarko** [comment]
i already do that with script, but its a PITA because of all the escape characters and such :grin: so raw text would be way easier to process. a builtin function to create logs would ofc also be great.

i just tried tgpt -w -q with piper and its amazing! id love to have that for interactive modes

> piper_dir="${HOME}/.local/bin/piper"
> onnx="${piper_dir}/voices/amy.onnx"
> json="${piper_dir}/voices/amy.json"
> 
> t2s()
> {
> 	tgpt -w -q "$1" \
> 	| tr -d "*" \
> 	| ${piper_dir}/piper -m "$onnx" -c "$json" --output-raw \
> 	| aplay -r 22050 -f S16_LE -t raw -
> }

im sure others would find more usecases for a raw text output

**Comment by aandrew-me** [comment]
I am not sure about your usage of the words "raw text". Because what I mean by raw text is the unmodified text received from the API. And that unmodified text contains different types of escape characters, then the program parses the text and the characters aren't there anymore

**Comment by aandrew-me** [comment]
Also -w and -q are separate options

**Comment by DarioDarko** [comment]
> I am not sure about your usage of the words "raw text". Because what I mean by raw text is the unmodified text received from the API. And that unmodified text contains different types of escape characters, then the program parses the text and the escape characters aren't there anymore

i didnt know that it comes from the API like this. heres what the script command produces with tgpt -i
![image](https://github.com/aandrew-me/tgpt/assets/154679092/580cf332-cfb3-4dd6-906a-67829ba51c98)

i can cat the log in the terminal and it looks fine, but its a mess if i open it in a text editor. the normal mode works better, but the big disadvantage of that is that it keeps forgetting all the context, so its impossible to have a 'chat'

**Comment by aandrew-me** [comment]
It doesn't come from the API like this. Are yoy trying to pipe output from interactive mode to piper? Because you cant just pipe the interactive mode, you will get those strange characters.

**Comment by DarioDarko** [comment]
basically what i would like is an interactive mode that gives unformatted text ('raw'). or text that is not hard to process, like the output from normal mode. normal mode text output with a continuous chat.

**Comment by aandrew-me** [comment]
I'm afraid interactive mode cant give such text. But what I can do is log "raw text" to a file

**Comment by DarioDarko** [comment]
live logging? i mean writing to the log file after each reply from the AI? that would be awesome. i could "log" to a bash pipe, watch it with a script and process the text like i want to.

**Comment by aandrew-me** [comment]
Yes live logging

**Comment by agvxov** [comment]
I might be misunderstanding the issue, but doesn't GNU Script with `--flush` solve the logging part, making the problem boil down to for example `-q` working with `-i` in such a way that all ascii escapes are omited?

**Comment by SuXYIO** [comment]
With bash.  
Redirected to `less`, since im having problems using it in tmux, which doesn't support mouse scroll.  
```bash
#!/bin/bash
while true; do
	read -rp 'Prompt> ' prompt
	tgpt -w "${prompt}" | less
done
```
Similar to original `-iw`
Alias this thing in your `zshrc` or `bashrc`, and you're done!

**Comment by SuXYIO** [comment]
A more complete version, "highly customizable". 
Needs `glow` and `pygmentize` to work. Customize it yourself. 
```bash
#!/bin/bash
while true; do
	read -rep $'\033[32mPrompt> \033[0m' prompt
	if [ "${prompt}" == 'q' ]; then
		exit
	fi
	tgpt -w "${prompt}" | glow | pygmentize | less
done
```
Quite rough, but enough, at least for me. 

> With bash. Redirected to `less`, since im having problems using it in tmux, which doesn't support mouse scroll.
> 
> ```shell
> #!/bin/bash
> while true; do
> 	read -rp 'Prompt> ' prompt
> 	tgpt -w "${prompt}" | less
> done
> ```
> 
> Similar to original `-iw` Alias this thing in your `zshrc` or `bashrc`, and you're done!

**Comment by agvxov** [comment]
@SuXYIO 
> im having problems using it in tmux, which doesn't support mouse scroll.
what do you mean? you can scroll tmux buffers with the mouse. as far as i know this is the only config one requires for it: `set -g mouse on`

**Comment by SuXYIO** [comment]
@agvxov
Dude, don't mind that, programming noobie. 
Thanks for the tip though ^_^

**Comment by DarioDarko** [comment]
@agvxov
i dont know what --flush does. anyways i will wait for the tgpt logging feature

> Similar to original `-iw` Alias this thing in your `zshrc` or `bashrc`, and you're done!
@SuXYIO
its not similar to tgpt interactive mode, since it doesnt allow for continuous chat

**Comment by agvxov** [comment]
@DarioDarko
GNU Script records all the text that is going on your terminal to a file, `--flush` makes it not buffer per performance reasons, but continuously write, meaning the file its writing to will always up to date with your terminal output. This can be used to read whatever happens in your terminal in real time without awkwardly redirecting everything with `tee` or depending on builtin logging features.

More over, since we have tools like this, program developers no not have to force logging features into every executable ever.

**Comment by SuXYIO** [comment]
@DarioDarko, i know, haven't found a way to enable continuous chat yet. If `tgpt` has a feature that can get and use the _`dialog-number`_ (or something like that), it'll be easy to integrate continuous chat and other stuff.  
i think the feature won't be hard to implement for providers like `blackboxai`, which ends the `url` with _`dialog_number`_. Can't help to write code, since i have no idea how to write `Go` code.
