### ISSUE TITLE
keyboard left and right key fast traversal possible in tgpt interactive mode?

### ISSUE THREAD

**Issue by HakaishinShwet** [aandrew-me/tgpt#269]
what i mean by this is that if in normal terminal we write some commands or sentenace which has many words and want to go back and forth between words faster then we can use shortcut (ctrl+ left or right movement key) to move faster to next or previous word which make things faster and easier to correct or delete any word. So is it possible to have this shortcut functionality in interactive mode of tgpt because right now it is not possible so it makes sometimes little difficult to go back fast and correct back the typed request so was asking. If it possible then please implement it to make things more smooth for everyone (not just me) :-))
Thankyou

**Comment by aandrew-me** [comment]
That's why there is multiline interactive mode, -m
