### ISSUE TITLE
[Linux] Please make it so that the update function does not install under /usr/local/bin/

### ISSUE THREAD

**Issue by pitsi** [aandrew-me/tgpt#27]
As mentioned in the title, the update function seems to just execute the install script that asks for sudo so as to put it in the  /usr/local/bin/ folder. In my case though, tgpt is in ~/bin/ and I would like it to stay there. In plain terminal output
```
$ which tgpt-linux-amd64 
/home/user/bin//tgpt-linux-amd64

$ tgpt-linux-amd64 --version
tgpt 1.4.2

$ tgpt-linux-amd64 --update
Updating...
[sudo] password for user: 
```
p.s. I know it is on 1.4.2. I thought the upgrade would bring it to 1.4.3, that's why I used an older version. However, a few minutes earlier I realised that it got a lot of updates in the last 2 days.

**Comment by aandrew-me** [comment]
I am working on something which would allow the install script to get a custom filepath when installing for the first time. So when program will be updated, the file will be downloaded to that particular path

**Comment by pitsi** [comment]
```
$ tgpt-linux-amd64 --update
Updating...
Download location: /home/user/bin/tgpt-linux-amd64
Operating System: linux
Processor Architecture: amd64

Downloading...

######################################################################## 100.0%
Installed Successfully 

Make sure your file is in PATH
Then run tgpt -h to get started
Successfully updated.
```

That's perfect!
