### ISSUE TITLE
opengpts down?

### ISSUE THREAD

**Issue by sinuso** [aandrew-me/tgpt#274]
**tgpt --provider opengpts -q "hi"**

![image](https://github.com/aandrew-me/tgpt/assets/11968484/daf1e8c6-578f-4b03-b2bb-98b8049a0208)

**Comment by aandrew-me** [comment]
Yeah looks like it is. Nothing to do but wait. Maybe it will start working again, maybe not

**Comment by aandrew-me** [comment]
Yeah I will just remove it, if it ever works again, I will add again
