### ISSUE TITLE
panic when running TGPT with -s argument

### ISSUE THREAD

**Issue by xplshn** [aandrew-me/tgpt#28]
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.main()
	/home/runner/work/tgpt/tgpt/main.go:61 +0x1025

When I ran "tgpt -s" it panicked and spit out this.
But when I use "tgpt -s "update my system" " it works.

**Comment by xplshn** [comment]
Also when I typed Y
even thought tgpt showed me the command "sudo apt-get update && sudo apt-get upgrade -y"
the system gave me an error, and I'm not sure what it really executed. The error had a poor translation to Spanish and it seems TGPT executed another thing and not the command it showed me

**Comment by aandrew-me** [comment]
> panic: runtime error: index out of range [2] with length 2
> 
> goroutine 1 [running]: main.main() /home/runner/work/tgpt/tgpt/main.go:61 +0x1025
> 
> When I ran "tgpt -s" it panicked and spit out this. But when I use "tgpt -s "update my system" " it works.

Well you are not supposed to just run `tgpt -s` without some text, however I will improve the error message.

**Comment by aandrew-me** [comment]
tgpt only executes the command it shows

> Also when I typed Y even thought tgpt showed me the command "sudo apt-get update && sudo apt-get upgrade -y" the system gave me an error, and I'm not sure what it really executed. The error had a poor translation to Spanish and it seems TGPT executed another thing and not the command it showed me

**Comment by xplshn** [comment]
> tgpt only executes the command it shows
> 
> > Also when I typed Y even thought tgpt showed me the command "sudo apt-get update && sudo apt-get upgrade -y" the system gave me an error, and I'm not sure what it really executed. The error had a poor translation to Spanish and it seems TGPT executed another thing and not the command it showed me

Well, that's the expected behaivor, but it runs part of the answer, sometimes. Like "As an AI model ...", it tries to run every word, ruining you bash_history

**Comment by aandrew-me** [comment]
> > tgpt only executes the command it shows
> > > Also when I typed Y even thought tgpt showed me the command "sudo apt-get update && sudo apt-get upgrade -y" the system gave me an error, and I'm not sure what it really executed. The error had a poor translation to Spanish and it seems TGPT executed another thing and not the command it showed me
> 
> Well, that's the expected behaivor, but it runs part of the answer, sometimes. Like "As an AI model ...", it tries to run every word, ruining you bash_history

If you check the help page with -h, you will see that i added (Experimental). Thats because sometimes GPT misbehaves and provides additional info other than the command. The program assumes that GPT provided only the command and it executes it. So if you see that something else has been provided, dont execute it
