### ISSUE TITLE
Latex code not rendered

### ISSUE THREAD

**Issue by git-aniket** [aandrew-me/tgpt#285]
Thanks for the amazing tool. 
I think what could make tgpt even more useful is if it would be able to render latex characters correctly.

I guess this package could help.
[https://github.com/go-latex/latex]()
Currently, the output for the interactive mode looks like this. But a latex based rendering would help make it easier in reading.
![Screenshot from 2024-08-13 12-31-48](https://github.com/user-attachments/assets/c105448b-bc19-4ccc-b0d2-5af8694349ec)

**Comment by aandrew-me** [comment]
Hello, well as far as I know, you cannot  just render latex characters in terminal, its probably possible to show them in terminal by converting to images and using other programs and all, but its just better to use a website instead.

Also I tried compiling text in a latex editor online and, doesn't look good...
![image](https://github.com/user-attachments/assets/b4ad0af7-9479-4128-b453-8edfd7ed8081)
