### ISSUE TITLE
`scoop` install 404

### ISSUE THREAD

**Issue by omaru-ok** [aandrew-me/tgpt#29]
![image](https://github.com/aandrew-me/tgpt/assets/108952834/2ca6f299-9527-4e5e-a727-d19420b124cd)

trying to install latest release 1.5.2

**Comment by aandrew-me** [comment]
My bad, I forgot to put the tag, it should work now

**Comment by aandrew-me** [comment]
And you don't need to do `scoop install...` again. You can just do `scoop update tgpt`

**Comment by omaru-ok** [comment]
i know about `scoop update` i did clean install because of errors

**Comment by omaru-ok** [comment]
![image](https://github.com/aandrew-me/tgpt/assets/108952834/54579b2b-2b1a-4df7-9998-75bd34917499)
can u fix thsi too?

**Comment by aandrew-me** [comment]
Don't worry, its not an error, just a warning. Putting the hashes every time is annoying, so I just don't put them

**Comment by omaru-ok** [comment]
@aandrew-me you app is getting famous's, `hashes` correctness will be needed to ensure security, to avoid package flaw ,
u can skip it for now , but after certain popularity , it is necessary, also u can automate it , 
scoop manifest is fully automated 🤔  or am i wrong?

**Comment by aandrew-me** [comment]
Manifest is not automated. I have to change the version each time. As for hashes, i need op download both 64 bit and 32 bit exes, calculate their hashes and put it there. 

And famous or not famous doesn't matter for me in case of this program. I made it for personal use and also made it open do that others can use it. Its free open source, so I don't owe anyone anything. If someone wants to use he/she will. Also who if the site stops working, so will the program

**Comment by aandrew-me** [comment]
Also putting hashes isn't actually increasing security.
https://youtu.be/b4b8ktEV4Bg?t=401
