### ISSUE TITLE
Line breaks in web search

### ISSUE THREAD

**Issue by brontosaurusrex** [aandrew-me/tgpt#290]
When typing

    ai "What is going on in Ukraine"

i get

    @web_search "Ukraine current situation news updates 2023"Based on the search results provided, here is an overview o...

Where did it got 2023? Why no line breaks?

ai is aliased to tgpt.

**Comment by satanx016** [comment]
same issue here
`How to make a loop in java`
outputs this:
`Java loop example`
Weird, it's like it's outputing a more simpler and concise form of the prompt but not an answer

**Comment by aandrew-me** [comment]
Hm Phind is behaving strangely, use some other provider for now
