### ISSUE TITLE
tgpt-bin is not found in AUR

### ISSUE THREAD

**Issue by itsmenewbie03** [aandrew-me/tgpt#292]
Currently https://aur.archlinux.org/packages/tgpt-bin returns 404.

**Comment by aandrew-me** [comment]
Its now in official repos, I have added that to README :)
https://github.com/aandrew-me/tgpt?tab=readme-ov-file#download-for-gnulinux--or-macos-

**Comment by itsmenewbie03** [comment]
Thanks
