### ISSUE TITLE
Configure OpenAI URL using an environment variable

### ISSUE THREAD

**Issue by hoh** [aandrew-me/tgpt#293]
Currently, the OpenAI URL is set using the `--url` flag, as mentioned in the README. It would be more convenient to allow the configuration of this URL through an environment variable, such as `AI_PROVIDER_URL`, to avoid needing to specify it with every command. This would simplify usage in terminal and scripts.

**Comment by aandrew-me** [comment]
`OPENAI_URL` will be available in next update
