### ISSUE TITLE
--disable-input-limit flag doesn't work with -q or -w

### ISSUE THREAD

**Issue by Tasin269** [aandrew-me/tgpt#296]
Hello Dev,
I'm tying to pipe a txt file which is over 4000 chars and I need to store the result in another txt file so I used --disable-input-limit with -q and it's not working saying exceeded 4000 limit but working when flags used individually

**Comment by Tasin269** [comment]
Never mind I fixed it on my own. But I still have a problem. Is there any way to use the same vqd on a non-interactive session? I was trying to use old chats without using the for loop so I could send them multiple requests on same session with a bash script. Thanks in advance.

**Comment by aandrew-me** [comment]
If you're doing bash scripting, you can try directly making request with curl
