### ISSUE TITLE
Region error

### ISSUE THREAD

**Issue by bbbberd** [aandrew-me/tgpt#297]
Hello dev i installed this with go and I got this error

![Screenshot 2024-09-18 184459](https://github.com/user-attachments/assets/1d801710-108b-40fe-ae33-4e1e225f39ab)

my location is jakarta/indonesia, how to deal with this?

**Comment by aandrew-me** [comment]
Well looks like the default provider won't work. You can try other providers. Check the help menu and you will see the list
