### ISSUE TITLE
Can you use Python to write a simple request for topic

### ISSUE THREAD

**Issue by yybjy** [aandrew-me/tgpt#30]
i don't konw why i use python couldn't pass:
url="https://chatbot.theb.ai/api/chat-process"

headers = {
    'Content-Length':'93',
    'authority':'chatbot.theb.ai',
    'Content-Type':'application/json',
    "Referer": "https://chatbot.theb.ai/",
    "accept": "application/json, text/plain, */*",
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
    'Cookie':'_ga=''
}
data={
    "prompt":"who are you",
    "options":{"parentMessageId":"chatcmpl-7Ez7G8eRMBVroyBc7AWxcvr7lzq2U"}
    }
data1=json.dumps(data)
resp= requests.post(url,headers=headers,data=data1,timeout=100000)
print(resp)
resp.raise_for_status()
print(resp.status_code, resp.text)

**Comment by aandrew-me** [comment]
This is because of [TLS Fingerprinting](https://httptoolkit.com/blog/tls-fingerprinting-node-js/#how-does-tls-fingerprinting-work)

**Comment by aandrew-me** [comment]
This is not the place to talk about your issues, if you want, message me on [any of those](https://aandrew.netlify.app/#contact)
