### ISSUE TITLE
Command Fails with Piped Input and Arguments

### ISSUE THREAD

**Issue by patrickkdev** [aandrew-me/tgpt#300]
When piping input into the tgpt command and providing arguments (e.g., --provider duckduckgo and --model gpt-4o-mini), it returns "You need to write something." This issue only occurs when the input is piped. The command works without issues when no arguments are provided, or when input is not piped.

Steps to Reproduce:

Run cat file.txt | tgpt – this works as expected.
Run cat file.txt | tgpt --provider duckduckgo --model 'gpt-4o-mini' – returns "You need to write something."
Expected Behavior: The command should process the piped input along with the specified arguments.

Actual Behavior: The command returns "You need to write something" when piped input is used with arguments.

Screenshot:
![Screenshot From 2024-10-01 20-28-10](https://github.com/user-attachments/assets/5062ab57-7197-462a-806d-c2a68e24aaf3)

**Comment by aandrew-me** [comment]
It is intended behavior. Infact I will modify so that it requires arguments when no provider is provided

**Comment by SinaiOnline** [comment]
So I can't pipe input when using other providers?

**Comment by aandrew-me** [comment]
You can, you just have to add some text
```
cat foo.txt | tgpt —provider duckduckgo "Analyze the content"
```

**Comment by patrickkdev** [comment]
Makes sense. Thank you
