### ISSUE TITLE
Can't change model to Ollama

### ISSUE THREAD

**Issue by Telementry** [aandrew-me/tgpt#304]
Every single time i type the instrunctions it just tells me "You need to write"

**Comment by aandrew-me** [comment]
If you don't provide details, how will I understand? :)

**Comment by Telementry** [comment]
Now that I think about it there might have just been some step that i didn't do so I think the tutorial that I was following had a cut,so could anybody please help me with the steps to change the model from Phind to ChatGPT and I have api keys so that won't be a problem

**Comment by aandrew-me** [comment]
There are examples in the help menu

**Comment by Telementry** [comment]
So basically i type this:tgpt --model openai, but then it just say you need to write something

**Comment by aandrew-me** [comment]
`tgpt --provider openai --key "sk-xxxx" --model "gpt-3.5-turbo" "What is 1+1"`

**Comment by Telementry** [comment]
Thanks man

**Comment by Telementry** [comment]
Some error has occurred. Statuscode: 429
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
And I had entered my API Key that i got from https://platform.openai.com/api-keys
