### ISSUE TITLE
feature request for multiline mode: preset messages

### ISSUE THREAD

**Issue by ardabro** [aandrew-me/tgpt#309]
When I'm asking AI about something I often add some tuning additions like "give me a minimalistic example, don't elaborate too much", or: "to the point, don't tell me how to start a terminal or install a package".  Usually, the purpose is to minimize the flood of useless bullshit it spills.
It would be nice to have a set of preset messages like this, prepared to be easily pasted into chat using keyboard shortcuts. 
ctr+1,2,3 or alt+1,2,3 would be probably the best choices.
What do You think?

**Comment by aandrew-me** [comment]
There is a preprompt option. You can create aliases with different prepromts. I think that will be even more convenient

**Comment by ardabro** [comment]
Yeah, but if you conduct a conversation you may want to add such addition (or a different one every time) to each subsequent query. Single preprompt, decided once at the very beginning, doesn't help much.

**Comment by aandrew-me** [comment]
It doesn't make much sense for me to add it in the program. Reminded me of AutoHotkey- https://www.autohotkey.com/
