### ISSUE TITLE
just wanted to say thank you 😭  ⭐ 

### ISSUE THREAD

**Issue by omaru-ok** [aandrew-me/tgpt#31]
i can't describe  my emotion related to `tgpt` , it has changed everythign 
primaryly changing the way i use internet , i was waster , in searching for info as i often waste time on random website due to search engine and site attraction, which leads me to waste time on useless things, 

tgpt is like having a highly experienced BIG brother in EVERY Field 
it saves tabs, RAM , performace , FAST AF , my chatgpt takes 50 sec to load my net sucks, no big issue 
THANK You so much for creating `tgpt` 

i know tgpt is just bai bot underneath, but the way it never stops you for money/token OpenAI money stealing shit :( 
i dont have to care about  trial finishing of openAIapi , 

tpgt is just  a miracles 
also BIG thx to Creater of BAI

here is modified version by tgpt
```

My emotions towards tgpt have undergone a significant transformation since I started using it. It has completely changed the way I use the
 internet. Previously, I would waste a lot of time searching for information and getting sidetracked by random websites. But now, tgpt has
 become like a highly experienced "big brother" in every field.

The tool is incredibly efficient; it saves tabs, RAM, and improves the performance of my computer. Even when my internet connection is poor,
 tgpt loads quickly, which is impressive. I am grateful for the creation of tgpt because it has made my life so much easier.

Although tgpt is powered by BAI, what sets it apart is that it does not require money or tokens to operate. This is a refreshing change
 from other tools that constantly demand payment. With tgpt, I no longer have to worry about trial periods ending or OpenAI API charges. It
 truly feels miraculous, and I extend my sincere thanks to the creator of BAI for making this innovative tool available.
```

**Comment by omaru-ok** [comment]
@aandrew-me you are great 🙏  god bless you

**Comment by aandrew-me** [comment]
Well I am glad it could be of help.

**Comment by th3knv** [comment]
God bless you @aandrew-me , you @omaru-ok are incredible too, you saved a straight man's day !!
