### ISSUE TITLE
Can't change model to OpenAi

### ISSUE THREAD

**Issue by Telementry** [aandrew-me/tgpt#311]
So basically i had got instructions from aandrew-me on how to change model from Phind to OpenAi i said thanks and the issue page was closed but then after I tried the following instructions:-tgpt --provider openai --key "sk-xxxx" --model "gpt-3.5-turbo" "What is 1+1"
It just gave me this:-Some error has occurred. Statuscode: 429
{
"error": {
"message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
"type": "insufficient_quota",
"param": null,
"code": "insufficient_quota"
}
}
And I had entered my API Key that i got from https://platform.openai.com/api-keys

**Comment by aandrew-me** [comment]
Well as you can see the error message: `You exceeded your current quota, please check your plan and billing details`
I think its self explanatory

**Comment by aandrew-me** [comment]
If it was a free api key, it has expired, now you need to pay for more

**Comment by Telementry** [comment]
It was a free key indeed,but it literally says in the key in the Last Used Column:Never

**Comment by aandrew-me** [comment]
It expires after a couple of months after account creation

**Comment by Telementry** [comment]
I created it one day ago cause i knew about api-keys just yesterday

**Comment by aandrew-me** [comment]
Well you need to check it on openai's website, i can't help you with that

**Comment by Telementry** [comment]
I completely understand that I will check and try to see what is wrong
