### ISSUE TITLE
Disable input limit flag fails to work when other flags are also supplied

### ISSUE THREAD

**Issue by AkashRajpurohit** [aandrew-me/tgpt#313]
Using multiple other flags along with `--disable-input-limit` fails to work.

I tried a large prompt with with `--disable-input-limit` and it worked fine but when I tacked in the `--quiet` flag then it did not respect the `--disable-input-limit` and throwed `Input exceeds the input limit of 4000 characters` error.

**Comment by Calebe94** [comment]
I've tested with all flags and got the same error.

**Comment by aandrew-me** [comment]
I will take a look

**Comment by aandrew-me** [comment]
I will remove input limit check altogether
