### ISSUE TITLE
Add ability to preload instructions for interactive mode

### ISSUE THREAD

**Issue by Leafback** [aandrew-me/tgpt#315]
I'm not seeing a way to preload information into interactive mode. For instance: 

> $ tgpt -i "Call me Ismael"
>
> Bot: Hello Ismael

Is there a way to add this idea in?

**Comment by aandrew-me** [comment]
What's the issue with `— preprompt`

**Comment by Leafback** [comment]
I saw, but it doesn't seem to work with interactive mode. 

I've tried:

> tgpt -i -preprompt "what is 2+2?"
> tgpt -i --preprompt "what is 2+2?"
> tgpt -preprompt "what is 2+2?" -i
> tgpt --preprompt "what is 2+2?" -i

Is my formatting wrong?

**Comment by aandrew-me** [comment]
![image](https://github.com/user-attachments/assets/08f37cfc-1486-4da2-baf7-c798432c2db9)

**Comment by Leafback** [comment]
...looks like a PEBKAC. Thank you and disregard!

**Comment by aandrew-me** [comment]
:)
