### ISSUE TITLE
STATUSCODE: 403

### ISSUE THREAD

**Issue by arcel1945** [aandrew-me/tgpt#316]
<img width="287" alt="Screenshot 2024-11-27 000956" src="https://github.com/user-attachments/assets/02917252-0651-491e-8618-98da9e04fa9f">

**Comment by arcel1945** [comment]
please help me someone

**Comment by aandrew-me** [comment]
Well as you see the error is related to your IP address. 
Try other providers like duckduckgo
`tgpt -provider duckduckgo "hello"`
