### ISSUE TITLE
Where are the config files?

### ISSUE THREAD

**Issue by chrischtili** [aandrew-me/tgpt#322]
I have installed TGP on my Mac via curl. Where can I find the configuration files? I've searched everything but can't find anything.
They are not in /Library/Application Support/tgpt and not in ~/.config/tgpt.

**Comment by aandrew-me** [comment]
You can create config file for proxy, other than that there are no config files

**Comment by chrischtili** [comment]
ok..great.
I would like to use my installed Ollama models. Then I need to do a git clone, then adjust ollama.go, and then run the installation script. Is this correct? How should ollama.go look when I have two models? qwen2.5-coder:7b and llama3.1:8b-instruct-q4_1

**Comment by aandrew-me** [comment]
You don't need any ollama.go file, you just start your a model with `ollama run qwen2.5-coder:7b`, then you can chat with it
For example
`tgpt -provider ollama -model qwen2.5-coder:7b -i`
