### ISSUE TITLE
Prettier interactive mode

### ISSUE THREAD

**Issue by jyash8** [aandrew-me/tgpt#33]
Could you please make interactive mode prettier with colors or symbols like this
![image](https://github.com/aandrew-me/tgpt/assets/122196951/a96a4151-cc0d-432b-8f56-616877721d6c)
i have done it using simple bash but i think integrating into "tgpt" would be good

**Comment by aandrew-me** [comment]
Will be available in next update

**Comment by NormTurtle** [comment]
can i plain one, i dont like that kind of `pretty look` particularly

also why this keep happening?
![image](https://github.com/aandrew-me/tgpt/assets/108952834/0326af9d-e516-42dc-80bc-519e36f1172b)

on empty lines

**Comment by aandrew-me** [comment]
> can i plain one, i dont like that kind of `pretty look` particularly
> 
> also why this keep happening? ![image](https://user-images.githubusercontent.com/108952834/238920734-0326af9d-e516-42dc-80bc-519e36f1172b.png)
> 
> on empty lines

The program is made for many people, not one. If you don't like something, you can modify source code and build for yourself. I am fixing that error, but why would you send empty lines?

**Comment by NormTurtle** [comment]
> why would you send empty lines? 

imagin you copied lots of text from somewhere and it start with empty lines 

so both only reply with 
`%!s(<nil>)

**Comment by NormTurtle** [comment]
![image](https://github.com/aandrew-me/tgpt/assets/108952834/2d4e2c87-899a-47df-bd4d-4f580b2e0404)

its not  a blank line tho

**Comment by aandrew-me** [comment]
> ![image](https://user-images.githubusercontent.com/108952834/239734847-2d4e2c87-899a-47df-bd4d-4f580b2e0404.png)
> 
> its not a blank line tho

Yes this happens when server doesn't respond with the desired response. I am fixing it. So next time it should provide more detailed message
