### ISSUE TITLE
Error Launch on Arch Linux, (latest upgrade won't fix)

### ISSUE THREAD

**Issue by najibnet** [aandrew-me/tgpt#34]
please fix this, I dont know but it works on my other systems like WSL Ubuntu, and Termux, it fails on my Arch Linux but it used to work before it returns error like this (attached):

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
        /home/runner/work/tgpt/tgpt/main.go:42 +0xb05
![image](https://github.com/aandrew-me/tgpt/assets/134274255/5f80328b-7cd7-4bca-8cfe-5fc5b33afde6)

**Comment by aandrew-me** [comment]
I am on an Arch Based distro too and I have no problems, so provide more details. How did you install the program?

**Comment by najibnet** [comment]
I installed it by Yay, I supposed that this program does not connect to its dependency app, (Go), so it returns error. Fortunately, I also have other two Arch systems (a netbook & a raspberry pi3b), they run fine... this is the screenshot i have, after uninstalling Go, when reinstalling TGPT back, Yay passes its dependency, it returns the same error, the same way when Go was installed. I am confused by now..

this is the screenshot from : Yay -Si tgpt

You can see that, it depends on nothing, very weird
![image](https://github.com/aandrew-me/tgpt/assets/134274255/ef0e8351-2af7-48c1-87bb-d014bfd6396d)

**Comment by aandrew-me** [comment]
Firstly. AUR has `tgpt` and `tgpt-bin`. I recommend downloading `tgpt-bin`. 

Now I realized, its a problem in the program, so I am fixing it, and it should work in next update

**Comment by aandrew-me** [comment]
For now, do 
`rm ~/.config/tgpt/config.txt`
It should fix this

**Comment by najibnet** [comment]
Thank you very much, it indeed works again..
I appreciate your work very much.. I install TGPT on many devices I have, including Mac on homebrew, 3 Archs, 3 android phones on Termux.. this app really helps me, because it needs no API & I can instantly launch it with very low resources available..

**Comment by aandrew-me** [comment]
Glad to know that!
But how does it work on android phones? I don't build for android phones, so which one do you use?

**Comment by najibnet** [comment]
I works on Android, I use Termux
Install Golang on it.. and then I install it using your Go installer.. it works

![image](https://github.com/aandrew-me/tgpt/assets/134274255/52d33e7c-a433-4f22-bc06-7ceb845db51c)

**Comment by aandrew-me** [comment]
Oh I see, you build for yourself. Great! Ok I have pushed update which should fix the issue. Have a nice day!
