### ISSUE TITLE
Redirecting stdout not works as intended

### ISSUE THREAD

**Issue by amitkrxyz** [aandrew-me/tgpt#35]
When redirecting the output to a file it puts a newline after the end of every single word and it also includes the loading spinner and original question which is not expected.

`tgpt "What is the purpose of life"  > ans.txt`

`cat ans.txt`

<details>
<summary>Output:</summary>

> ⣾  Loading
> ⣽  Loading
> ⣻  Loading
> ⢿  Loading
> ⡿  Loading
> ⣟  Loading
> ⣯  Loading
> ⣷  Loading
> ⣾  Loading
> ⣽  Loading
> ⣻  Loading
> ⢿  Loading
> ⡿  Loading
> ⣟  Loading
> ⣯  Loading
> ⣷  Loading
> ⣾  Loading
> ⣽  Loading
> ⣻  Loading
> ⢿  Loading
> ⡿  Loading
> ⣟  Loading
> ⣯  Loading
> 
>           
> 
> What is the purpose of life
> 
> 
> The
>  purpose
>  of
>  life
>  is
>  a
>  philosophical
>  question
>  that
>  has
>  puzzled
>  humans
>  for
>  centuries
> .
>  While
>  there
>  is
>  no
>  one
>  "
> correct
> "
>  answer
>  to
>  this
>  question
> ,
>  some
>  people
>  believe
>  that
>  the
>  purpose
>  of
>  life
>  is
>  to
>  find
>  happiness
> ,
>  others
>  believe
>  that
>  it
>  is
>  to
>  fulfill
>  certain
>  duties
>  or
>  obligations
> ,
>  and
>  still
>  others
>  believe
>  that
>  it
>  is
>  to
>  seek
>  knowledge
>  or
>  spiritual
>  enlightenment
> .
>  Ultimately
> ,
>  the
>  purpose
>  of
>  life
>  is
>  a
>  deeply
>  personal
>  and
>  subjective
>  matter
>  that
>  each
>  individual
>  must
>  explore
>  and
>  determine
>  for
>  themselves
>  based
>  on
>  their
>  own
>  beliefs
> ,
>  values
> ,
>  and
>  experiences
> .
> 
</details>

**Comment by amitkrxyz** [comment]
It was kind of working in version 1. But now it is printing newline after every word. Idk if this is fixable or not.

**Comment by aandrew-me** [comment]
> It was kind of working in version 1. But now it is printing newline after every word. Idk if this is fixable or not.

In version the whole text was printed whereas in the latest versions, the text is printed word by word.
