### ISSUE TITLE
[Feature Request] Add an option to inject prompts before asking something

### ISSUE THREAD

**Issue by xplshn** [aandrew-me/tgpt#37]
Let me explain, if there was an option for the user to add a prompt before his real prompt, you could have personalities or a custom assistan. For example, whenever I use TGPT I tell it my personal beliefs and political vision so it doesn't generate things I wouldn't believe, other AI projects also use this when they want ChatGPT to do something specific, like generating JSONs, Code, or Shell commands.

PS: Your project is awesome, keep it up. Maybe you can add more back-ends, even Dall-E?

**Comment by aandrew-me** [comment]
> whenever I use TGPT I tell it my personal beliefs and political vision so it doesn't generate things I wouldn't believe
🙃

Adding different custom prompts is beyond the scope of this program. However I can suggest a program that can help you with that - https://github.com/denisidoro/navi

Dall-E is an image generation model and it needs an API Key. So I don't see how its related with this tool

**Comment by xplshn** [comment]
Thanks, I'll check it out.

-

There might already be unofficial APIs for Dall-e I've seen some people try with automated account generation, I myself used disposable email to sign in to OpenAI.

**Comment by aandrew-me** [comment]
If you find unofficial APIs, let me know. To use openAI API you need to register and verify your phone number. So just disposable email is not enough

**Comment by xplshn** [comment]
I didn't have to use my phone number though, maybe because of the region. Anyways, if I end up encountering other APIs, I'll let you know. Also, check this ones out:
https://api.hypere.app/#get-started the source is here https://github.com/FoxGPT/gpt
https://github.com/xtekky/gpt4free





forefront.ai | GPT-4/3.5
-- | --
poe.com | GPT-4/3.5
writesonic.com | GPT-3.5 / Internet
t3nsor.com | GPT-3.5
you.com | GPT-3.5 / Internet / good search
sqlchat.ai | GPT-3.5
bard.google.com | custom / search
bing.com/chat | GPT-4/3.5
italygpt.it | GPT-3.5
deepai.org | GPT-3.5 / chat support

[forefront.ai](https://chat.forefront.ai/) 	GPT-4/3.5
[poe.com](https://poe.com/) 	GPT-4/3.5
[writesonic.com](https://writesonic.com/) 	GPT-3.5 / Internet
[t3nsor.com](https://t3nsor.com/) 	GPT-3.5
[you.com](https://you.com/) 	GPT-3.5 / Internet / good search
[sqlchat.ai](https://sqlchat.ai/) 	GPT-3.5
[bard.google.com](https://bard.google.com/) 	custom / search
[bing.com/chat](https://bing.com/chat) 	GPT-4/3.5
[italygpt.it](https://italygpt.it/) 	GPT-3.5
[deepai.org](https://deepai.org/chat) 	GPT-3.5 / chat support

**Comment by xplshn** [comment]
I copied the table from GPT4FREE, check those out

**Comment by xplshn** [comment]
https://chat.forefront.ai/
No account required on the first prompts it seems, maybe its infinitely "free"

**Comment by aandrew-me** [comment]
Thanks, I will check them out

**Comment by NormTurtle** [comment]
replicate has some free stuff too 
https://github.com/replicate/zoo

**Comment by aandrew-me** [comment]
Here are many more

https://github.com/xtekky/gpt4free/issues/40
