### ISSUE TITLE
Bai is stucked to only `ONE prompt`

### ISSUE THREAD

**Issue by NormTurtle** [aandrew-me/tgpt#38]
i dont know why this is happening
![image](https://github.com/aandrew-me/tgpt/assets/108952834/0fe0d00e-d2fa-4e60-9118-1bd152ad578d)

in image it shows that -->
1st  ` what is austere`
2nd ` explain this with all jargon for 5 year old "Severe or stern in disposition or appearance; somber and grave"`
but thsi time tgpt think 1st is the prompt ?? how u can see screenshot
and this goes repeat

**Comment by NormTurtle** [comment]
reproducing this issue very hard ! so u can close it for now , i will notify if it happen  again

**Comment by aandrew-me** [comment]
Looks like chatgpt cannot understand you properly. You should ask it properly. And what can I do if chatgpt doesn't understand you? Its not an issue with the program
