### ISSUE TITLE
tgpt --shell on linux 

### ISSUE THREAD

**Issue by Thopow** [aandrew-me/tgpt#39]
The -s/--shell argument run the command with exec. This give problems with the core utilities and crash the process.  
My suggestion is to use "eval" instate of "exec".

**Comment by aandrew-me** [comment]
> This give problems with the core utilities and crash the process.
Please elaborate that

I don't know of eny `eval` function in Go Standard Lib

**Comment by Thopow** [comment]
I'm not so familiar with go but I know bash/sh. 
Your script/program call a shell with the command ```exec "string to execute"``` this make problems when you like to do something like "cd". If your script/program would send ```eval "string to execute"``` the shell will evaluate the string and execute the commands include string like your input to the shell command line.
In bash I would do:
```bash
output="output of gpt"
eval "$output"
```
I hope this help a bit to make it work.

**Comment by aandrew-me** [comment]
tgpt executes commands with `bash -c`

**Comment by Thopow** [comment]
OK, I understand. 
So the problem is that tgpt try to exec the output of the chat. This can be also a problem when there are more the one command is in the chat output.
I checked ```bash -c "string of commands"``` work fine to. I guess based on my error output that your script send ```bash -c "exec 'string of commands'"```  the exec is not needed the -c already do execute the string.

**Comment by Thopow** [comment]
Thanks for your response.
