### ISSUE TITLE
Query returns error 504

### ISSUE THREAD

**Issue by toehold** [aandrew-me/tgpt#40]
I tried to ask something and in return I got this:

Error. Your request is being blocked by the server.
Status Code: 504

**Comment by aandrew-me** [comment]
Are you always getting this error? See if this happens with/without VPN

**Comment by toehold** [comment]
> Are you always getting this error? See if this happens with/without VPN

No, only once or twice!

**Comment by aandrew-me** [comment]
Well then that's not an issue. It could be because of some problems in connectivity
