### ISSUE TITLE
[feature] -f not to remember ID

### ISSUE THREAD

**Issue by ghost** [aandrew-me/tgpt#41]
use `-f` to both forget and not remember in the first place.

**Comment by NormTurtle** [comment]
huh? what

**Comment by NormTurtle** [comment]
please explain in DETAIL

**Comment by aandrew-me** [comment]
To be clear, tgpt doesn't save any history. The previous text in help menu was misleading. It was just the chat id which was being stored. 

However I understand what you are saying. I can add an incognito mode where no chat id will be used

**Comment by aandrew-me** [comment]
It works without ID so no problem. Since -i is already in use I can add -p/--private

**Comment by aandrew-me** [comment]
> Yea, but that would mean, that it immediately forgets everything after each message. I was thinking, that it remembers, until the end of the command.

That's the whole point of it. 

And I don't understand what you mean by 

> I was thinking, that it remembers, until the end of the command.

If you use -p, the command that you executed will be excluded from any chat id. If you need to clear the chat id and start a  new conversation you already have -f

**Comment by aandrew-me** [comment]
I don't understand you

First you say

>  Right now -f just deletes the history. I'm proposing to expand the function to not save history in the first place.

Then you say the completely opposite thing

> What you're saying will cripple the chat function. Do what you want, but i'll not be using -p.

Come on man...

**Comment by aandrew-me** [comment]
> I meant, to drop the memory at the end of the command. Not completely as the command executes.

That sentence makes no sense to me

**Comment by aandrew-me** [comment]
Well that is no different from -p/--private that I was talking about

**Comment by aandrew-me** [comment]
That's why `-f ` is there

**Comment by aandrew-me** [comment]
> you can't use that in advance.

Well then don't
