### ISSUE TITLE
tgpt knowledge of versions

### ISSUE THREAD

**Issue by juren53** [aandrew-me/tgpt#43]
It would be nice of tgpt could report on version history.

$ tgpt 'what is the difference between tgpt 1.6.4 and tgpt 1.6.5?'
what is the difference between tgpt 1.6.4 and tgpt 1.6.5?

Unfortunately, I'm not aware of any specific product called "TGPT" that corresponds to version numbers 1.6.4 and 1.6.5. Could you please provide more information or context about  what you are referring to? That would help me better understand your question and provide a more accurate answer.

**Comment by aandrew-me** [comment]
> $ tgpt 'what is the difference between tgpt 1.6.4 and tgpt 1.6.5?'

Well ChatGPT for certain cannot know that

There are 3 ways I can handle this
1. Hard-code release bodies (Bad idea)
2. Get the release body/bodies from github api and show (Will require me to write a decent amount of code)
3. Take the user to the [releases](https://github.com/aandrew-me/tgpt/releases) where they can check for themselves.  (Most realistic solution for me)

**Comment by aandrew-me** [comment]
Nevermind, no. 2 will be available in next update

**Comment by juren53** [comment]
This was meant as a suggestion.  Not trying to create extra work for you.  You have done a FANTASTIC job with tgpt - - I love it.

Some articles I have read have said ChatGPT is capable of learning from users.  I don''t profess to be an AI developer - - just an active user but the "Pre-train" part of GPT implies there's a way to update and tune the knowledgebase used by ChatGPT.

Just a thought . . .

**Comment by aandrew-me** [comment]
Thanks!

ChatGPT doesn't have permanent memory. So in each conversation you can tell things to it to remember. But it has limits. What developers usually do is say write some message for chatgpt like - "_Your are an expert Therapist"_ and [so on](https://platform.openai.com/docs/guides/gpt/chat-completions-api). So then that information applies for that converstion.

I don't mean that by 2nd option. For chatgpt to be able to answer the question **"what is the difference between tgpt 1.6.4 and tgpt 1.6.5?"** I would need to add a long message to your message everything you ask tgpt something.
So the final prompt would look like -
```
You are tgpt, a terminal chatbot. Your current version is 1.6.5. Changes from the previous version....
What is the difference between tgpt 1.6.4 and tgpt 1.6.5?
```
As you see, this is inefficient and unrealistic.

I have done this by just getting the data from Github [API](https://api.github.com/repos/aandrew-me/tgpt/releases), finding the changelogs and showing them
