### ISSUE TITLE
Arrow keys dont work in interactive mode

### ISSUE THREAD

**Issue by aalhitennf** [aandrew-me/tgpt#49]
[screenshot](https://i.imgur.com/Ofz9jsK.png)

Using arrow keys in interactive mode produces these characters. On multiline mode i can navigate with arrow keys properly.

I'm on linux using hyprland wm (wayland). Keyboard layout fi. I tested with alacritty and UXTerm, same happens with both.

**Comment by NormTurtle** [comment]
can we get EMACS binding? or vi 
oh wait emacs are there !

**Comment by aandrew-me** [comment]
> [screenshot](https://i.imgur.com/Ofz9jsK.png)
> 
> Using arrow keys in interactive mode produces these characters. On multiline mode i can navigate with arrow keys properly.
> 
> I'm on linux using hyprland wm (wayland). Keyboard layout fi. I tested with alacritty and UXTerm, same happens with both.

Arrow keys don't work in interactive mode. Thats why multiline interactive mode was added.
