### ISSUE TITLE
Is tgpt a proxy between client and openai?

### ISSUE THREAD

**Issue by lisp2021** [aandrew-me/tgpt#51]
How do tgpt connect to chatgpt/openai?share many openai keys between all users?

**Comment by aandrew-me** [comment]
As mentioned in the readme, it uses the api of [Bai Chatbot](https://chatbot.theb.ai/). This Bai Chatbot is free and acts like a proxy between client and openai. Here is their repo - https://github.com/Chanzhaoyu/chatgpt-web
