### ISSUE TITLE
Rate limit reached, please try again.

### ISSUE THREAD

**Issue by olinux68** [aandrew-me/tgpt#55]
Comment faire pour ne pas être limité ? ou quels sont les limites ? pourrait-elle afficher dans l'aide ?

**Comment by NormTurtle** [comment]
i was about to open this issue good , u made if FAST

**Comment by NormTurtle** [comment]
okay i add info

**Comment by NormTurtle** [comment]
BAI : https://chatbot.theb.ai
is also showing 
```
速率限制，请重试。
Rate limit reached, please try again.
```
i know this is WON"T situation RN 
🙏 

lets hope for it gets fixed soon
till then i ask BAi support if any, also the community for the help

**Comment by olinux68** [comment]
Pourquoi ne pas utiliser l'api de openia directement ?

**Comment by Day-OS** [comment]
It seems to be back again! ^^

**Comment by sbdaule5** [comment]
You can try `tgpt --forget`

**Comment by Day-OS** [comment]
That was not the case, their API was rate limited, not OP.
