### ISSUE TITLE
About updating in windows

### ISSUE THREAD

**Issue by WiLuX-Source** [aandrew-me/tgpt#58]
Hello, I use this program a lot in my daily life a lot. But why does update function don't work in windows? Some Go binaries don't support it?

**Comment by WiLuX-Source** [comment]
https://github.com/aandrew-me/tgpt/blob/fdb62ccd50d8a250ec82399c9e8dbba2e17279ae/functions.go#L284C62-L284C62

**Comment by aandrew-me** [comment]
On Linux and MacOS the update function executes the install script. Things work differently on Windows.

**Comment by WiLuX-Source** [comment]
I'll see what i can do about it and eventually PR it for you to review it. Thank you for answering.
