### ISSUE TITLE
Getting an API key error.

### ISSUE THREAD

**Issue by riceset** [aandrew-me/tgpt#59]
Whenever I enter an input I am getting the following error:

```
Error: 提供错误的API密钥 | Incorrect API key provided
```

**Comment by Bundy01** [comment]
Hi,
I've had this same error message for a few hours now.

**Comment by xi-pinmping** [comment]
Same here as well

**Comment by Bundy01** [comment]
update with the command `tgpt -u` solved this problem.
or
`curl -sSL https://raw.githubusercontent.com/aandrew-me/tgpt/main/install | bash -s /usr/local/bin`
