### ISSUE TITLE
API Key Error after updating.

### ISSUE THREAD

**Issue by robertovacirca** [aandrew-me/tgpt#60]
API Key Error after updating from Aur. Same problem with older versions. Please, help!
Output: Error: 提供错误的API密钥 | Incorrect API key provided

**Comment by aandrew-me** [comment]
When you get that error, all you can do is wait. Coz its not a problem with the program but rather the backend

**Comment by Bundy01** [comment]
Yesterday's update solved the problem, but now the error persists despite V1.6.12.
@aandrew-me 
Does Open AI revoke keys?

**Comment by aandrew-me** [comment]
> Yesterday's update solved the problem, but now the error persists despite V1.6.12. @aandrew-me Does Open AI revoke keys?

Update has got nothing to do with this. When this site https://chatbot.theb.ai works, the program works

**Comment by Nebb-0** [comment]
> 

I have the same problem but the site works fine
