### ISSUE TITLE
Silent output

### ISSUE THREAD

**Issue by gerardbm** [aandrew-me/tgpt#63]
Hi! Is it possible to add an option to get the only the output, without the "Loading" text?  (Let's say the flag `--silent`).

I'm creating a command in Vim to run tgpt and display the output directly in the buffer.

It is an enhancement.

Thanks in advance!

**Comment by aandrew-me** [comment]
Yes its already in local code, so it should be available soon

**Comment by aandrew-me** [comment]
Ok its available as `-q or --quiet`
