### ISSUE TITLE
Error. Your request is being blocked by the server.

### ISSUE THREAD

**Issue by stpnwf** [aandrew-me/tgpt#65]
Hey, I have been using this tool for a bit, but just now when I tried to use it tonight I've been getting this error:
```
Error. Your request is being blocked by the server.
Status Code: 503
```
I am using the latest version.

**Comment by najibnet** [comment]
the same thing happens to me, i am no longer able to use tgpt, it returns the same error on me.. on several devices i install. Apparently, it is related to its API, maybe it is no longer working anymore..

I need some fixes, please Andrew

**Comment by juren53** [comment]
I too received the same message but after retrying a few moments later, it
is once again operating normally.

**Comment by aandrew-me** [comment]
This is a server side problem, it often happens and you just have to wait and use something else

**Comment by stpnwf** [comment]
Oh awesome, tried it now and it is working again. Closing this issue
