### ISSUE TITLE
The answers are not given properly 

### ISSUE THREAD

**Issue by INDrishitz** [aandrew-me/tgpt#67]
So here i faced a problem with tgpt today and  i dont think it is a 'BAI CHAT ' problem here is a screenshot at the time of the problem 
![image](https://github.com/aandrew-me/tgpt/assets/86766527/c4ad1a27-567d-462d-98dc-0483ea169785)
BTW version is 1.70

**Comment by aandrew-me** [comment]
Interesting. But I think its a bai chat problem. I have never encountered such an issue
