### ISSUE TITLE
I keep getting this message: Error. Your request is being blocked by the server. Status Code: 504

### ISSUE THREAD

**Issue by technicolourdream** [aandrew-me/tgpt#68]
Every time I'm requesting a response from tgpt I keep getting this error.

**Comment by tiborh** [comment]
Same with me: same error.
additional info: I made sure that tgpt is fully updated (tgpt -u)

**Comment by aandrew-me** [comment]
I guess I will have to change the server, it will take time to change a lot of code

**Comment by tiborh** [comment]
The outage seemed to happen at the weekend only. By Monday, it seemed to be
working again.

**Comment by tiborh** [comment]
Today, it is dead again.  (Status Code: 504, blocked by server)

**Comment by aandrew-me** [comment]
yeah as I see, it happens often
