### ISSUE TITLE
Package as OCI Image

### ISSUE THREAD

**Issue by kth8** [aandrew-me/tgpt#69]
I think it would be useful to also package `tgpt` as an OCI image so users running immutable distros who can't install this to `/usr/local/bin` or otherwise don't want to use the install script can alternatively run for example:
```
docker run --rm -t aandrew-me/tgpt "Explain quantum computing in simple terms"
```
or create a shell alias/function to run it:
```
tgpt(){ podman run --rm -it aandrew-me/tgpt $@; }
```

**Comment by kth8** [comment]
A Containerfile could look something like this:
```
FROM alpine
ARG ARCH="${ARCH:-amd64}"
RUN apk add --no-cache gcompat
ADD https://github.com/aandrew-me/tgpt/releases/latest/download/tgpt-linux-${ARCH} /usr/local/bin/tgpt
RUN chmod +x /usr/local/bin/tgpt
ENTRYPOINT ["/usr/local/bin/tgpt"]
```

**Comment by aandrew-me** [comment]
I think thats an interesting idea. Also thanks for providing some examples.
