### ISSUE TITLE
-ash: tgpt: not found 

### ISSUE THREAD

**Issue by xyzaf1** [aandrew-me/tgpt#70]
Hey,
I'm not familiar with Go, so this is probably my fault, please excuse me.

Im on Alpine Linux (latest release), so i ran:
sudo apk add go
go install github.com/aandrew-me/tgpt@latest
tgpt "tell my some random fact"

Then alpine returned: -ash: tgpt: not found 

I also tried sudo go install gith....
Did not work as well

Have a nice one
xyzaf

**Comment by xyzaf1** [comment]
u have to go into /go/bin and run ./tgpt :)

**Comment by aandrew-me** [comment]
If you install with go then you need to add /go/bin to PATH
