### ISSUE TITLE
Support prompt from file / stdin

### ISSUE THREAD

**Issue by johnd0e** [aandrew-me/tgpt#71]
I miss that feature very much)

**Comment by NormTurtle** [comment]
when it there :) ?

**Comment by johnd0e** [comment]
What do you mean?

**Comment by aandrew-me** [comment]
I'll try

**Comment by aandrew-me** [comment]
Ok I added it, expect it in next update. However keep in mind that it won't work with arguments.

You can use it like this
`cat test.txt | tgpt`
`cat "hi" | tgpt`
and it will work

**Comment by aandrew-me** [comment]
I noticed one limitation, stdin is just one line. Reading multiple lines from stdin is a whole different story

**Comment by johnd0e** [comment]
> Reading multiple lines from stdin is a whole different story

Too bad.
But you can read from general file, right?
It would be helpful, for example to give a file to analyse, or some context (previous conversation).

> However keep in mind that it won't work with arguments.

I would be convenient to have possibility to use both simultaneously.

**Comment by aandrew-me** [comment]
Its possible. You can't upload the file, instead the program will have to read it and then send the text. So if its just a text file, it won't be hard, but if it's a PDF....
