### ISSUE TITLE
tgpt is not working anymore 

### ISSUE THREAD

**Issue by abdulbadii** [aandrew-me/tgpt#72]
Why this Linux shell chatgpt is not working anymore e.g.
```

$ tgpt 'Where is the Linux OS drivers location '
Where is the Linux OS drivers location

```
so confused

**Comment by aandrew-me** [comment]
Oh no, looks like they closed down https://chatbot.theb.ai/ and moved to https://beta.theb.ai/

**Comment by abdulbadii** [comment]
How's solution to restore to work?

**Comment by aandrew-me** [comment]
You just have to wait and hope
I have to find a way...

**Comment by pitsi** [comment]
Same thing here, on amd64 (debian unstable) and arm64 (debian 11), it returns 3 empty lines..
```
$ tgpt-linux-amd64 "what is 2 times 3"
what is 2 times 3



```
My... jinx friend is to blame for that! I shouldn't have shown him tgpt :D

**Comment by tfuchs1987** [comment]
please find a way 🙏 and thanks so much in advance

**Comment by baby-joe** [comment]
Glad to see I'm not the only one with this issue. I wonder if it's the move from 3.5 to 4? Maybe there's something interfering?

**Comment by ScriptAlchemist** [comment]
honestly someone is paying for the heat being generated from the queries. It may have to move to something that requires us to use our own api keys. Especially as more and more people find this tool.

It would be awesome if it could still access the free versions somehow. So I'm rooting for a free setup.

**Comment by Bundy01** [comment]
Hi,

I created an account on the new site to see how to authenticate.
The big problem is that they've made requests chargeable (credit card and other $).

@aandrew-me: I don't want to be pessimistic, but I think it's going to be complicated for you :(

**Comment by abdulbadii** [comment]
As we see many in-shell chatgpts else works with demanding a free API key
So why don't simply let this work with behaving such

**Comment by Bundy01** [comment]
I discovered a site that uses different AIs.

There must be others but this one uses multiple LLMs including Vicuna-33b which is good.

GPT-3.5 has also become payware :(

If it helps, here's the link: https://chat.lmsys.org/

**Comment by aandrew-me** [comment]
> As we see many in-shell chatgpts else works with demanding a free API key So why don't simply let this work with behaving such

Those api keys are not free. They expire. And using api key defeats the whole purpose of this program. There are already many programs out there which you can use with api keys

**Comment by aandrew-me** [comment]
> Hi,
> 
> I created an account on the new site to see how to authenticate. The big problem is that they've made requests chargeable (credit card and other $).
> 
> @aandrew-me: I don't want to be pessimistic, but I think it's going to be complicated for you :(
> 
> Can I make requests from bing with Edge UA with tgpt?

I don't necessarily have to use that site. 

And I couldn't understand your question

**Comment by aandrew-me** [comment]
> I discovered a site that uses different AIs.
> 
> There must be others but this one uses multiple LLMs including Vicuna-33b which is good.
> 
> GPT-3.5 has also become payware :(
> 
> If it helps, here's the link: https://chat.lmsys.org/

Thanks but as I see, its slow.

**Comment by muhiris** [comment]
If anyone comes across a free AI NLP endpoint, sharing it would be extremely helpful for the progress of these projects. I used to work on a project called [wgpt](https://github.com/muhiris/wgpt), which was a ChatGPT running in the terminal. You can show support for [this repository](https://github.com/aandrew-me/tgpt) and [wgpt](https://github.com/muhiris/wgpt) by giving them stars. These actions will increase the visibility of the issue and might attract someone with a solution for a free API key.

**Comment by jyash8** [comment]
I found one very similar to Bai chat please try it
https://chat.chatgptdemo.net/
It also does not require login.

**Comment by Bundy01** [comment]
@aandrew-me: with my question, I was thinking of using tgpt with Bing's AI, but I think the queries are limited.

Otherwise, I found two other sites that use GPT-3. The @jyash8 link doesn't work for me because of an Unbound blacklist, "you're using an adblocker ..."

https://www.chatgptdownload.org/chatgpt/
https://aichatonline.org/chat/

I hope they can be used with tgpt.

**Comment by muhiris** [comment]
Thank you, @Bundy01 and @aandrew-me, for your valuable assistance in resolving the terminal AI issue. I added you in special thanks section and I have successfully created a scraper in Node.js, which functions well but a bit slow. You can find the code for it [here](https://github.com/muhiris/wgpt). As much as I would like to contribute to the GO version, my expertise lies in Node.js, and I am not well-versed in GO.

To run the scraper, you can install the package using the following command:
```
npm i -g wgpt
```

After installation, you can use it with the commands:
```
wgpt hello world
```
or
```
wgpt "Hello world"
```

Though it may not be as feature-rich as tgpt, any support and stars you provide would be highly appreciated. The tool also includes an `--timeout` tag, allowing you to adjust the waiting time. If you have a good internet connection, you can decrease the timeout from 7 to 5 seconds. For more details on available options, you can refer to `wgpt --help`.

@aandrew-me , I kindly request you to check out this project, and I hope you can find the time to get tgpt working again. Your contribution would be highly beneficial.

**Comment by aandrew-me** [comment]
> Thank you, @Bundy01 and @aandrew-me, for your valuable assistance in resolving the terminal AI issue. I added you in special thanks section and I have successfully created a scraper in Node.js, which functions well but a bit slow. You can find the code for it [here](https://github.com/muhiris/wgpt). As much as I would like to contribute to the GO version, my expertise lies in Node.js, and I am not well-versed in GO.
> 
> To run the scraper, you can install the package using the following command:
> 
> ```
> npm i -g wgpt
> ```
> 
> After installation, you can use it with the commands:
> 
> ```
> wgpt hello world
> ```
> 
> or
> 
> ```
> wgpt "Hello world"
> ```
> 
> Though it may not be as feature-rich as tgpt, any support and stars you provide would be highly appreciated. The tool also includes an `--timeout` tag, allowing you to adjust the waiting time. If you have a good internet connection, you can decrease the timeout from 7 to 5 seconds. For more details on available options, you can refer to `wgpt --help`.
> 
> @aandrew-me , I kindly request you to check out this project, and I hope you can find the time to get tgpt working again. Your contribution would be highly beneficial.

I see that you are using chromium for that. Making it this way is making your program slower and inefficient. Instead you can just make a POST request to the API with `axios`

**Comment by muhiris** [comment]
I tried that way but as their is no end point to send the request. The chat option is within a webpage. So axios POST request give errors but I'm not an expert maybe it's possible that way. 

Also thanks for guiding me. I'll try implementing with axios again

**Comment by aandrew-me** [comment]
> I tried that way but as their is no end point to send the request. The chat option is within a webpage. So axios POST request give errors but I'm not an expert maybe it's possible that way.
> 
> Also thanks for guiding me. I'll try implementing with axios again

Endpoint is always there, you need to intercept your browser request with some MITM tool like mitmproxy, burpsuite.

**Comment by ScriptAlchemist** [comment]
> Thank you, @Bundy01 and @aandrew-me, for your valuable assistance in resolving the terminal AI issue. I added you in special thanks section and I have successfully created a scraper in Node.js, which functions well but a bit slow. You can find the code for it [here](https://github.com/muhiris/wgpt). As much as I would like to contribute to the GO version, my expertise lies in Node.js, and I am not well-versed in GO.
> 
> To run the scraper, you can install the package using the following command:
> 
> ```
> npm i -g wgpt
> ```
> 
> After installation, you can use it with the commands:
> 
> ```
> wgpt hello world
> ```
> 
> or
> 
> ```
> wgpt "Hello world"
> ```
> 
> Though it may not be as feature-rich as tgpt, any support and stars you provide would be highly appreciated. The tool also includes an `--timeout` tag, allowing you to adjust the waiting time. If you have a good internet connection, you can decrease the timeout from 7 to 5 seconds. For more details on available options, you can refer to `wgpt --help`.
> 
> @aandrew-me , I kindly request you to check out this project, and I hope you can find the time to get tgpt working again. Your contribution would be highly beneficial.

This idea is interesting. I'm almost tempted to take this idea and instead of using https://aichatonline.org/. Setting it up to login to the normal chat.openai with a usename and password for my own account

**Comment by muhiris** [comment]
> Endpoint is always there, you need to intercept your browser request with some MITM tool like mitmproxy, burpsuite.

I really don't know what all these things are, I'm a beginner but just would love to see TGPT live again because this inspired me to make my own terminal based apps.

**Comment by muhiris** [comment]
> This idea is interesting. I'm almost tempted to take this idea and instead of using https://aichatonline.org/. Setting it up to login to the normal chat.openai with a usename and password for my own account

If you ever make it or contribute to this base project that would be super cool. I'll love to install that thing.

**Comment by entrider** [comment]
There is `https://free.churchless.tech/v1/chat/completions`
It is identical to the official API except free.

**Comment by muhiris** [comment]
Thanks @entrider !

@aandrew-me, Can you update `getData` function in your `function.go` so tgpt start working again. You can use this code to update. This code uses `free.churchless` API

`
package main
import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
)

func main() {
	url := "https://free.churchless.tech/v1/chat/completions"

	// Take user input for content
	reader := bufio.NewReader(os.Stdin)
	fmt.Print("Enter your input: ")
	input, _ := reader.ReadString('\n')
	input = input[:len(input)-1] // Remove the newline character

	// Prepare the request body
	requestBody := map[string]interface{}{
		"messages": []map[string]string{
			{
				"role":    "user",
				"content": input,
			},
		},
	}
	requestBodyJSON, _ := json.Marshal(requestBody)

	// Make the POST request
	resp, err := http.Post(url, "application/json", bytes.NewBuffer(requestBodyJSON))
	if err != nil {
		fmt.Println("Error:", err)
		return
	}
	defer resp.Body.Close()

	// Read the response body
	responseBody, _ := ioutil.ReadAll(resp.Body)

	// Unmarshal the response JSON
	var jsonResponse map[string]interface{}
	err = json.Unmarshal(responseBody, &jsonResponse)
	if err != nil {
		fmt.Println("Error:", err)
		return
	}

	// Extract the content value
	choices := jsonResponse["choices"].([]interface{})
	if len(choices) > 0 {
		message := choices[0].(map[string]interface{})["message"].(map[string]interface{})
		content := message["content"].(string)
		fmt.Println("Assistant's response:", content)
	} else {
		fmt.Println("No response content found.")
	}
}
`

**Comment by muhiris** [comment]
![image](https://github.com/aandrew-me/tgpt/assets/80543033/aeafe20d-88fc-4935-8ef1-551ca713f263)

**Comment by aandrew-me** [comment]
Thanks for the URL. And Muhiris, I appreciate it, however I am doing in a different way since I also want streamed responses. Its already working, so an update should be available soon

**Comment by aandrew-me** [comment]
Update has been released. If this API goes down, I think it will be easier next time because if its identical to original API, I would only need to change the URL of the API

**Comment by tfuchs1987** [comment]
thank you so much! also the -q attribute for quiet is so usefull ❤

**Comment by NormTurtle** [comment]
@aandrew-me 
i have found a full repo of FREE-API, please use if any BREAK-point occurred.
https://github.com/NovaOSS/free-ai-apis
