### ISSUE TITLE
Issue with latest release

### ISSUE THREAD

**Issue by Cody-Learner** [aandrew-me/tgpt#75]
I'm running this on Arch Linux: https://aur.archlinux.org/packages/tgpt-bin

I think there are possibly some issues with this release. I've been running the previous two versions without this intermittent error in an nspawn container on this system.

╭─ Bot
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getData({0xc000110580, 0x159}, {0x1?, 0x854cbb?}, {0x0?, 0x0?}, 0x1)
    /home/runner/work/tgpt/tgpt/functions.go:120 +0x1229
main.main()
    /home/runner/work/tgpt/tgpt/main.go:159 +0x1a94

Strangely, this seems to come up as a result of asking difficult questions, and returned me to a bash prompt following this output.
In past versions, it would just end the tgpt session, returning me to my regular bash prompt with no output.

**Comment by aandrew-me** [comment]
Thanks for letting me know. I had to change to a new API for this release, so everything is new and different. It should be fixed

**Comment by skhelishalnev** [comment]
+1  Version: `tgpt 1.7.1`

```go
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getData({0x16d8f544d, 0x38}, {0x1028da278?, 0x10284206e?}, {0x0?, 0x0?}, 0x0)
	/home/runner/work/tgpt/tgpt/functions.go:120 +0xed0
main.main()
	/home/runner/work/tgpt/tgpt/main.go:225 +0x15cc
```

**Comment by aandrew-me** [comment]
Looks like the API has stopped working :/

**Comment by filfai** [comment]
I have the same problem :/

**Comment by skhelishalnev** [comment]
Yeah, I twitted the @acheong08, he was blocking the access to find out who is abusing the API...
His last suggestion was to use group specific bearer token. but it now returns 401...
```shell
#request
curl -X POST -H "Content-Type: application/json" -H 'Authorization: Bearer TwitterFollowers' -d '{"model":"gpt-3.5-turbo","messages":[{"role":"user","content":"hello world"}],"stream":true}' https://free.churchless.tech/v1/chat/completions

#return
{"error":{"code":"error","message":{"message":"Unauthorized - Access token is missing"},"param":null,"type":"401 Unauthorized"}}

```

**Comment by skhelishalnev** [comment]
So much for "open" AI ...

**Comment by aandrew-me** [comment]
Looks like its working again

**Comment by stpnwf** [comment]
Hey, I don't really understand a lot of this, so I'm unsure if it is helpful, but I ran into this, and I think it is...

www.perplexity.ai/


Also, what this guy is talking about could be useful, maybe?

https://nostr.band/note1lgzzy4dey6g2w03vq5nf8c005h8de7xeezw8r0lt3hkn8zxc5ngskkex6u

https://nostr.band/note1rtkrkwdq0k42pp26v22ltjdvxjf6umdkqzq4cfxgeutustfzzckq26djvy

**Comment by aandrew-me** [comment]
> Hey, I don't really understand a lot of this, so I'm unsure if it is helpful, but I ran into this, and I think it is...
> 
> [www.perplexity.ai/](http://www.perplexity.ai/)
> 
> Also, what this guy is talking about could be useful, maybe?
> 
> https://nostr.band/note1lgzzy4dey6g2w03vq5nf8c005h8de7xeezw8r0lt3hkn8zxc5ngskkex6u
> 
> https://nostr.band/note1rtkrkwdq0k42pp26v22ltjdvxjf6umdkqzq4cfxgeutustfzzckq26djvy

Good stuff in general but can't really be used for this project.

**Comment by Cody-Learner** [comment]
Hey aandrew-me, not sure you've had time to look into my issue above, and I don't know go, but thought perhaps asking chat GPT would be interesting. Here's the meat of the reply below. Interested in your thoughts...


> Here's the relevant section of your code where the error seems to be happening:
> 
> ```go
> splitLine := strings.Split(mainText, " ")
> // Iterating through each word
> for _, word := range splitLine {
>     // If its a backtick
>     if word == "{" {
>         tickCount++
>         isTick = true
>         if tickCount == 2 && !previousWasTick {
>             tickCount = 0
>         } else if tickCount == 6 {
>             tickCount = 0
>         }
>         previousWasTick = true
>         isGreen = false
>         isCode = false
>     } else {
>         isTick = false
>         // If its a normal word
>         if tickCount == 1 {
>             isGreen = true
>         } else if tickCount == 3 {
>             isCode = true
>         }
>         previousWasTick = false
>     }
>     // ...
> }
> ```
> 
> The issue might be caused by an incorrect assumption about the structure of the splitLine array. It seems like you are expecting certain patterns (like
>  backticks) within the splitLine, but the actual content of splitLine might not match your expectations, leading to the index out of range error.
> 
> You need to ensure that you're properly splitting the mainText string into words and then iterating through each word as intended. It's important to handle
>  edge cases and unexpected input to avoid index out of range errors.
> 
> To diagnose the issue further, you should consider checking the length of the splitLine array before accessing specific indices. You can also add print
>  statements or debugging tools to see the content of the splitLine array and the values of relevant variables during runtime.
> 
> Additionally, you have an empty line and a variable declaration (var obj = {}) on lines 99 and 100 that seem incomplete or incorrect. You should ensure
>  that you are initializing variables correctly with the appropriate data types.
> 
> Please review this section of your code and make sure that you are handling string splitting and array access correctly to avoid the index out of range error
> .
>

**Comment by aandrew-me** [comment]
@Cody-Learner Hello the issue occurs because sometimes the API responds with an error. I have improved error handling, so it should be better in next release
