### ISSUE TITLE
Unabel to install tgpt on ubuntu 22.04

### ISSUE THREAD

**Issue by vk0942** [aandrew-me/tgpt#76]
I ran the command as given in the ReadMe.md file "curl -sSL https://raw.githubusercontent.com/aandrew-me/tgpt/main/install | bash -s /usr/local/bin" but it is giving the error message mv: cannot stat '/tmp/tgpt': No such file or directory
below i have copy pasted the while process.
Please resolve this issue.

v@nsh:~$ curl -sSL https://raw.githubusercontent.com/aandrew-me/tgpt/main/install | bash -s /usr/local/bin
Download location: /usr/local/bin
Operating System: linux
Processor Architecture: amd64

Downloading...

######################################################################## 100.0%
[sudo] password for v: 
mv: cannot stat '/tmp/tgpt': No such file or directory

**Comment by aandrew-me** [comment]
I remember someone else encountering a similar problem. This is a problem on your side, I think it has got to do with how you configured your /tmp directory. Did you configure your /tmp directory to be stored in RAM?

**Comment by aandrew-me** [comment]
One simple solution is to download the executable from releases and put it in `/use/local/bin` and rename it however you want.

**Comment by vk0942** [comment]
> I remember someone else encountering a similar problem. This is a problem on your side, I think it has got to do with how you configured your /tmp directory. Did you configure your /tmp directory to be stored in RAM?

Yes I don't have a tmp.folder in usr/local/bin/ so should I make one there and then try to reinstall?

**Comment by vk0942** [comment]
> One simple solution is to download the executable from releases and put it in `/usr/local/bin` and rename it however you want.

Ok I will try then after downloading how should I install it?
