### ISSUE TITLE
tgpt Not answering Questinos

### ISSUE THREAD

**Issue by vk0942** [aandrew-me/tgpt#77]
### tgpt not answering queries

v@nsh:~$ cd usr/local/bin
bash: cd: usr/local/bin: No such file or directory
v@nsh:~$ cd /usr/local/bin/
v@nsh:/usr/local/bin$ ls
nodemon  tgpt
v@nsh:/usr/local/bin$ ./tgpt
You have to write some text
Example: tgpt "Explain quantum computing in simple terms"
v@nsh:/usr/local/bin$ tgpt "Explain quantum computing"
Explain quantum computing

v@nsh:/usr/local/bin$ tgpt "what is 2+2"
what is 2+2

v@nsh:/usr/local/bin$ 
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
i downloaded the tgpt-linux-amd64 for my Ubuntu 22.04  x86_64 system
then renamed it to tgpt with mv and then chnod +x tgpt
After this it should run right?

**Comment by aandrew-me** [comment]
Yes it should be working fine. I hope you downloaded the latest version - https://github.com/aandrew-me/tgpt/releases/download/v1.7.1/tgpt-linux-amd64

**Comment by vk0942** [comment]
> Yes it should be working fine. I hope you downloaded the latest version - https://github.com/aandrew-me/tgpt/releases/download/v1.7.1/tgpt-linux-amd64

Great man it worked now i might be doing some mistake earlier some cool stuff you have made i also want to learn such things and build such awesome stuff from where did you learned all these things

**Comment by aandrew-me** [comment]
> > Yes it should be working fine. I hope you downloaded the latest version - https://github.com/aandrew-me/tgpt/releases/download/v1.7.1/tgpt-linux-amd64
> 
> Great man it worked now i might be doing some mistake earlier some cool stuff you have made i also want to learn such things and build such awesome stuff from where did you learned all these things

Good that its working. There are many websites and Youtube channels with lots of tutorials. So you can learn for free. You can message me on telegram and I can then share a lot of learning resources - t.me/aandrew_me
