### ISSUE TITLE
Change cmd code output color

### ISSUE THREAD

**Issue by mistersenpai** [aandrew-me/tgpt#78]
I was wondering if it's possible at all to change the color of the outputted code from tgpt? At the moment it is green and black, but if I wanted to change the colors how would we go abouts this? Couldn't find anything in the README

**Comment by aandrew-me** [comment]
Yeah because there is no such option.

**Comment by evilsh3ll** [comment]
> I was wondering if it's possible at all to change the color of the outputted code from tgpt? At the moment it is green and black, but if I wanted to change the colors how would we go abouts this? Couldn't find anything in the README

if it can be useful you can use `highlight -O ansi --syntax YOUR-LANGUAGE`
![image](https://github.com/aandrew-me/tgpt/assets/63223659/f66421cd-4a70-455f-afa3-8ec293e43595)
and you can also setup an alias like `alias colorcode="highlight -O ansi --syntax"` to pipe your output like this `tgpt -c "write a simple helloword in 3-line C code" | codecolor c`
