### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Muzammil-4u** [aandrew-me/tgpt#80]
**Some error has occurred. Please try again**
getting this error when i type something to search 
operating system arch linux 
downloaded from paru

**Comment by Iliageorgiev** [comment]
Same here , 90% of tries ends with the same error. Before 2-3 days was fine i mean same error appeared 10% of the time , but now is almost unusable .

**Comment by nusantaraja** [comment]
Me too
appears error like this --> "Some error has occurred. Please try again"

**Comment by drblog** [comment]
On ubuntu 18.04.6:
Some error has occurred. Please try again

On ubuntu 20.04.6:
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getData({0x7ffd2d83e753, 0x4}, {0x3?, 0x854cbb?}, {0x0?, 0x0?}, 0x0)
        /home/runner/work/tgpt/tgpt/functions.go:120 +0x1229
main.main()
        /home/runner/work/tgpt/tgpt/main.go:225 +0x1665

**Comment by Iliageorgiev** [comment]
I think i found the problem
https://free.churchless.tech/v1/chat/completions 
404 page not found

**Comment by Bundy01** [comment]
@aandrew-me 
did you see this comment (https://github.com/aandrew-me/tgpt/issues/72#issuecomment-1696254408)?

If GPT-4 can be used, that would be a great bonus.
Regards.

**Comment by aandrew-me** [comment]
That api is down and that repo in #72 has several apis but all require api keys. However I have found a way so be patient, update is coming soon!

**Comment by aandrew-me** [comment]
Update and enjoy

**Comment by grugnoymeme** [comment]
same error now :(

**Comment by grugnoymeme** [comment]
on macOS

**Comment by aandrew-me** [comment]
Update is coming again

**Comment by valenchu** [comment]
I have the same error today 8 september 2023

![image](https://github.com/aandrew-me/tgpt/assets/20959371/b9509dd8-5632-4ff9-abb4-49ab27ba0e1d)
