### ISSUE TITLE
Termux support??

### ISSUE THREAD

**Issue by rexackermann** [aandrew-me/tgpt#83]
Can you add termux support?
termux can't access /tmp and /usr/local/bin without root.
So a few lines in install might help
And maybe the architecture would be a thing?
This might help :
```
if [[ $(uname -a | awk '{print $14}') == "Android" ]]
        then
             it's termux !
fi
```

**Comment by aandrew-me** [comment]
I had tried, I can't build executables for Termux.

If you want to use in termux you have to install `go` and then install with `go`
```
go install github.com/aandrew-me/tgpt@latest
```

Then it will download and compile the program. On Linux its usually in `~/go/bin`,  you can find where it is on android, you will just have to add that folder to $PATH
