### ISSUE TITLE
What's the current strategy here?

### ISSUE THREAD

**Issue by Destroy666x** [aandrew-me/tgpt#84]
I don't think changing API keys (https://github.com/aandrew-me/tgpt/commit/3f42643b7fe4cc6d4e916597de15118ecb47bb97#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R36) will last long. Where do these keys come from in the 1st place?

**Comment by aandrew-me** [comment]
https://youtu.be/oenlOvLPYDo?si=sWRLwwZ6X3w4L4hG

**Comment by Free-Radical** [comment]
Firstly, awesome work! 
Q: Could a similar tactic be used to access MS  bing (GPT-4) ?
Although I've only seen Bing running in MS Edge and IOS Bing app.

**Comment by aandrew-me** [comment]
> Firstly, awesome work! Q: Could a similar tactic be used to access MS bing (GPT-4) ? Although I've only seen Bing running in MS Edge and IOS Bing app.

MS bing doesn't have an API, however some people have attempted to reverse engineer. Search and you may find something on github
