### ISSUE TITLE
"Some error has occurred. Please try again"

### ISSUE THREAD

**Issue by liata1975** [aandrew-me/tgpt#85]
I got this error message: "Some error has occurred. Please try again" and had no clue what happened. After some try and error, I realized it was because I accidentally put a prompt over 4k token. After trimming down prompt size, the error went away. 
FWIW, It might be good to add some warning about token size?

**Comment by aindriu80** [comment]
I'm having the same issue but with any input:-

`tgpt "what is the interent"      

Some error has occurred. Please try again

`

I didn't ask that many questions, it worked yesterday but not today

**Comment by aandrew-me** [comment]
> I got this error message: "Some error has occurred. Please try again" and had no clue what happened. After some try and error, I realized it was because I accidentally put a prompt over 4k token. After trimming down prompt size, the error went away. FWIW, It might be good to add some warning about token size?

Yes I agree

**Comment by aandrew-me** [comment]
> I'm having the same issue but with any input:-
> 
> > tgpt "what is the internet"
> > Some error has occurred. Please try again
> 
> I didn't ask that many questions, it worked yesterday but not today

Wait, update is coming

**Comment by aindriu80** [comment]
> The internet is a global network of computers and other digital devices connected together,
 which allows for the transfer and sharing of information. It enables people to access
 websites, send and receive emails, participate in online platforms and social media, conduct
 research, shop online, and much more. The internet is facilitated by a system of protocols
 and technologies, such as TCP/IP (Transmission Control Protocol/Internet Protocol) and DNS (
Domain Name System). Through the internet, individuals and businesses can connect with each
 other and the world, accessing a vast amount of information and resources.


Working for me with 1.7.6 :) thanks! 

Just a note - I couldn't update with` sudo tgpt -u`  there was a permissions problem even with sudo, I had to run the install script.

**Comment by onurcangnc** [comment]
The issue continue ,so please check again. Especially for command tgpt --interactive. I updated.

**Comment by aandrew-me** [comment]
yes wait for next update and I will find a better way so that you don't have to update each time

**Comment by aandrew-me** [comment]
> I got this error message: "Some error has occurred. Please try again" and had no clue what happened. After some try and error, I realized it was because I accidentally put a prompt over 4k token. After trimming down prompt size, the error went away. FWIW, It might be good to add some warning about token size?

Will be in next update
