### ISSUE TITLE
prompt on stdin

### ISSUE THREAD

**Issue by solsticedhiver** [aandrew-me/tgpt#86]
I can use stdin to pipe my prompt like:

    echo "What is 42?" | tgpt

but I can't use it with `-w` like

    cat my_very_long_prompt.txt | tgpt -w

It gives the "error":

    You need to provide some text
    Example: tgpt -w "What is encryption?"

**Comment by vimnux** [comment]
Basic script that should fix your problem:

`#!/bin/bash

my_very_long_prompt="Answer the following queston as good as you can but use only emoji:"

echo -e "\nHello! My name is GPT-3, how can I assist you today?"

while true; do
  echo -ne "\n> "
  read -r user_input
  if [ -z "$user_input" ] || [ "$user_input" = exit ]; then
    exit 0
  fi
  tgpt -w  "\"${my_very_long_prompt} ${user_input}"\"
done
`
Give it a name,  change my_very_long_prompt to  your_very_long_prompt and make it executable.

![tgpt-github](https://github.com/aandrew-me/tgpt/assets/137954021/0209f3c5-f29c-416a-9b1e-137efe7fc184)

**Comment by johnd0e** [comment]
> Basic script that should fix your problem:

I still hope that one day this can be implemented in tgpt itself.

**Comment by solsticedhiver** [comment]
Just by looking at the code (not a go expert here), I can smell that it is just a matter of rewriting the argument parsing and call the correct method at the right time.

**Comment by aandrew-me** [comment]
> Just by looking at the code (not a go expert here), I can smell that it is just a matter of rewriting the argument parsing and call the correct method at the right time.

I think you're right (not a go expert either)

**Comment by aandrew-me** [comment]
Will be available in next update
