### ISSUE TITLE
Some error has occurred. Check your internet connection.

### ISSUE THREAD

**Issue by ivkraft** [aandrew-me/tgpt#87]
>tgpt "How are you?"           
Some error has occurred. Check your internet connection.

Error: Post "https://free.churchless.tech/v1/chat/completions": dial tcp 143.244.220.150:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by johnd0e** [comment]
Just update to the latest version
