### ISSUE TITLE
Some error has occurred. Please try again

### ISSUE THREAD

**Issue by sinuso** [aandrew-me/tgpt#90]
For a few hours now I have always been getting this response.

`:~$ tgpt "hello"`
`Some error has occurred. Please try again`

**Comment by aandrew-me** [comment]
yes I gotta add a better way to change keys

**Comment by sinuso** [comment]
> yes I gotta add a better way to change keys

Thanks for the response and your work
I have seen that the main.go has been updated but not the version.txt.

**Comment by aandrew-me** [comment]
Update

**Comment by sinuso** [comment]
It works now thanks
