### ISSUE TITLE
new key already dead?  :(

### ISSUE THREAD

**Issue by Free-Radical** [aandrew-me/tgpt#91]
```
❯ tgpt -s "howto install python requirement.txt"
Some error has occurred. Please try again
```

I did direct api debugging and actual error:

`HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/chat/completions`

PS I know python happy to help, but not sure how. Lemme know.

**Comment by sinuso** [comment]
I have the same problem.
To update the key, it occurs to me that aandrew-me adds a separate file with the key. Every X time tgpt should check if there is an update to the key.

This would save having to wait for the code to be updated and having to update tgpt manually.

**Comment by sinuso** [comment]
I have the same problem.

To update the key, it occurs to me that aandrew-me adds a separate file with the key. Every X time tgpt should check if there is an update to the key (This would save having to wait for the code to be updated and having to update tgpt manually).

Another option, and I think the best, would be for each person to generate a key. I don't know if it can be done or how to do it. (This would help with the 429 error).

Instead of showing the error `Some error has occurred. Please try again` a message similar to this might appear.

`❯ tgpt "hi"`
`The key is no longer functional. Please wait for it to update or enter one manually.`
`You want to add a y/n: Y`
`Enter the new key: ****************`

**Comment by aandrew-me** [comment]
> I have the same problem.
> 
> To update the key, it occurs to me that aandrew-me adds a separate file with the key. Every X time tgpt should check if there is an update to the key (This would save having to wait for the code to be updated and having to update tgpt manually).
> 
> Another option, and I think the best, would be for each person to generate a key. I don't know if it can be done or how to do it. (This would help with the 429 error).
> 
> Instead of showing the error `Some error has occurred. Please try again` a message similar to this might appear.
> 
> `❯ tgpt "hi"` `The key is no longer functional. Please wait for it to update or enter one manually.` `You want to add a new y/n: Y` `Enter the new key: ****************`

Yes I added code so that tgpt checks for a new key of there is such an error. That should be available in the next update

**Comment by aandrew-me** [comment]
Ok the update is available. Also let me know if the key gets automatically updated next time it stops working

**Comment by Free-Radical** [comment]
Working! Thanks!

**Comment by HarshalRathore** [comment]
@aandrew-me Hi bro First thanks for this fantastic tool, but I want to ask are you using your own API key for tgpt and bearing the charges? If so then I fail to understand why you may be offering to do this free of cost for others. I haven't read the source code so I don't know if you are doing something entirely different so I could only come to the conclusion that you might be using your own API keys for this tool to work.

**Comment by aandrew-me** [comment]
> @aandrew-me Hi bro First thanks for this fantastic tool, but I want to ask are you using your own API key for tgpt and bearing the charges? If so then I fail to understand why you may be offering to do this free of cost for others. I haven't read the source code so I don't know if you are doing something entirely different so I could only come to the conclusion that you might be using your own API keys for this tool to work.

Hello. This
https://youtu.be/oenlOvLPYDo?si=iNb5RuwzJl2p7rPr

**Comment by aandrew-me** [comment]
> > > @aandrew-me Hi bro First thanks for this fantastic tool, but I want to ask are you using your own API key for tgpt and bearing the charges? If so then I fail to understand why you may be offering to do this free of cost for others. I haven't read the source code so I don't know if you are doing something entirely different so I could only come to the conclusion that you might be using your own API keys for this tool to work.
> > 
> > 
> > Hello. This https://youtu.be/oenlOvLPYDo?si=iNb5RuwzJl2p7rPr
> 
> Wait... so you are 'harvesting' keys by reverse-engineering random apps you find? Pretty sure that's illegal. Please tell me I got it all wrong.

I didn't even have to do reversing. Anything that is client side is public, so all I had to do was check the requests made by apps

**Comment by aandrew-me** [comment]
If you feel ethically concerned, you may use your own api keys instead ;)

**Comment by NormTurtle** [comment]
@aandrew-me can we use PALM? its a FREE ai-Chatbot like thing from google
https://makersuite.google.com/app/

**Comment by aandrew-me** [comment]
> @aandrew-me can we use PALM? its a FREE ai-Chatbot like thing from google https://makersuite.google.com/app/

![image](https://github.com/aandrew-me/tgpt/assets/66430340/80e4d53a-a770-48da-abb0-2ed16d413776)

**Comment by aandrew-me** [comment]
> > > @aandrew-me Hi bro First thanks for this fantastic tool, but I want to ask are you using your own API key for tgpt and bearing the charges? If so then I fail to understand why you may be offering to do this free of cost for others. I haven't read the source code so I don't know if you are doing something entirely different so I could only come to the conclusion that you might be using your own API keys for this tool to work.
> > 
> > 
> > Hello. This https://youtu.be/oenlOvLPYDo?si=iNb5RuwzJl2p7rPr
> 
> Well I followed the video but I could not find the request end point for the API can you tell where did you find it?

Its easier to find by just interceptiong the requests.
