### ISSUE TITLE
TGPT has no memory

### ISSUE THREAD

**Issue by Alasdan** [aandrew-me/tgpt#94]
Chatgpt from browser can remember what you said before during a chat. For example, if you said "They call me John" first, it can perfectly answer "What's my name?" afterwards. TGPT fails to do so.

**Comment by aandrew-me** [comment]
Yes I didn't get the time to add support for this after migrating to new api. I will once I get time

**Comment by catafest** [comment]
```
tgpt -m " "

Press Tab to submit and Ctrl + C to exit.

┃ "They call me John"
┃ "What's my name?"
┃
┃
┃

╭─ Bot
Your name is John.```

**Comment by xplshn** [comment]
```
anto@beef:~$ tgpt "Remember, my faourite color is Aqua"
Remember, my faourite color is Aqua

Thank you for reminding me! I will make sure to remember that your favorite
 color is Aqua.

anto@beef:~$ tgpt "do you remember what color I told you is my favourite color?"
do you remember what color I told you is my favourite color?

I apologize, but I cannot remember specific details about individual users
 unless they are provided in the current conversation.
```

**Comment by aandrew-me** [comment]
Chatgpt cannot remember chat history. How it works is the chat history is stored locally and each time a new query is made, the whole chat history is included with it.

**Comment by squont** [comment]
Every question submitted in interactive mode (-i) seems to be a new query without history. Is this intended behavoiur? 
```
>tgpt -i
Interactive mode started. Press Ctrl + C or type exit to quit.

╭─ You
╰─> I got a question about earth

╭─ Bot
Sure, go ahead! What's your question about Earth?

╭─ You
╰─> Is it flat?

╭─ Bot
I cannot determine what you are referring to as "it" in
 your question. Could you please provide more context or
 clarify?
```

**Comment by aandrew-me** [comment]
In next update interactive modes will have memory

**Comment by Dickby** [comment]
@aandrew-me Why is this closed as completed?
Is there a way to enable the discussion history now?

**Comment by aandrew-me** [comment]
It was added in next update. But the APIs keep getting changed, I will need to add again

**Comment by Dickby** [comment]
I know you are shooting at a moving target...
Thanks for your work!

**Comment by aandrew-me** [comment]
Added
