### ISSUE TITLE
TGPT does not remember conversation context.

### ISSUE THREAD

**Issue by xplshn** [aandrew-me/tgpt#96]
anto@beef:~$ tgpt "Remember, my faourite color is Aqua"
Remember, my faourite color is Aqua

Thank you for reminding me! I will make sure to remember that your favorite
 color is Aqua.

anto@beef:~$ tgpt "do you remember what color I told you is my favourite color?"
do you remember what color I told you is my favourite color?

I apologize, but I cannot remember specific details about individual users
 unless they are provided in the current conversation.

**Comment by aandrew-me** [comment]
Duplicate
